setup.terraMiscellaneous = {
	"Daybloom_Seed": {
		name: "Daybloom_Seed",
		cn_name: "太阳花种子",
		type: "herb_seed",
		amount: V.Daybloom_Seeds || 0,
		icon: "herb/herb_seed/Daybloom_Seed.png",
	},
	"Moonglow_Seed": {
		name: "Moonglow_Seed",
		cn_name: "月光草种子",
		type: "herb_seed",
		amount: V.Moonglow_Seed || 0,
		icon: "herb/herb_seed/Moonglow_Seed.png",
	},
	"Waterleaf_Seed": {
		name: "Waterleaf_Seed",
		cn_name: "水叶草种子",
		type: "herb_seed",
		amount: V.Waterleaf_Seed || 0,
		icon: "herb/herb_seed/Waterleaf_Seed.png",
	},
	"Fireblossom_Seed": {
		name: "Fireblossom_Seed",
		cn_name: "火焰花种子",
		type: "herb_seed",
		amount: V.Fireblossom_Seed || 0,
		icon: "herb/herb_seed/Fireblossom_Seed.png",
	},
	"Shiverthorn_Seed": {
		name: "Shiverthorn_Seed",
		cn_name: "寒颤棘种子",
		type: "herb_seed",
		amount: V.Shiverthorn_Seed || 0,
		icon: "herb/herb_seed/Shiverthorn_Seed.png",
	},
	"Blinkroot_Seed": {
		name: "Blinkroot_Seed",
		cn_name: "闪耀根种子",
		type: "herb_seed",
		amount: V.Blinkroot_Seed || 0,
		icon: "herb/herb_seed/Blinkroot_Seed.png",
	},
	"Deathweed_Seed": {
		name: "Deathweed_Seed",
		cn_name: "死亡草种子",
		type: "herb_seed",
		amount: V.Deathweed_Seed || 0,
		icon: "herb/herb_seed/Deathweed_Seed.png",
	},
	"Dirt_Block": {
		name: "Dirt_Block",
		cn_name: "土块",
		type: "block",
		amount: V.Dirt_Block,
		icon: "herb/planter_block/Dirt_Block.png",
	},
	"Sand_Block": {
		name: "Sand_Block",
		cn_name: "沙块",
		type: "block",
		amount: V.Sand_Block,
		icon: "herb/planter_block/Sand_Block.png",
	},
	"Ash_Block": {
		name: "Ash_Block",
		cn_name: "灰烬块",
		type: "block",
		amount: V.Ash_Block,
		icon: "herb/planter_block/Ash_Block.png",
	},
	"Snow_Block": {
		name: "Snow_Block",
		cn_name: "雪块",
		type: "block",
		amount: V.Snow_Block,
		icon: "herb/planter_block/Snow_Block.png",
	},
	"Forest_Grass_Seed": {
		name: "Forest_Grass_Seed",
		cn_name: "森林草种子",
		type: "block",
		amount: V.Forest_Grass_Seed,
		icon: "herb/planter_block/Forest_Grass_Seed.png",
	},
	"Jungle_Grass_Seed": {
		name: "Jungle_Grass_Seed",
		cn_name: "丛林草种子",
		type: "block",
		amount: V.Jungle_Grass_Seed,
		icon: "herb/planter_block/Jungle_Grass_Seed.png",
	},
}