setup.terraAccessories = {
	"Fishing_Bobber": {
        name: "Fishing_Bobber",
        cn_name: "钓鱼浮标",
		material: true,
        type: "bobber",
        obtained: V.Fishing_Bobber,
        icon: "fishing/fishing_accessories/Fishing_Bobber.png",
		des: "增加10点渔力",
		vanity: "<i>时装</i>：改变你的浮标外观",
    },
	"Glowing_Fishing_Bobber": {
        name: "Glowing_Fishing_Bobber",
        cn_name: "发光钓鱼浮标",
		material: true,
        type: "bobber",
        obtained: V.Glowing_Fishing_Bobber,
        icon: "fishing/fishing_accessories/Glowing_Fishing_Bobber.png",
		des: "增加10点渔力",
		vanity: "<i>时装</i>：改变你的浮标外观",
    },
	"Helium_Moss_Fishing_Bobber": {
        name: "Helium_Moss_Fishing_Bobber",
        cn_name: "氦地衣钓鱼浮标",
		material: false,
        type: "bobber",
        obtained: V.Helium_Moss_Fishing_Bobber,
		/* 虽然现在用不上了，但还是感谢动车之前帮我制作的合适尺寸的gif图像！！ */
        icon: "fishing/fishing_accessories/Helium_Moss_Fishing_Bobber.gif",
		des: "增加10点渔力",
		vanity: "<i>时装</i>：改变你的浮标外观",
    },
	"Neon_Moss_Fishing_Bobber": {
        name: "Neon_Moss_Fishing_Bobber",
        cn_name: "氖地衣钓鱼浮标",
		material: false,
        type: "bobber",
        obtained: V.Neon_Moss_Fishing_Bobber,
        icon: "fishing/fishing_accessories/Neon_Moss_Fishing_Bobber.png",
		des: "增加10点渔力",
		vanity: "<i>时装</i>：改变你的浮标外观",
    },
	"Argon_Moss_Fishing_Bobber": {
        name: "Argon_Moss_Fishing_Bobber",
        cn_name: "氩地衣钓鱼浮标",
		material: false,
        type: "bobber",
        obtained: V.Argon_Moss_Fishing_Bobber,
        icon: "fishing/fishing_accessories/Argon_Moss_Fishing_Bobber.png",
		des: "增加10点渔力",
		vanity: "<i>时装</i>：改变你的浮标外观",
    },
	"Krypton_Moss_Fishing_Bobber": {
        name: "Krypton_Moss_Fishing_Bobber",
        cn_name: "氪地衣钓鱼浮标",
		material: false,
        type: "bobber",
        obtained: V.Krypton_Moss_Fishing_Bobber,
        icon: "fishing/fishing_accessories/Krypton_Moss_Fishing_Bobber.png",
		des: "增加10点渔力",
		vanity: "<i>时装</i>：改变你的浮标外观",
    },
	"Xenon_Moss_Fishing_Bobber": {
        name: "Xenon_Moss_Fishing_Bobber",
        cn_name: "氙地衣钓鱼浮标",
		material: false,
        type: "bobber",
        obtained: V.Xenon_Moss_Fishing_Bobber,
        icon: "fishing/fishing_accessories/Xenon_Moss_Fishing_Bobber.png",
		des: "增加10点渔力",
		vanity: "<i>时装</i>：改变你的浮标外观",
    },
	"Lava_Moss_Fishing_Bobber": {
        name: "Lava_Moss_Fishing_Bobber",
        cn_name: "熔岩地衣钓鱼浮标",
		material: false,
        type: "bobber",
        obtained: V.Lava_Moss_Fishing_Bobber,
        icon: "fishing/fishing_accessories/Lava_Moss_Fishing_Bobber.png",
		des: "增加10点渔力",
		vanity: "<i>时装</i>：改变你的浮标外观",
    },
	"Angler_Earring": {
        name: "Angler_Earring",
        cn_name: "渔夫耳环",
		material: true,
        type: "fishing",
        obtained: V.Angler_Earring,
        icon: "fishing/fishing_accessories/Angler_Earring.png",
		des: "增加10点渔力",
		vanity: "",
    },
	"High_Test_Fishing_Line": {
        name: "High_Test_Fishing_Line",
        cn_name: "优质钓鱼线",
		material: true,
        type: "fishing",
        obtained: V.High_Test_Fishing_Line,
        icon: "fishing/fishing_accessories/High_Test_Fishing_Line.png",
		des: "提高钓鱼小游戏中鱼线的耐久，并防止钓上鱼时鱼线断裂",
		vanity: "",
    },
	"Tackle_Box": {
        name: "Tackle_Box",
        cn_name: "钓具箱",
		material: true,
        type: "fishing",
        obtained: V.Tackle_Box,
        icon: "fishing/fishing_accessories/Tackle_Box.png",
		des: "降低钓鱼时消耗鱼饵的几率",
		vanity: "",
    },
	"Angler_Tackle_Bag": {
        name: "Angler_Tackle_Bag",
        cn_name: "渔夫渔具袋",
		material: true,
        type: "fishing",
        obtained: V.Angler_Tackle_Bag,
        icon: "fishing/fishing_accessories/Angler_Tackle_Bag.png",
		des: "组合了渔夫耳环、优质钓鱼线、钓具箱的功能：增加10点渔力，提高钓鱼小游戏中鱼线的耐久，防止钓上鱼时鱼线断裂，降低钓鱼时消耗鱼饵的几率",
		vanity: "",
    },
	"Lavaproof_Fishing_Hook": {
        name: "Lavaproof_Fishing_Hook",
        cn_name: "防熔岩钓钩",
		material: true,
        type: "fishing",
        obtained: V.Lavaproof_Fishing_Hook,
        icon: "fishing/fishing_accessories/Lavaproof_Fishing_Hook.png",
		des: "允许你用任意鱼饵和鱼竿在沸水/熔岩中钓鱼",
		vanity: "",
    },
	"Lavaproof_Tackle_Bag": {
        name: "Lavaproof_Tackle_Bag",
        cn_name: "防熔岩渔具袋",
		material: true,
        type: "fishing",
        obtained: V.Lavaproof_Tackle_Bag,
        icon: "fishing/fishing_accessories/Lavaproof_Tackle_Bag.png",
		des: "组合了渔夫耳环、优质钓鱼线、钓具箱、防熔岩钓钩的功能：增加10点渔力，提高钓鱼小游戏中鱼线的耐久，防止钓上鱼时鱼线断裂，降低钓鱼时消耗鱼饵的几率，允许你用任意鱼饵和鱼竿在沸水/熔岩中钓鱼",
		vanity: "",
    },
	"Supreme_Bait_Tackle_Box_Fishing_Station": {
        name: "Supreme_Bait_Tackle_Box_Fishing_Station",
        cn_name: "万能渔具包",
		material: false,
        type: "fishing",
        obtained: V.Supreme_Bait_Tackle_Box_Fishing_Station,
        icon: "fishing/fishing_accessories/Supreme_Bait_Tackle_Box_Fishing_Station.png",
		des: "拥有防熔岩渔具袋的全部效果，在此基础上增加50点渔力，并使钓鱼/声呐/宝匣药水持续时间翻倍<br><i>“水中鱼的噩梦，钓鱼者的最爱，泰拉人的希望，至尊渔具背包钓鱼台！”</i>",
		vanity: "",
    },
	"Inner_Tube": {
        name: "Inner_Tube",
        cn_name: "浮游圈",
		material: false,
        type: "fishing",
        obtained: V.Inner_Tube,
        icon: "accessories/Inner_Tube.png",
		des: "增加游泳能力，并在钓鱼时增加5点渔力",
		vanity: "",
    },
	"Enchanted_Pearl": {
        name: "Enchanted_Pearl",
        cn_name: "附魔珍珠",
		material: false,
        type: "fishing",
        obtained: V.Enchanted_Pearl,
        icon: "fishing/fishing_accessories/Enchanted_Pearl.png",
		des: "增加10点渔力，并增加钓到宝匣的几率",
		vanity: "",
    },
	"Fishermans_Pocket_Guide": {
        name: "Fishermans_Pocket_Guide",
        cn_name: "渔民袖珍宝典",
		material: true,
        type: "informational",
		upgrades: ["Fishermans_Pocket_Guide","Fish_Finder","PDA","Cell_Phone","Shellphone"],
        obtained: V.Fishermans_Pocket_Guide,
        icon: "fishing/fishing_accessories/Fishermans_Pocket_Guide.png",
		des: "显示当前渔力。无需装备即可生效",
		vanity: "",
    },
	"Sextant": {
        name: "Sextant",
        cn_name: "六分仪",
		material: true,
        type: "informational",
		upgrades: ["Sextant","Fish_Finder","PDA","Cell_Phone","Shellphone"],
        obtained: V.Sextant,
        icon: "fishing/fishing_accessories/Sextant.png",
		des: "显示当天月相。无需装备即可生效",
		vanity: "",
    },
	"Weather_Radio": {
        name: "Weather_Radio",
        cn_name: "天气收音机",
		material: true,
        type: "informational",
		upgrades: ["Weather_Radio","Fish_Finder","PDA","Cell_Phone","Shellphone"],
        obtained: V.Weather_Radio,
        icon: "fishing/fishing_accessories/Weather_Radio.png",
		des: "显示当前天气，并预报至多12小时内的天气。无需装备即可生效",
		vanity: "",
    },
	"Fish_Finder": {
        name: "Fish_Finder",
        cn_name: "探鱼器",
		material: true,
        type: "multiInfo",
        obtained: V.Fish_Finder,
        icon: "fishing/fishing_accessories/Fish_Finder.png",
		des: "组合了渔民袖珍宝典、六分仪、天气收音机的功能：显示当前渔力、月相、天气，并预报至多12小时内的天气。无需装备即可生效",
		vanity: "",
    },
	"Gold_Watch": {
        name: "Gold_Watch",
        cn_name: "金表",
		material: true,
        type: "informational",
		upgrades: ["Gold_Watch","GPS","PDA","Cell_Phone","Shellphone"],
        obtained: V.Gold_Watch,
        icon: "accessories/Gold_Watch.png",
		des: "可设置在特定时间提醒自己的闹钟。无需装备即可生效",
		vanity: "",
    },
	"Compass": {
        name: "Compass",
        cn_name: "罗盘",
		material: true,
        type: "informational",
		upgrades: ["Compass","GPS","PDA","Cell_Phone","Shellphone"],
        obtained: V.Compass,
        icon: "accessories/Compass.png",
		des: "位于森林、荒原、海洋时，显示当前在该区域内的具体位置。无需装备即可生效",
		vanity: "",
    },
	"Depth_Meter": {
        name: "Depth_Meter",
        cn_name: "深度计",
		material: true,
        type: "informational",
		upgrades: ["Depth_Meter","GPS","PDA","Cell_Phone","Shellphone"],
        obtained: V.Depth_Meter,
        icon: "accessories/Depth_Meter.png",
		des: "位于沼泽、走私者洞穴时，显示当前在该区域内的具体位置。无需装备即可生效",
		vanity: "",
    },
	"GPS": {
        name: "GPS",
        cn_name: "全球定位系统",
		material: true,
        type: "multiInfo",
		upgrades: ["GPS","PDA","Cell_Phone","Shellphone"],
        obtained: V.GPS,
        icon: "accessories/GPS.png",
		des: "组合了金表、罗盘、深度计的功能：可设置在特定时间提醒自己的闹钟，位于森林、荒原、海洋、沼泽、走私者洞穴时，显示当前在该区域内的具体位置，且位于特定区域时显示地图。无需装备即可生效",
		vanity: "",
    },
	"Thermometer": {
        name: "Thermometer",
        cn_name: "温度计",
		material: true,
        type: "informational",
		upgrades: ["Thermometer","Goblin_Tech","PDA","Cell_Phone","Shellphone"],
        obtained: V.Thermometer,
        icon: "accessories/Thermometer.png",
		des: "显示室外温度、室内温度与水体温度。无需装备即可生效",
		vanity: "",
    },
	"Stopwatch": {
        name: "Stopwatch",
        cn_name: "秒表",
		material: true,
        type: "informational",
		upgrades: ["Stopwatch","Goblin_Tech","PDA","Cell_Phone","Shellphone"],
        obtained: V.Stopwatch,
        icon: "accessories/Stopwatch.png",
		des: "允许在合适的地点和时机掐表消磨1分钟或5分钟。无需装备即可生效",
		vanity: "",
    },
	"Metal_Detector": {
        name: "Metal_Detector",
        cn_name: "金属探测器",
		material: true,
        type: "informational",
		upgrades: ["Metal_Detector","Goblin_Tech","PDA","Cell_Phone","Shellphone"],
        obtained: V.Metal_Detector,
        icon: "accessories/Metal_Detector.png",
		des: "与全球定位系统配合使用，在码头显示有高价值的物品的位置，以及在某些区域显示有精确位置的古董的方位。无需装备即可生效",
		vanity: "",
    },
	"Goblin_Tech": {
        name: "Goblin_Tech",
        cn_name: "哥布林数据仪",
		material: true,
        type: "multiInfo",
		upgrades: ["Goblin_Tech","PDA","Cell_Phone","Shellphone"],
        obtained: V.Goblin_Tech,
        icon: "accessories/Goblin_Tech.png",
		des: "组合了温度计、秒表、金属探测器的功能：显示室外温度、室内温度与水体温度，允许在合适的地点和时机掐表消磨1分钟或5分钟，与全球定位系统配合使用后在对应区域显示有价值的物品的位置。无需装备即可生效",
		vanity: "",
    },
	"Radar": {
        name: "Radar",
        cn_name: "雷达",
		material: true,
        type: "informational",
		upgrades: ["Radar","R_E_K_3000","PDA","Cell_Phone","Shellphone"],
        obtained: V.Radar,
        icon: "accessories/Radar.png",
		des: "在走私者进行交易时显示其位置，并配合全球定位系统在鹰塔狩猎中显示营地具体方位。无需装备即可生效",
		vanity: "",
    },
	"Lifeform_Analyzer": {
        name: "Lifeform_Analyzer",
        cn_name: "生命体分析机",
		material: true,
        type: "informational",
		upgrades: ["Lifeform_Analyzer","R_E_K_3000","PDA","Cell_Phone","Shellphone"],
        obtained: V.Lifeform_Analyzer,
        icon: "accessories/Lifeform_Analyzer.png",
		des: "显示NPC的位置（仅限主要角色）。无需装备即可生效",
		vanity: "",
    },
	"Tally_Counter": {
        name: "Tally_Counter",
        cn_name: "战斗计数器",
		material: true,
        type: "informational",
		upgrades: ["Tally_Counter","R_E_K_3000","PDA","Cell_Phone","Shellphone"],
        obtained: V.Tally_Counter,
        icon: "accessories/Tally_Counter.png",
		des: "显示在战斗中击退过的敌人类型及其数量。无需装备即可生效",
		vanity: "",
    },
	"R_E_K_3000": {
        name: "R_E_K_3000",
        cn_name: "R.E.K.3000",
		material: true,
        type: "multiInfo",
		upgrades: ["R_E_K_3000","PDA","Cell_Phone","Shellphone"],
        obtained: V.R_E_K_3000,
        icon: "accessories/R_E_K_3000.png",
		des: "组合了雷达、生命体分析机、战斗计数器的功能：在走私者进行交易时显示其位置，显示NPC的位置（仅限主要角色），显示在战斗中击退过的敌人类型及其数量。无需装备即可生效",
		vanity: "",
    },
	"PDA": {
        name: "PDA",
        cn_name: "个人数字助手",
		material: true,
        type: "multiInfo",
		upgrades: ["PDA","Cell_Phone","Shellphone"],
        obtained: V.PDA,
        icon: "accessories/PDA.png",
		des: "组合了所有信息饰品的功能。无需装备即可生效",
		vanity: "",
    },
	"Fin_Wings": {
        name: "Fin_Wings",
        cn_name: "鳍翼",
		material: false,
        type: "wings",
        obtained: V.Fin_Wings,
        icon: "accessories/Fin_Wings.png",
		des: "使你能从高处滑翔，并具有一定的飞行能力。只能配合耍蛇者长笛使用。不能代替鸟化的强健羽翼",
		vanity: "",
    },
	"Fledgling_Wings": {
        name: "Fledgling_Wings",
        cn_name: "雏翼",
		material: false,
        type: "wings",
        obtained: V.Fledgling_Wings,
        icon: "accessories/Fledgling_Wings.png",
		des: "使你能从高处滑翔",
		vanity: "",
    },
	"Blizzard_in_a_Bottle": {
        name: "Blizzard_in_a_Bottle",
        cn_name: "暴雪瓶",
		material: false,
        type: "bottle",
        obtained: V.Blizzard_in_a_Bottle,
        icon: "accessories/Blizzard_in_a_Bottle.png",
		des: "在一定程度内缓解过热",
		vanity: "",
    },
	"Sandstorm_in_a_Bottle": {
        name: "Sandstorm_in_a_Bottle",
        cn_name: "沙暴瓶",
		material: false,
        type: "bottle",
        obtained: V.Sandstorm_in_a_Bottle,
        icon: "accessories/Sandstorm_in_a_Bottle.png",
		des: "在一定程度内缓解过冷",
		vanity: "",
    },
	"Lucky_Horseshoe": {
        name: "Lucky_Horseshoe",
        cn_name: "幸运马掌",
		material: false,
        type: "none",
        obtained: V.Lucky_Horseshoe,
        icon: "accessories/Lucky_Horseshoe.png",
		des: "给你带来好运，为各技能提供加成<br><i>“据说能带来好运、驱除邪灵”</i>",
		vanity: "",
    },
	"Sailfish_Boots": {
        name: "Sailfish_Boots",
        cn_name: "航鱼靴",
		material: false,
        type: "boots",
        obtained: V.Sailfish_Boots,
        icon: "accessories/Sailfish_Boots.png",
		des: "增加运动能力，与其它靴子效果不叠加",
		vanity: "",
    },
	"Dunerider_Boots": {
        name: "Dunerider_Boots",
        cn_name: "沙丘行者靴",
		material: false,
        type: "boots",
        obtained: V.Dunerider_Boots,
        icon: "accessories/Dunerider_Boots.png",
		des: "增加运动能力，与其它靴子效果不叠加",
		vanity: "",
    },
	"Flurry_Boots": {
        name: "Flurry_Boots",
        cn_name: "疾风雪靴",
		material: false,
        type: "boots",
        obtained: V.Flurry_Boots,
        icon: "accessories/Flurry_Boots.png",
		des: "增加运动能力，与其它靴子效果不叠加",
		vanity: "",
    },
	"Ice_Skates": {
        name: "Ice_Skates",
        cn_name: "溜冰鞋",
		material: false,
        type: "none",
        obtained: V.Ice_Skates,
        icon: "accessories/Ice_Skates.png",
		des: "在冰面上行走时更加安全",
		vanity: "",
    },
	"Magiluminescence": {
        name: "Magiluminescence",
        cn_name: "魔光护符",
		material: false,
        type: "none",
        obtained: V.Magiluminescence,
        icon: "accessories/Magiluminescence.png",
		des: "可在特定地点提供照明，随时间降低<span class='lblue'>意识</span>(需在“选项-模组设置”中开启)<br><i>“我黑暗生命中的一道短暂曙光。”</i>",
		vanity: "",
    },
	"Lava_Charm": {
        name: "Lava_Charm",
        cn_name: "熔岩护身符",
		material: false,
        type: "none",
        obtained: V.Lava_Charm,
        icon: "accessories/Lava_Charm.png",
		des: "免疫熔岩、沸水、地衣等高温环境带来的催情效果",
		vanity: "",
    },
	"Ancient_Chisel": {
        name: "Ancient_Chisel",
        cn_name: "远古凿子",
		material: false,
        type: "none",
        obtained: V.Ancient_Chisel,
        icon: "accessories/Ancient_Chisel.png",
		des: "提高挖掘速度。缩短挖掘人工钓鱼池的时间<br><i>“古老的问题需要古老的解决方案”</i>",
		vanity: "",
    },
	"Angel_Halo": {
        name: "Angel_Halo",
        cn_name: "天使光环",
		material: false,
        type: "transformation",
        obtained: V.Angel_Halo,
        icon: "accessories/Angel_Halo.png",
		des: "一个天使的光环！防止天使转化点数衰退",
		vanity: "<i>时装</i>：获得仅自己可见的天使光环",
    },
	"Demon_Horns": {
        name: "Demon_Horns",
        cn_name: "恶魔角",
		material: false,
        type: "transformation",
        obtained: V.Demon_Horns,
        icon: "accessories/Demon_Horns.png",
		des: "一对恶魔的犄角！防止恶魔转化点数衰退(不会防止对应的惩罚)",
		vanity: "<i>时装</i>：获得仅自己可见的恶魔犄角",
    },
}

function getAllAccessoriesList() {
	let all_accessories_list = Object.keys(setup.terraAccessories);
	return all_accessories_list;
}
window.getAllAccessoriesList = getAllAccessoriesList;

function getAccessoriesObtained() {
	for (let accessory in setup.terraAccessories) {
        setup.terraAccessories[accessory].obtained = V[accessory];
    }
    let accessory_obtained = Object.keys(setup.terraAccessories);
    return accessory_obtained.filter(accessory => {
        return setup.terraAccessories[accessory].obtained === true;
    });
}
window.getAccessoriesObtained = getAccessoriesObtained;