setup.terraMaterial = {
	//纯材料
	"White_Pearl": {
        name: "White_Pearl",
        cn_name: "白珍珠<br><i>材料</i>",
        type: "material",
        amount: V.White_Pearl || 0,
        icon: "material/White_Pearl.png",
    },
	"Black_Pearl": {
        name: "Black_Pearl",
        cn_name: "黑珍珠<br><i>材料</i>",
        type: "material",
        amount: V.Black_Pearl || 0,
        icon: "material/Black_Pearl.png",
    },
	"Pink_Pearl": {
        name: "Pink_Pearl",
        cn_name: "粉珍珠<br><i>材料</i>",
        type: "material",
        amount: V.Pink_Pearl || 0,
        icon: "material/Pink_Pearl.png",
    },
	"Sea_Prism": {
        name: "Sea_Prism",
        cn_name: "海棱晶<br><i>材料</i>",
        type: "material",
        amount: V.Sea_Prism || 0,
        icon: "material/Sea_Prism.png",
    },
	"Iron_Bar": {
        name: "Iron_Bar",
        cn_name: "铁锭<br><i>材料</i>",
        type: "material",
        amount: V.Iron_Bar || 0,
        icon: "material/Iron_Bar.png",
    },
	"Sea_Remains": {
        name: "Sea_Remains",
        cn_name: "海洋残渣<br><i>材料</i>",
        type: "material",
        amount: V.Sea_Remains || 0,
        icon: "material/Sea_Remains.png",
    },
	"Demonic_Bone_Ash": {
        name: "Demonic_Bone_Ash",
        cn_name: "恶魔骨灰<br><i>材料</i>",
        type: "material",
        amount: V.Demonic_Bone_Ash || 0,
        icon: "material/Demonic_Bone_Ash.png",
    },
	"Fallen_Star": {
        name: "Fallen_Star",
        cn_name: "坠落之星<br><i>材料</i>",
        type: "material",
        amount: V.Fallen_Star || 0,
        icon: "material/Fallen_Star.png",
    },
	"Helium_Moss": {
        name: "Helium_Moss",
        cn_name: "氦苔藓<br><i>材料</i>",
        type: "material",
        amount: V.Helium_Moss || 0,
        icon: "material/Helium_Moss.gif",
    },
	"Neon_Moss": {
        name: "Neon_Moss",
        cn_name: "氖苔藓<br><i>材料</i>",
        type: "material",
        amount: V.Neon_Moss || 0,
        icon: "material/Neon_Moss.png",
    },
	"Argon_Moss": {
        name: "Argon_Moss",
        cn_name: "氩苔藓<br><i>材料</i>",
        type: "material",
        amount: V.Argon_Moss || 0,
        icon: "material/Argon_Moss.png",
    },
	"Krypton_Moss": {
        name: "Krypton_Moss",
        cn_name: "氪苔藓<br><i>材料</i>",
        type: "material",
        amount: V.Krypton_Moss || 0,
        icon: "material/Krypton_Moss.png",
    },
	"Xenon_Moss": {
        name: "Xenon_Moss",
        cn_name: "氙苔藓<br><i>材料</i>",
        type: "material",
        amount: V.Xenon_Moss || 0,
        icon: "material/Xenon_Moss.png",
    },
	"Lava_Moss": {
        name: "Lava_Moss",
        cn_name: "熔岩苔藓<br><i>材料</i>",
        type: "material",
        amount: V.Lava_Moss || 0,
        icon: "material/Lava_Moss.png",
    },
	//工具
	"Magic_Conch": {
        name: "Magic_Conch",
        cn_name: "魔法海螺<br><i>材料</i>",
        type: "tool",
        obtained: V.Magic_Conch,
        icon: "tool/Magic_Conch.png",
    },
	"Bug_Net": {
        name: "Bug_Net",
        cn_name: "虫网<br><i>材料</i>",
        type: "tool",
        obtained: V.Bug_Net,
        icon: "tool/Bug_Net.png",
    },
	"Bottomless_Honey_Bucket": {
        name: "Bottomless_Honey_Bucket",
        cn_name: "无底蜂蜜桶<br><i>材料</i>",
        type: "tool",
        obtained: V.Bottomless_Honey_Bucket,
        icon: "tool/Bottomless_Honey_Bucket.png",
    },
	//饰品
	"Angler_Earring": {
        name: "Angler_Earring",
        cn_name: "渔夫耳环<br><i>材料</i>",
        type: "accessory",
        obtained: V.Angler_Earring,
        icon: "fishing/fishing_accessories/Angler_Earring.png",
    },
	"High_Test_Fishing_Line": {
        name: "High_Test_Fishing_Line",
        cn_name: "优质钓鱼线<br><i>材料</i>",
        type: "accessory",
        obtained: V.High_Test_Fishing_Line,
        icon: "fishing/fishing_accessories/High_Test_Fishing_Line.png",
    },
	"Tackle_Box": {
        name: "Tackle_Box",
        cn_name: "钓具箱<br><i>材料</i>",
        type: "accessory",
        obtained: V.Tackle_Box,
        icon: "fishing/fishing_accessories/Tackle_Box.png",
    },
	"Angler_Tackle_Bag": {
        name: "Angler_Tackle_Bag",
        cn_name: "渔夫渔具袋<br><i>材料</i>",
        type: "accessory",
        obtained: V.Angler_Tackle_Bag,
        icon: "fishing/fishing_accessories/Angler_Tackle_Bag.png",
    },
	"Lavaproof_Fishing_Hook": {
        name: "Lavaproof_Fishing_Hook",
        cn_name: "防熔岩钓钩<br><i>材料</i>",
        type: "accessory",
        obtained: V.Lavaproof_Fishing_Hook,
        icon: "fishing/fishing_accessories/Lavaproof_Fishing_Hook.png",
    },
	"Lavaproof_Tackle_Bag": {
        name: "Lavaproof_Tackle_Bag",
        cn_name: "防熔岩渔具袋<br><i>材料</i>",
        type: "accessory",
        obtained: V.Lavaproof_Tackle_Bag,
        icon: "fishing/fishing_accessories/Lavaproof_Tackle_Bag.png",
    },
	"Fishermans_Pocket_Guide": {
        name: "Fishermans_Pocket_Guide",
        cn_name: "渔民袖珍宝典<br><i>材料</i>",
        type: "accessory",
        obtained: V.Fishermans_Pocket_Guide,
        icon: "fishing/fishing_accessories/Fishermans_Pocket_Guide.png",
    },
	"Sextant": {
        name: "Sextant",
        cn_name: "六分仪<br><i>材料</i>",
        type: "accessory",
        obtained: V.Sextant,
        icon: "fishing/fishing_accessories/Sextant.png",
    },
	"Weather_Radio": {
        name: "Weather_Radio",
        cn_name: "天气收音机<br><i>材料</i>",
        type: "accessory",
        obtained: V.Weather_Radio,
        icon: "fishing/fishing_accessories/Weather_Radio.png",
    },
	"Gold_Watch": {
        name: "Gold_Watch",
        cn_name: "金表<br><i>材料</i>",
        type: "accessory",
        obtained: V.Gold_Watch,
        icon: "accessories/Gold_Watch.png",
    },
	"Compass": {
        name: "Compass",
        cn_name: "罗盘<br><i>材料</i>",
        type: "accessory",
        obtained: V.Compass,
        icon: "accessories/Compass.png",
    },
	"Depth_Meter": {
        name: "Depth_Meter",
        cn_name: "深度计<br><i>材料</i>",
        type: "accessory",
        obtained: V.Depth_Meter,
        icon: "accessories/Depth_Meter.png",
    },
	"Fishing_Bobber": {
        name: "Fishing_Bobber",
        cn_name: "钓鱼浮标<br><i>材料</i>",
        type: "accessory",
        obtained: V.Fishing_Bobber,
        icon: "fishing/fishing_accessories/Fishing_Bobber.png",
    },
	"Glowing_Fishing_Bobber": {
        name: "Glowing_Fishing_Bobber",
        cn_name: "发光钓鱼浮标<br><i>材料</i>",
        type: "accessory",
        obtained: V.Glowing_Fishing_Bobber,
        icon: "fishing/fishing_accessories/Glowing_Fishing_Bobber.png",
    },
	//鱼类
	"Salmon": {
        name: "Salmon",
        cn_name: "三文鱼<br><i>材料</i>",
        type: "fish",
        amount: V.Salmon || 0,
        icon: "fishing/fish/Salmon.png",
    },
	"Bass": {
        name: "Bass",
        cn_name: "鲈鱼<br><i>材料</i>",
        type: "fish",
        amount: V.Bass || 0,
        icon: "fishing/fish/Bass.png",
    },
	"Shrimp": {
        name: "Shrimp",
        cn_name: "虾<br><i>材料</i>",
        type: "fish",
        amount: V.Shrimp || 0,
        icon: "fishing/fish/Shrimp.png",
    },
	"Tuna": {
        name: "Tuna",
        cn_name: "金枪鱼<br><i>材料</i>",
        type: "fish",
        amount: V.Tuna || 0,
        icon: "fishing/fish/Tuna.png",
    },
	"Red_Snapper": {
        name: "Red_Snapper",
        cn_name: "红鲷鱼<br><i>材料</i>",
        type: "fish",
        amount: V.Red_Snapper || 0,
        icon: "fishing/fish/Red_Snapper.png",
    },
	"Trout": {
        name: "Trout",
        cn_name: "鳟鱼<br><i>材料</i>",
        type: "fish",
        amount: V.Trout || 0,
        icon: "fishing/fish/Trout.png",
    },
	"Stinkfish": {
        name: "Stinkfish",
        cn_name: "臭味鱼<br><i>材料</i>",
        type: "fish",
        amount: V.Stinkfish || 0,
        icon: "fishing/fish/Stinkfish.png",
    },
	"Armored_Cavefish": {
        name: "Armored_Cavefish",
        cn_name: "装甲洞穴鱼<br><i>材料</i>",
        type: "fish",
        amount: V.Armored_Cavefish || 0,
        icon: "fishing/fish/Armored_Cavefish.png",
    },
	"Specular_Fish": {
        name: "Specular_Fish",
        cn_name: "装甲洞穴鱼<br><i>材料</i>",
        type: "fish",
        amount: V.Specular_Fish || 0,
        icon: "fishing/fish/Specular_Fish.png",
    },
	"Flounder": {
        name: "Flounder",
        cn_name: "偏口鱼<br><i>材料</i>",
        type: "fish",
        amount: V.Flounder || 0,
        icon: "fishing/fish/Flounder.png",
    },
	"Rock_Lobster": {
        name: "Rock_Lobster",
        cn_name: "岩石龙虾<br><i>材料</i>",
        type: "fish",
        amount: V.Rock_Lobster || 0,
        icon: "fishing/fish/Rock_Lobster.png",
    },
	"Honeyfin": {
        name: "Honeyfin",
        cn_name: "蜂蜜鱼<br><i>材料</i>",
        type: "fish",
        amount: V.Honeyfin || 0,
        icon: "fishing/fish/Honeyfin.png",
    },
	"Double_Cod": {
        name: "Double_Cod",
        cn_name: "双鳍鳕鱼<br><i>材料</i>",
        type: "fish",
        amount: V.Double_Cod || 0,
        icon: "fishing/fish/Double_Cod.png",
    },
	"Variegated_Lardfish": {
        name: "Variegated_Lardfish",
        cn_name: "斑驳油鱼<br><i>材料</i>",
        type: "fish",
        amount: V.Variegated_Lardfish || 0,
        icon: "fishing/fish/Variegated_Lardfish.png",
    },
	"Neon_Tetra": {
        name: "Neon_Tetra",
        cn_name: "霓虹脂鲤<br><i>材料</i>",
        type: "fish",
        amount: V.Neon_Tetra || 0,
        icon: "fishing/fish/Neon_Tetra.png",
    },
	"Chaos_Fish": {
        name: "Chaos_Fish",
        cn_name: "混沌鱼<br><i>材料</i>",
        type: "fish",
        amount: V.Chaos_Fish || 0,
        icon: "fishing/fish/Chaos_Fish.png",
    },
	"Prismite": {
        name: "Prismite",
        cn_name: "七彩矿鱼<br><i>材料</i>",
        type: "fish",
        amount: V.Prismite || 0,
        icon: "fishing/fish/Prismite.png",
    },
	"Princess_Fish": {
        name: "Princess_Fish",
        cn_name: "公主鱼<br><i>材料</i>",
        type: "fish",
        amount: V.Princess_Fish || 0,
        icon: "fishing/fish/Princess_Fish.png",
    },
	"Frost_Minnow": {
        name: "Frost_Minnow",
        cn_name: "寒霜绦鱼<br><i>材料</i>",
        type: "fish",
        amount: V.Frost_Minnow || 0,
        icon: "fishing/fish/Frost_Minnow.png",
    },
	"Atlantic_Cod": {
        name: "Atlantic_Cod",
        cn_name: "大西洋鳕鱼<br><i>材料</i>",
        type: "fish",
        amount: V.Atlantic_Cod || 0,
        icon: "fishing/fish/Atlantic_Cod.png",
    },
	"Flarefin_Koi": {
        name: "Flarefin_Koi",
        cn_name: "闪鳍锦鲤<br><i>材料</i>",
        type: "fish",
        amount: V.Flarefin_Koi || 0,
        icon: "fishing/fish/Flarefin_Koi.png",
    },
	"Obsidifish": {
        name: "Obsidifish",
        cn_name: "黑曜石鱼<br><i>材料</i>",
        type: "fish",
        amount: V.Obsidifish || 0,
        icon: "fishing/fish/Obsidifish.png",
    },
	"Sunken_Sailfish": {
        name: "Sunken_Sailfish",
        cn_name: "沉沦帆鱼<br><i>材料</i>",
        type: "fish",
        amount: V.Sunken_Sailfish || 0,
        icon: "fishing/fish/Sunken_Sailfish.png",
    },
	"Prismatic_Guppy": {
        name: "Prismatic_Guppy",
        cn_name: "棱晶孔雀鱼<br><i>材料</i>",
        type: "fish",
        amount: V.Prismatic_Guppy || 0,
        icon: "fishing/fish/Prismatic_Guppy.png",
    },
	"Coastal_Demonfish": {
        name: "Coastal_Demonfish",
        cn_name: "海岸恶魔鱼<br><i>材料</i>",
        type: "fish",
        amount: V.Coastal_Demonfish || 0,
        icon: "fishing/fish/Coastal_Demonfish.png",
    },
	"Crag_Bullhead": {
        name: "Crag_Bullhead",
        cn_name: "硫火崖回鱼<br><i>材料</i>",
        type: "fish",
        amount: V.Crag_Bullhead || 0,
        icon: "fishing/fish/Crag_Bullhead.png",
    },
	"Honeyfin": {
        name: "Honeyfin",
        cn_name: "蜂蜜鱼<br><i>材料</i>",
        type: "fish",
        amount: V.Honeyfin || 0,
        icon: "fishing/fish/Honeyfin.png",
    },
	"Sashimi": {
        name: "Sashimi",
        cn_name: "生鱼片<br><i>材料</i>",
        type: "food",
        amount: V.Sashimi || 0,
        icon: "food/Sashimi.png",
    },
	//鱼饵
	"Apprentice_Bait": {
        name: "Apprentice_Bait",
        cn_name: "学徒诱饵<br><i>材料</i>",
        type: "bait",
        amount: V.Apprentice_Bait || 0,
        icon: "fishing/bait/Apprentice_Bait.png",
    },
	"Journeyman_Bait": {
        name: "Journeyman_Bait",
        cn_name: "熟手诱饵<br><i>材料</i>",
        type: "bait",
        amount: V.Journeyman_Bait || 0,
        icon: "fishing/bait/Journeyman_Bait.png",
    },
	"Master_Bait": {
        name: "Master_Bait",
        cn_name: "大师诱饵<br><i>材料</i>",
        type: "bait",
        amount: V.Master_Bait || 0,
        icon: "fishing/bait/Master_Bait.png",
    },
	"Worm": {
        name: "Worm",
        cn_name: "蠕虫<br><i>材料</i>",
        type: "bait",
        amount: V.Worm || 0,
        icon: "fishing/bait/Worm.png",
    },
	// 药水
	"Fishing_Potion": {
        name: "Fishing_Potion",
        cn_name: "钓鱼药水<br><i>材料</i>",
        type: "bait",
        amount: V.Fishing_Potion || 0,
        icon: "potions/Fishing_Potion.png",
    },
	"Sonar_Potion": {
        name: "Sonar_Potion",
        cn_name: "声呐药水<br><i>材料</i>",
        type: "bait",
        amount: V.Sonar_Potion || 0,
        icon: "potions/Sonar_Potion.png",
    },
	"Crate_Potion": {
        name: "Crate_Potion",
        cn_name: "宝匣药水<br><i>材料</i>",
        type: "bait",
        amount: V.Crate_Potion || 0,
        icon: "potions/Crate_Potion.png",
    },
}

function getAllMaterialList() {
	for (let material in setup.terraMaterial) {
        setup.terraMaterial[material].amount = V[material] || 0;
    }
    let all_material_list = Object.keys(setup.terraMaterial);
	return all_material_list;
}
window.getAllMaterialList = getAllMaterialList;

function getMaterialObtainedList() {
	for (let material in setup.terraMaterial) {
        setup.terraMaterial[material].amount = V[material] || 0;
    }
    let material_obtained = Object.keys(setup.terraMaterial);
    return material_obtained.filter(material => {
        return setup.terraMaterial[material].amount > 0 || setup.terraMaterial[material].obtained === true;
    });
}
window.getMaterialObtainedList = getMaterialObtainedList;