/*
	非常逆天的合成配方字典
	name: 产物代号/英文名
	cn_name: 产物中文名
	des: 产物的信息描述
	type: 产物的种类(饰品/工具/食物等等)
	amount/obtained: 持有产物的数量/是否持有产物
	icon: 产物图标
	required_material: 合成产物所需的材料种类英文名
	required_material_info: 合成产物所需的具体材料图标、中文名与对应的数量
	required_crafting_station: 合成需要的制作站英文名，用于在不同的制作站调用配方
	required_crafting_station_info: 合成需要的制作站的图标
	craftable: 判断身上是否有足够的材料用于合成物品，_craftable在满足条件时定义为true，否则为false
	craft: 合成时计算材料消耗并获得产物
	crafting_info: 合成物品后，显示合成的物品为何，持有的产物数量以及剩余的原料数量
*/
setup.terraRecipe = {
	//饰品和工具
	"Enchanted_Pearl": {
        name: "Enchanted_Pearl",
        cn_name: "附魔珍珠",
		des: "增加渔力，并增加钓到宝匣的几率",
        type: "accessories",
        amount: V.Enchanted_Pearl,
        icon: "fishing/fishing_accessories/Enchanted_Pearl.png",
		required_material: ["White_Pearl","Sea_Prism","Sea_Remains"],
		required_material_info: "<<icon \"material/White_Pearl.png\">>白珍珠(1)<br><<icon \"material/Sea_Prism.png\">>海棱晶(10)<br><<icon \"material/Sea_Remains.png\">>海洋残渣(3)",
		required_crafting_station: "Iron_Anvil",
		required_crafting_station_info: "<<icon \"furniture_item/Iron_Anvil.png\">>铁砧",
		craftable: "<<set _craftable to ($White_Pearl gte 1 and $Sea_Prism gte 10 and $Sea_Remains gte 3 and $Enchanted_Pearl isnot true) ? true : false>>",
		craft: "<<set $White_Pearl -= 1>><<set $Sea_Prism -= 10>><<set $Sea_Remains -= 3>><<set $Enchanted_Pearl to true>>",
		crafting_info: "你制作了1个<<icon \"fishing/fishing_accessories/Enchanted_Pearl.png\">>附魔珍珠。",
    },
	"Demon_Conch": {
        name: "Demon_Conch",
        cn_name: "恶魔海螺",
		des: "使用后将你传送至地下熔岩湖",
        type: "tool",
        amount: V.Demon_Conch,
        icon: "tool/Demon_Conch.png",
		required_material: ["Magic_Conch","Demonic_Bone_Ash"],
		required_material_info: "<<icon \"tool/Magic_Conch.png\">>魔法海螺<br><<icon \"material/Demonic_Bone_Ash.png\">>恶魔骨灰(5)",
		required_crafting_station: "Hellforge",
		required_crafting_station_info: "<<icon \"furniture_item/Hellforge.png\">>地狱熔炉",
		craftable: "<<set _craftable to ($Magic_Conch and $Demonic_Bone_Ash gte 5 and $Demon_Conch isnot true) ? true : false>>",
		craft: "<<set $Magic_Conch to undefined>><<set $Demonic_Bone_Ash -= 5>><<set $Demon_Conch to true>>",
		crafting_info: "你制作了1个<<icon \"tool/Demon_Conch.png\">>恶魔海螺。",
    },
	"Lavaproof_Bug_Net": {
        name: "Lavaproof_Bug_Net",
        cn_name: "防熔岩虫网",
		des: "可以用来和罗宾在森林捕捉小动物，还可以在森林湖边、雷米庄园门口抓蜻蜓。也可以捕捉熔岩小动物！",
        type: "tool",
        amount: V.Lavaproof_Bug_Net,
        icon: "tool/Lavaproof_Bug_Net.png",
		required_material: ["Bug_Net","Demonic_Bone_Ash"],
		required_material_info: "<<icon \"tool/Bug_Net.png\">>虫网<br><<icon \"material/Demonic_Bone_Ash.png\">>恶魔骨灰(5)",
		required_crafting_station: "Hellforge",
		required_crafting_station_info: "<<icon \"furniture_item/Hellforge.png\">>地狱熔炉",
		craftable: "<<set _craftable to ($Bug_Net and $Demonic_Bone_Ash gte 5 and $Lavaproof_Bug_Net isnot true) ? true : false>>",
		craft: "<<set $Bug_Net to undefined>><<set $Demonic_Bone_Ash -= 5>><<set $Lavaproof_Bug_Net to true>>",
		crafting_info: "你制作了1个<<icon \"tool/Lavaproof_Bug_Net.png\">>防熔岩虫网。",
    },
	"Mana_Crystal": {
		name: "Mana_Crystal",
        cn_name: "魔力水晶",
		des: "用坠落之星的魔力汇聚而成，使用后可以对已有的催眠特质起到抵消作用，使随机一项催眠特质降级",
        type: "tool",
        icon: "tool/Mana_Crystal.png",
		required_material: ["Fallen_Star"],
		required_material_info: "<<icon \"material/Fallen_Star.png\">>坠落之星(5)",
		required_crafting_station: "Work_Bench",
		required_crafting_station_info: "<<icon \"furniture_item/Work_Bench.png\">>工作台",
		craftable: "<<set _craftable to $Fallen_Star gte 5 ? true : false>>",
		craft: "<<set $Fallen_Star -= 5>><<set $Mana_Crystal += 1>>",
		crafting_info: "你制作了1个<<icon \"tool/Mana_Crystal.png\">>魔力水晶。<br>你有<<icon \"tool/Mana_Crystal.png\">>魔力水晶($Mana_Crystal)，你还有<<icon \"material/Fallen_Star.png\">>坠落之星($Fallen_Star)。",
	},
	"Iron_Anvil": {
        name: "Iron_Anvil",
        cn_name: "铁砧",
		des: "用于制作以金属锭为原料的物品",
        type: "furniture",
        amount: V.Iron_Anvil,
        icon: "furniture_item/Iron_Anvil.png",
		required_material: ["Iron_Bar"],
		required_material_info: "需要有C级家务技能<br><<icon \"material/Iron_Bar.png\">>铁锭(5)",
		required_crafting_station: "Work_Bench",
		required_crafting_station_info: "<<icon \"furniture_item/Work_Bench.png\">>工作台",
		craftable: "<<set _craftable to (currentSkillValue('housekeeping') gte 400 and $Iron_Bar gte 5 and !$orphanage_loft_crafting_station.includes(\"Iron_Anvil\")) ? true : false>>",
		craft: "<<set $Iron_Bar -= 5>><<set $orphanage_loft_crafting_station.pushUnique(\"Iron_Anvil\")>>",
		crafting_info: "你制作了1个<<icon \"furniture_item/Iron_Anvil.png\">>铁砧，将它放在了阁楼。",
    },
	"Cooking_Pot": {
        name: "Cooking_Pot",
        cn_name: "烹饪锅",
		des: "用于食物制作",
        type: "furniture",
        amount: V.Cooking_Pot,
        icon: "furniture_item/Cooking_Pot.png",
		required_material: ["Iron_Bar"],
		required_material_info: "需要有B级家务技能<br><<icon \"material/Iron_Bar.png\">>铁锭(10)",
		required_crafting_station: "Iron_Anvil",
		required_crafting_station_info: "<<icon \"furniture_item/Iron_Anvil.png\">>铁砧",
		craftable: "<<set _craftable to (currentSkillValue('housekeeping') gte 600 and $Iron_Bar gte 10 and !$orphanage_loft_crafting_station.includes(\"Cooking_Pot\")) ? true : false>>",
		craft: "<<set $Iron_Bar -= 10>><<set $orphanage_loft_crafting_station.pushUnique(\"Cooking_Pot\")>>",
		crafting_info: "你制作了1个<<icon \"furniture_item/Cooking_Pot.png\">>烹饪锅，将它放在了阁楼。",
    },
	"Angler_Tackle_Bag": {
        name: "Angler_Tackle_Bag",
        cn_name: "渔夫渔具袋<br><i>材料</i>",
		des: "结合了其合成材料的效果：钓鱼线永远不会断，降低鱼饵消耗几率，渔力增加10",
        type: "accessories",
        amount: V.Angler_Tackle_Bag,
        icon: "fishing/fishing_accessories/Angler_Tackle_Bag.png",
		required_material: ["Angler_Earring","High_Test_Fishing_Line","Tackle_Box"],
		required_material_info: "<<icon \"fishing/fishing_accessories/Angler_Earring.png\">>渔夫耳环<br><<icon \"fishing/fishing_accessories/High_Test_Fishing_Line.png\">>优质钓鱼线<br><<icon \"fishing/fishing_accessories/Tackle_Box.png\">>钓具箱",
		required_crafting_station: "Tinkerers_Workshop",
		required_crafting_station_info: "<<icon \"furniture_item/Tinkerers_Workshop.png\">>工匠作坊",
		craftable: "<<set _craftable to ($Angler_Earring and $High_Test_Fishing_Line and $Tackle_Box and $Angler_Tackle_Bag isnot true) ? true : false>>",
		craft: "<<unset $Angler_Earring>><<set $terra_accessories_slots.delete('Angler_Earring')>><<set $terra_vanity_accessories_slots.delete('Angler_Earring')>><<unset $High_Test_Fishing_Line>><<set $terra_accessories_slots.delete('High_Test_Fishing_Line')>><<set $terra_vanity_accessories_slots.delete('High_Test_Fishing_Line')>><<unset $Tackle_Box>><<set $terra_accessories_slots.delete('Tackle_Box')>><<set $terra_vanity_accessories_slots.delete('Tackle_Box')>><<set $Angler_Tackle_Bag to true>>",
		crafting_info: "你制作了1个<<icon \"fishing/fishing_accessories/Angler_Tackle_Bag.png\">>渔夫渔具袋。",
    },
	"Lavaproof_Tackle_Bag": {
        name: "Lavaproof_Tackle_Bag",
        cn_name: "防熔岩渔具袋",
		des: "结合了其合成材料的效果：钓鱼线永远不会断，降低鱼饵消耗几率，渔力增加10，可在沸水/熔岩中钓鱼",
        type: "accessories",
        amount: V.Lavaproof_Tackle_Bag,
        icon: "fishing/fishing_accessories/Lavaproof_Tackle_Bag.png",
		required_material: ["Lavaproof_Fishing_Hook","Angler_Tackle_Bag"],
		required_material_info: "<<icon \"fishing/fishing_accessories/Angler_Tackle_Bag.png\">>渔夫渔具袋<br><<icon \"fishing/fishing_accessories/Lavaproof_Fishing_Hook.png\">>防熔岩钓钩",
		required_crafting_station: "Tinkerers_Workshop",
		required_crafting_station_info: "<<icon \"furniture_item/Tinkerers_Workshop.png\">>工匠作坊",
		craftable: "<<set _craftable to ($Angler_Tackle_Bag and $Lavaproof_Fishing_Hook and $Lavaproof_Tackle_Bag isnot true) ? true : false>>",
		craft: "<<unset $Angler_Tackle_Bag>><<set $terra_accessories_slots.delete('Angler_Tackle_Bag')>><<set $terra_vanity_accessories_slots.delete('Angler_Tackle_Bag')>><<unset $Lavaproof_Fishing_Hook>><<set $terra_accessories_slots.delete('Lavaproof_Fishing_Hook')>><<set $terra_vanity_accessories_slots.delete('Lavaproof_Fishing_Hook')>><<set $Lavaproof_Tackle_Bag to true>>",
		crafting_info: "你制作了1个<<icon \"fishing/fishing_accessories/Lavaproof_Tackle_Bag.png\">>防熔岩渔具袋。",
    },
	"Supreme_Bait_Tackle_Box_Fishing_Station": {
        name: "Supreme_Bait_Tackle_Box_Fishing_Station",
        cn_name: "万能渔具包",
		des: "拥有<<icon \"fishing/fishing_accessories/Lavaproof_Tackle_Bag.png\">>防熔岩渔具袋的全部效果，在此基础上增加50点渔力，并使<<icon 'potions/Fishing_Potion.png'>>钓鱼/<<icon 'potions/Sonar_Potion.png'>>声呐/<<icon 'potions/Crate_Potion.png'>>宝匣药水持续时间翻倍<br><i>\"水中鱼的噩梦，钓鱼者的最爱，泰拉人的希望，至尊渔具背包钓鱼台！\"</i>",
        type: "accessories",
        amount: V.Supreme_Bait_Tackle_Box_Fishing_Station,
        icon: "fishing/fishing_accessories/Supreme_Bait_Tackle_Box_Fishing_Station.png",
		required_material: ["Lavaproof_Tackle_Bag","Pink_Pearl","Master_Bait","Fishing_Potion","Sonar_Potion","Crate_Potion"],
		required_material_info: "<<icon \"fishing/fishing_accessories/Lavaproof_Tackle_Bag.png\">>防熔岩渔具袋<br><<icon 'material/Pink_Pearl.png'>>粉珍珠(1)<br><<icon 'fishing/bait/Master_Bait.png'>>大师诱饵(5)<br><<icon 'potions/Fishing_Potion.png'>>钓鱼药水(5)<br><<icon 'potions/Sonar_Potion.png'>>声呐药水(5)<br><<icon 'potions/Crate_Potion.png'>>宝匣药水(5)",
		required_crafting_station: "Iron_Anvil",
		required_crafting_station_info: "<<icon \"furniture_item/Iron_Anvil.png\">>铁砧",
		craftable: "<<set _craftable to ($Lavaproof_Tackle_Bag and $Pink_Pearl gte 1 and $Master_Bait gte 5 and $Fishing_Potion gte 5 and $Sonar_Potion gte 5 and $Crate_Potion gte 5 and $Supreme_Bait_Tackle_Box_Fishing_Station isnot true) ? true : false>>",
		craft: "<<unset $Lavaproof_Tackle_Bag>><<set $terra_accessories_slots.delete('Lavaproof_Tackle_Bag')>><<set $terra_vanity_accessories_slots.delete('Lavaproof_Tackle_Bag')>><<set $Pink_Pearl -= 5>><<set $Master_Bait -= 5>><<set $Fishing_Potion -= 5>><<set $Sonar_Potion -= 5>><<set $Crate_Potion -= 5>><<set $Supreme_Bait_Tackle_Box_Fishing_Station to true>>",
		crafting_info: "你制作了1个<<icon \"fishing/fishing_accessories/Supreme_Bait_Tackle_Box_Fishing_Station.png\">>万能渔具包。",
    },
	"Fish_Finder": {
        name: "Fish_Finder",
        cn_name: "探鱼器",
		des: "结合了其合成材料的效果：显示天气、月相和钓鱼信息",
        type: "accessories",
        amount: V.Fish_Finder,
        icon: "fishing/fishing_accessories/Fish_Finder.png",
		required_material: ["Fishermans_Pocket_Guide","Sextant","Weather_Radio"],
		required_material_info: "<<icon \"fishing/fishing_accessories/Fishermans_Pocket_Guide.png\">>渔民袖珍宝典<br><<icon \"fishing/fishing_accessories/Sextant.png\">>六分仪<br><<icon \"fishing/fishing_accessories/Weather_Radio.png\">>天气收音机",
		required_crafting_station: "Tinkerers_Workshop",
		required_crafting_station_info: "<<icon \"furniture_item/Tinkerers_Workshop.png\">>工匠作坊",
		craftable: "<<set _craftable to ($Fishermans_Pocket_Guide and $Sextant and $Weather_Radio and $Fish_Finder isnot true) ? true : false>>",
		craft: "<<unset $Fishermans_Pocket_Guide>><<set $terra_accessories_slots.delete('Fishermans_Pocket_Guide')>><<set $terra_vanity_accessories_slots.delete('Fishermans_Pocket_Guide')>><<unset $Sextant>><<set $terra_accessories_slots.delete('Sextant')>><<set $terra_vanity_accessories_slots.delete('Sextant')>><<unset $Weather_Radio>><<set $terra_accessories_slots.delete('Weather_Radio')>><<set $terra_vanity_accessories_slots.delete('Weather_Radio')>><<set $Fish_Finder to true>>",
		crafting_info: "你制作了1个<<icon \"fishing/fishing_accessories/Fish_Finder.png\">>探鱼器。",
    },
	"GPS": {
        name: "GPS",
        cn_name: "全球定位系统",
		des: "结合了其合成材料的效果：闹钟提醒、位于特定区域时显示所处的具体位置。并在旧下水道、老教堂墓地（未实装）时显示该区域的地图。",
        type: "accessories",
        amount: V.GPS,
        icon: "accessories/GPS.png",
		required_material: ["Gold_Watch","Compass","Depth_Meter"],
		required_material_info: "<<icon 'accessories/Gold_Watch.png'>>金表<br><<icon 'accessories/Compass.png'>>罗盘<br><<icon 'accessories/Depth_Meter.png'>>深度计",
		required_crafting_station: "Tinkerers_Workshop",
		required_crafting_station_info: "<<icon 'furniture_item/Tinkerers_Workshop.png'>>工匠作坊",
		craftable: "<<set _craftable to ($Gold_Watch and $Compass and $Depth_Meter and $GPS isnot true) ? true : false>>",
		craft: "<<unset $Gold_Watch>><<set $terra_accessories_slots.delete('Gold_Watch')>><<set $terra_vanity_accessories_slots.delete('Gold_Watch')>><<unset $Compass>><<set $terra_accessories_slots.delete('Compass')>><<set $terra_vanity_accessories_slots.delete('Compass')>><<unset $Depth_Meter>><<set $terra_accessories_slots.delete('Depth_Meter')>><<set $terra_vanity_accessories_slots.delete('Depth_Meter')>><<set $GPS to true>>",
		crafting_info: "你制作了1个<<icon 'accessories/GPS.png'>>全球定位系统。",
    },
	"Glowing_Fishing_Bobber": {
        name: "Glowing_Fishing_Bobber",
        cn_name: "发光钓鱼浮标<br><i>材料</i>",
		des: "增加10点渔力。你的浮标现在会发光",
        type: "accessories",
        amount: V.Glowing_Fishing_Bobber,
        icon: "fishing/fishing_accessories/Glowing_Fishing_Bobber.png",
		required_material: ["Fishing_Bobber","Fallen_Star"],
		required_material_info: "<<icon \"fishing/fishing_accessories/Fishing_Bobber.png\">>钓鱼浮标<br><<icon \"material/Fallen_Star.png\">>坠落之星(5)",
		required_crafting_station: "Tinkerers_Workshop",
		required_crafting_station_info: "<<icon \"furniture_item/Tinkerers_Workshop.png\">>工匠作坊",
		craftable: "<<set _craftable to ($Fishing_Bobber and $Fallen_Star gte 5 and $Glowing_Fishing_Bobber isnot true) ? true : false>>",
		craft: "<<unset $Fishing_Bobber>><<set $terra_accessories_slots.delete('Fishing_Bobber')>><<set $terra_vanity_accessories_slots.delete('Fishing_Bobber')>><<set $Fallen_Star -= 5>><<set $Glowing_Fishing_Bobber to true>>",
		crafting_info: "你制作了1个<<icon \"fishing/fishing_accessories/Glowing_Fishing_Bobber.png\">>发光钓鱼浮标。",
    },
	"Helium_Moss_Fishing_Bobber": {
        name: "Helium_Moss_Fishing_Bobber",
        cn_name: "氦苔藓钓鱼浮标",
		des: "增加10点渔力。你的浮标现在会发光",
        type: "accessories",
        amount: V.Helium_Moss_Fishing_Bobber,
        icon: "fishing/fishing_accessories/Helium_Moss_Fishing_Bobber.gif",
		required_material: ["Glowing_Fishing_Bobber","Helium_Moss"],
		required_material_info: "<<icon \"fishing/fishing_accessories/Glowing_Fishing_Bobber.png\">>发光钓鱼浮标<br><<icon \"material/Helium_Moss.gif\">>氦苔藓(5)",
		required_crafting_station: "Tinkerers_Workshop",
		required_crafting_station_info: "<<icon \"furniture_item/Tinkerers_Workshop.png\">>工匠作坊",
		craftable: "<<set _craftable to ($Glowing_Fishing_Bobber and $Helium_Moss gte 5 and $Helium_Moss_Fishing_Bobber isnot true) ? true : false>>",
		craft: "<<unset $Glowing_Fishing_Bobber>><<set $terra_accessories_slots.delete('Glowing_Fishing_Bobber')>><<set $terra_vanity_accessories_slots.delete('Glowing_Fishing_Bobber')>><<set $Helium_Moss -= 5>><<set $Helium_Moss_Fishing_Bobber to true>>",
		crafting_info: "你制作了1个<<icon \"fishing/fishing_accessories/Helium_Moss_Fishing_Bobber.gif\">>氦苔藓钓鱼浮标。",
    },
	"Neon_Moss_Fishing_Bobber": {
        name: "Neon_Moss_Fishing_Bobber",
        cn_name: "氖苔藓钓鱼浮标",
		des: "增加10点渔力。你的浮标现在会发光",
        type: "accessories",
        amount: V.Neon_Moss_Fishing_Bobber,
        icon: "fishing/fishing_accessories/Neon_Moss_Fishing_Bobber.png",
		required_material: ["Glowing_Fishing_Bobber","Neon_Moss"],
		required_material_info: "<<icon \"fishing/fishing_accessories/Glowing_Fishing_Bobber.png\">>发光钓鱼浮标<br><<icon \"material/Neon_Moss.png\">>氖苔藓(5)",
		required_crafting_station: "Tinkerers_Workshop",
		required_crafting_station_info: "<<icon \"furniture_item/Tinkerers_Workshop.png\">>工匠作坊",
		craftable: "<<set _craftable to ($Glowing_Fishing_Bobber and $Neon_Moss gte 5 and $Neon_Moss_Fishing_Bobber isnot true) ? true : false>>",
		craft: "<<unset $Glowing_Fishing_Bobber>><<set $terra_accessories_slots.delete('Glowing_Fishing_Bobber')>><<set $terra_vanity_accessories_slots.delete('Glowing_Fishing_Bobber')>><<set $Neon_Moss -= 5>><<set $Neon_Moss_Fishing_Bobber to true>>",
		crafting_info: "你制作了1个<<icon \"fishing/fishing_accessories/Neon_Moss_Fishing_Bobber.png\">>氖苔藓钓鱼浮标。",
    },
	"Argon_Moss_Fishing_Bobber": {
        name: "Argon_Moss_Fishing_Bobber",
        cn_name: "氩苔藓钓鱼浮标",
		des: "增加10点渔力。你的浮标现在会发光",
        type: "accessories",
        amount: V.Argon_Moss_Fishing_Bobber,
        icon: "fishing/fishing_accessories/Argon_Moss_Fishing_Bobber.png",
		required_material: ["Glowing_Fishing_Bobber","Argon_Moss"],
		required_material_info: "<<icon \"fishing/fishing_accessories/Glowing_Fishing_Bobber.png\">>发光钓鱼浮标<br><<icon \"material/Argon_Moss.png\">>氩苔藓(5)",
		required_crafting_station: "Tinkerers_Workshop",
		required_crafting_station_info: "<<icon \"furniture_item/Tinkerers_Workshop.png\">>工匠作坊",
		craftable: "<<set _craftable to ($Glowing_Fishing_Bobber and $Argon_Moss gte 5 and $Argon_Moss_Fishing_Bobber isnot true) ? true : false>>",
		craft: "<<unset $Glowing_Fishing_Bobber>><<set $terra_accessories_slots.delete('Glowing_Fishing_Bobber')>><<set $terra_vanity_accessories_slots.delete('Glowing_Fishing_Bobber')>><<set $Argon_Moss -= 5>><<set $Argon_Moss_Fishing_Bobber to true>>",
		crafting_info: "你制作了1个<<icon \"fishing/fishing_accessories/Argon_Moss_Fishing_Bobber.png\">>氩苔藓钓鱼浮标。",
    },
	"Krypton_Moss_Fishing_Bobber": {
        name: "Krypton_Moss_Fishing_Bobber",
        cn_name: "氪苔藓钓鱼浮标",
		des: "增加10点渔力。你的浮标现在会发光",
        type: "accessories",
        amount: V.Krypton_Moss_Fishing_Bobber,
        icon: "fishing/fishing_accessories/Krypton_Moss_Fishing_Bobber.png",
		required_material: ["Glowing_Fishing_Bobber","Krypton_Moss"],
		required_material_info: "<<icon \"fishing/fishing_accessories/Glowing_Fishing_Bobber.png\">>发光钓鱼浮标<br><<icon \"material/Krypton_Moss.png\">>氪苔藓(5)",
		required_crafting_station: "Tinkerers_Workshop",
		required_crafting_station_info: "<<icon \"furniture_item/Tinkerers_Workshop.png\">>工匠作坊",
		craftable: "<<set _craftable to ($Glowing_Fishing_Bobber and $Krypton_Moss gte 5 and $Krypton_Moss_Fishing_Bobber isnot true) ? true : false>>",
		craft: "<<unset $Glowing_Fishing_Bobber>><<set $terra_accessories_slots.delete('Glowing_Fishing_Bobber')>><<set $terra_vanity_accessories_slots.delete('Glowing_Fishing_Bobber')>><<set $Krypton_Moss -= 5>><<set $Krypton_Moss_Fishing_Bobber to true>>",
		crafting_info: "你制作了1个<<icon \"fishing/fishing_accessories/Krypton_Moss_Fishing_Bobber.png\">>氪苔藓钓鱼浮标。",
    },
	"Xenon_Moss_Fishing_Bobber": {
        name: "Xenon_Moss_Fishing_Bobber",
        cn_name: "氙苔藓钓鱼浮标",
		des: "增加10点渔力。你的浮标现在会发光",
        type: "accessories",
        amount: V.Xenon_Moss_Fishing_Bobber,
        icon: "fishing/fishing_accessories/Xenon_Moss_Fishing_Bobber.png",
		required_material: ["Glowing_Fishing_Bobber","Xenon_Moss"],
		required_material_info: "<<icon \"fishing/fishing_accessories/Glowing_Fishing_Bobber.png\">>发光钓鱼浮标<br><<icon \"material/Xenon_Moss.png\">>氙苔藓(5)",
		required_crafting_station: "Tinkerers_Workshop",
		required_crafting_station_info: "<<icon \"furniture_item/Tinkerers_Workshop.png\">>工匠作坊",
		craftable: "<<set _craftable to ($Glowing_Fishing_Bobber and $Xenon_Moss gte 5 and $Xenon_Moss_Fishing_Bobber isnot true) ? true : false>>",
		craft: "<<unset $Glowing_Fishing_Bobber>><<set $terra_accessories_slots.delete('Glowing_Fishing_Bobber')>><<set $terra_vanity_accessories_slots.delete('Glowing_Fishing_Bobber')>><<set $Xenon_Moss -= 5>><<set $Xenon_Moss_Fishing_Bobber to true>>",
		crafting_info: "你制作了1个<<icon \"fishing/fishing_accessories/Xenon_Moss_Fishing_Bobber.png\">>氙苔藓钓鱼浮标。",
    },
	"Lava_Moss_Fishing_Bobber": {
        name: "Lava_Moss_Fishing_Bobber",
        cn_name: "熔岩苔藓钓鱼浮标",
		des: "增加10点渔力。你的浮标现在会发光",
        type: "accessories",
        amount: V.Lava_Moss_Fishing_Bobber,
        icon: "fishing/fishing_accessories/Lava_Moss_Fishing_Bobber.png",
		required_material: ["Glowing_Fishing_Bobber","Lava_Moss"],
		required_material_info: "<<icon \"fishing/fishing_accessories/Glowing_Fishing_Bobber.png\">>发光钓鱼浮标<br><<icon \"material/Lava_Moss.png\">>熔岩苔藓(5)",
		required_crafting_station: "Tinkerers_Workshop",
		required_crafting_station_info: "<<icon \"furniture_item/Tinkerers_Workshop.png\">>工匠作坊",
		craftable: "<<set _craftable to ($Glowing_Fishing_Bobber and $Lava_Moss gte 5 and $Lava_Moss_Fishing_Bobber isnot true) ? true : false>>",
		craft: "<<unset $Glowing_Fishing_Bobber>><<set $terra_accessories_slots.delete('Glowing_Fishing_Bobber')>><<set $terra_vanity_accessories_slots.delete('Glowing_Fishing_Bobber')>><<set $Lava_Moss -= 5>><<set $Lava_Moss_Fishing_Bobber to true>>",
		crafting_info: "你制作了1个<<icon \"fishing/fishing_accessories/Lava_Moss_Fishing_Bobber.png\">>熔岩苔藓钓鱼浮标。",
    },
	//生鱼片：可由 三文鱼、鲈鱼、金枪鱼、红鲷鱼、鳟鱼、偏口鱼、大西洋鳕鱼、棱晶孔雀鱼、硫火崖回鱼 在 工作台 上制作得到
	"Sashimi_Salmon": {
		name: "Sashimi",
        cn_name: "生鱼片<br><i>材料</i>",
		des: "- 饥饿值<br><i>“是生的！异国风味！”</i>",
        type: "food",
        amount: V.Sashimi || 0,
        icon: "food/Sashimi.png",
		required_material: ["Salmon"],
		required_material_info: "<<icon \"fishing/fish/Salmon.png\">>三文鱼(1)",
		required_crafting_station: "Work_Bench",
		required_crafting_station_info: "<<icon \"furniture_item/Work_Bench.png\">>工作台/<<birdicon 'tools'>>鹰塔工具箱",
		craftable: "<<set _craftable to $Salmon gt 0 ? true : false>>",
		craft: "<<set $Salmon -= 1>><<set $Sashimi += 1>>",
		crafting_info: "你制作了1份<<icon \"food/Sashimi.png\">>生鱼片。<<if currentSkillValue('housekeeping') lt 600>><<ghousekeeping 600>><</if>><br>你有<<icon \"food/Sashimi.png\">>生鱼片($Sashimi)，你还有<<icon \"fishing/fish/Salmon.png\">>三文鱼($Salmon)。",
	},
	"Sashimi_Bass": {
		name: "Sashimi",
        cn_name: "生鱼片<br><i>材料</i>",
		des: "- 饥饿值<br><i>“是生的！异国风味！”</i>",
        type: "food",
        amount: V.Sashimi || 0,
        icon: "food/Sashimi.png",
		required_material: ["Bass"],
		required_material_info: "<<icon \"fishing/fish/Bass.png\">>鲈鱼(1)",
		required_crafting_station: "Work_Bench",
		required_crafting_station_info: "<<icon \"furniture_item/Work_Bench.png\">>工作台/<<birdicon 'tools'>>鹰塔工具箱",
		craftable: "<<set _craftable to $Bass gt 0 ? true : false>>",
		craft: "<<set $Bass -= 1>><<set $Sashimi += 1>>",
		crafting_info: "你制作了1份<<icon \"food/Sashimi.png\">>生鱼片。<<if currentSkillValue('housekeeping') lt 600>><<ghousekeeping 600>><</if>><br>你有<<icon \"food/Sashimi.png\">>生鱼片($Sashimi)，你还有<<icon \"fishing/fish/Bass.png\">>鲈鱼($Bass)。",
	},
	"Sashimi_Tuna": {
		name: "Sashimi",
        cn_name: "生鱼片<br><i>材料</i>",
		des: "- 饥饿值<br><i>“是生的！异国风味！”</i>",
        type: "food",
        amount: V.Sashimi || 0,
        icon: "food/Sashimi.png",
		required_material: ["Tuna"],
		required_material_info: "<<icon \"fishing/fish/Tuna.png\">>金枪鱼(1)",
		required_crafting_station: "Work_Bench",
		required_crafting_station_info: "<<icon \"furniture_item/Work_Bench.png\">>工作台/<<birdicon 'tools'>>鹰塔工具箱",
		craftable: "<<set _craftable to $Tuna gt 0 ? true : false>>",
		craft: "<<set $Tuna -= 1>><<set $Sashimi += 1>>",
		crafting_info: "你制作了1份<<icon \"food/Sashimi.png\">>生鱼片。<<if currentSkillValue('housekeeping') lt 600>><<ghousekeeping 600>><</if>><br>你有<<icon \"food/Sashimi.png\">>生鱼片($Sashimi)，你还有<<icon \"fishing/fish/Tuna.png\">>金枪鱼($Tuna)。",
	},
	"Sashimi_Red_Snapper": {
		name: "Sashimi",
        cn_name: "生鱼片<br><i>材料</i>",
		des: "- 饥饿值<br><i>“是生的！异国风味！”</i>",
        type: "food",
        amount: V.Sashimi || 0,
        icon: "food/Sashimi.png",
		required_material: ["Red_Snapper"],
		required_material_info: "<<icon \"fishing/fish/Red_Snapper.png\">>红鲷鱼(1)",
		required_crafting_station: "Work_Bench",
		required_crafting_station_info: "<<icon \"furniture_item/Work_Bench.png\">>工作台/<<birdicon 'tools'>>鹰塔工具箱",
		craftable: "<<set _craftable to $Red_Snapper gt 0 ? true : false>>",
		craft: "<<set $Red_Snapper -= 1>><<set $Sashimi += 1>>",
		crafting_info: "你制作了1份<<icon \"food/Sashimi.png\">>生鱼片。<<if currentSkillValue('housekeeping') lt 600>><<ghousekeeping 600>><</if>><br>你有<<icon \"food/Sashimi.png\">>生鱼片($Sashimi)，你还有<<icon \"fishing/fish/Red_Snapper.png\">>红鲷鱼($Red_Snapper)。",
	},
	"Sashimi_Trout": {
		name: "Sashimi",
        cn_name: "生鱼片<br><i>材料</i>",
		des: "- 饥饿值<br><i>“是生的！异国风味！”</i>",
        type: "food",
        amount: V.Sashimi || 0,
        icon: "food/Sashimi.png",
		required_material: ["Trout"],
		required_material_info: "<<icon \"fishing/fish/Trout.png\">>鳟鱼(1)",
		required_crafting_station: "Work_Bench",
		required_crafting_station_info: "<<icon \"furniture_item/Work_Bench.png\">>工作台/<<birdicon 'tools'>>鹰塔工具箱",
		craftable: "<<set _craftable to $Trout gt 0 ? true : false>>",
		craft: "<<set $Trout -= 1>><<set $Sashimi += 1>>",
		crafting_info: "你制作了1份<<icon \"food/Sashimi.png\">>生鱼片。<<if currentSkillValue('housekeeping') lt 600>><<ghousekeeping 600>><</if>><br>你有<<icon \"food/Sashimi.png\">>生鱼片($Sashimi)，你还有<<icon \"fishing/fish/Trout.png\">>鳟鱼($Trout)。",
	},
	"Sashimi_Flounder": {
		name: "Sashimi",
        cn_name: "生鱼片<br><i>材料</i>",
		des: "- 饥饿值<br><i>“是生的！异国风味！”</i>",
        type: "food",
        amount: V.Sashimi || 0,
        icon: "food/Sashimi.png",
		required_material: ["Flounder"],
		required_material_info: "<<icon \"fishing/fish/Flounder.png\">>偏口鱼(1)",
		required_crafting_station: "Work_Bench",
		required_crafting_station_info: "<<icon \"furniture_item/Work_Bench.png\">>工作台/<<birdicon 'tools'>>鹰塔工具箱",
		craftable: "<<set _craftable to $Flounder gt 0 ? true : false>>",
		craft: "<<set $Flounder -= 1>><<set $Sashimi += 1>>",
		crafting_info: "你制作了1份<<icon \"food/Sashimi.png\">>生鱼片。<<if currentSkillValue('housekeeping') lt 600>><<ghousekeeping 600>><</if>><br>你有<<icon \"food/Sashimi.png\">>生鱼片($Sashimi)，你还有<<icon \"fishing/fish/Flounder.png\">>偏口鱼($Flounder)。",
	},
	"Sashimi_Atlantic_Cod": {
		name: "Sashimi",
        cn_name: "生鱼片<br><i>材料</i>",
		des: "- 饥饿值<br><i>“是生的！异国风味！”</i>",
        type: "food",
        amount: V.Sashimi || 0,
        icon: "food/Sashimi.png",
		required_material: ["Atlantic_Cod"],
		required_material_info: "<<icon \"fishing/fish/Atlantic_Cod.png\">>大西洋鳕鱼(1)",
		required_crafting_station: "Work_Bench",
		required_crafting_station_info: "<<icon \"furniture_item/Work_Bench.png\">>工作台/<<birdicon 'tools'>>鹰塔工具箱",
		craftable: "<<set _craftable to $Atlantic_Cod gt 0 ? true : false>>",
		craft: "<<set $Atlantic_Cod -= 1>><<set $Sashimi += 1>>",
		crafting_info: "你制作了1份<<icon \"food/Sashimi.png\">>生鱼片。<<if currentSkillValue('housekeeping') lt 600>><<ghousekeeping 600>><</if>><br>你有<<icon \"food/Sashimi.png\">>生鱼片($Sashimi)，你还有<<icon \"fishing/fish/Atlantic_Cod.png\">>大西洋鳕鱼($Atlantic_Cod)。",
	},
	"Sashimi_Prismatic_Guppy": {
		name: "Sashimi",
        cn_name: "生鱼片<br><i>材料</i>",
		des: "- 饥饿值<br><i>“是生的！异国风味！”</i>",
        type: "food",
        amount: V.Sashimi || 0,
        icon: "food/Sashimi.png",
		required_material: ["Prismatic_Guppy"],
		required_material_info: "<<icon \"fishing/fish/Prismatic_Guppy.png\">>棱晶孔雀鱼(1)",
		required_crafting_station: "Work_Bench",
		required_crafting_station_info: "<<icon \"furniture_item/Work_Bench.png\">>工作台/<<birdicon 'tools'>>鹰塔工具箱",
		craftable: "<<set _craftable to $Prismatic_Guppy gt 0 ? true : false>>",
		craft: "<<set $Prismatic_Guppy -= 1>><<set $Sashimi += 1>>",
		crafting_info: "你制作了1份<<icon \"food/Sashimi.png\">>生鱼片。<<if currentSkillValue('housekeeping') lt 600>><<ghousekeeping 600>><</if>><br>你有<<icon \"food/Sashimi.png\">>生鱼片($Sashimi)，你还有<<icon \"fishing/fish/Prismatic_Guppy.png\">>棱晶孔雀鱼($Prismatic_Guppy)。",
	},
	"Sashimi_Crag_Bullhead": {
		name: "Sashimi",
        cn_name: "生鱼片<br><i>材料</i>",
		des: "- 饥饿值<br><i>“是生的！异国风味！”</i>",
        type: "food",
        amount: V.Sashimi || 0,
        icon: "food/Sashimi.png",
		required_material: ["Crag_Bullhead"],
		required_material_info: "<<icon \"fishing/fish/Crag_Bullhead.png\">>硫火崖回鱼(1)",
		required_crafting_station: "Work_Bench",
		required_crafting_station_info: "<<icon \"furniture_item/Work_Bench.png\">>工作台/<<birdicon 'tools'>>鹰塔工具箱",
		craftable: "<<set _craftable to $Crag_Bullhead gt 0 ? true : false>>",
		craft: "<<set $Crag_Bullhead -= 1>><<set $Sashimi += 1>>",
		crafting_info: "你制作了1份<<icon \"food/Sashimi.png\">>生鱼片。<<if currentSkillValue('housekeeping') lt 600>><<ghousekeeping 600>><</if>><br>你有<<icon \"food/Sashimi.png\">>生鱼片($Sashimi)，你还有<<icon \"fishing/fish/Crag_Bullhead.png\">>硫火崖回鱼($Crag_Bullhead)。",
	},
	//熟鱼：可由 三文鱼、鲈鱼、金枪鱼、红鲷鱼、鳟鱼、偏口鱼、大西洋鳕鱼、棱晶孔雀鱼、硫火崖回鱼 在 烹饪锅 上制作得到
	"Cooked_Fish_Salmon": {
		name: "Cooked_Fish",
        cn_name: "熟鱼",
		des: "- - 饥饿值<br><i>“薯条在哪里！？”</i>",
        type: "food",
        amount: V.Cooked_Fish || 0,
        icon: "food/Cooked_Fish.png",
		required_material: ["Salmon"],
		required_material_info: "<<icon \"fishing/fish/Salmon.png\">>三文鱼(1)",
		required_crafting_station: "Cooking_Pot",
		required_crafting_station_info: "<<icon \"furniture_item/Cooking_Pot.png\">>烹饪锅/<<birdicon 'pot_cook'>>鹰塔烹饪锅",
		craftable: "<<set _craftable to $Salmon gt 0 ? true : false>>",
		craft: "<<set $Salmon -= 1>><<set $Cooked_Fish += 1>>",
		crafting_info: "你制作了1份<<icon \"food/Cooked_Fish.png\">>熟鱼。<<if currentSkillValue('housekeeping') lt 1000>><<ghousekeeping 1000>><</if>><br>你有<<icon \"food/Cooked_Fish.png\">>熟鱼($Cooked_Fish)，你还有<<icon \"fishing/fish/Salmon.png\">>三文鱼($Salmon)。",
	},
	"Cooked_Fish_Bass": {
		name: "Cooked_Fish",
        cn_name: "熟鱼",
		des: "- - 饥饿值<br><i>“薯条在哪里！？”</i>",
        type: "food",
        amount: V.Cooked_Fish || 0,
        icon: "food/Cooked_Fish.png",
		required_material: ["Bass"],
		required_material_info: "<<icon \"fishing/fish/Bass.png\">>鲈鱼(1)",
		required_crafting_station: "Cooking_Pot",
		required_crafting_station_info: "<<icon \"furniture_item/Cooking_Pot.png\">>烹饪锅/<<birdicon 'pot_cook'>>鹰塔烹饪锅",
		craftable: "<<set _craftable to $Bass gt 0 ? true : false>>",
		craft: "<<set $Bass -= 1>><<set $Cooked_Fish += 1>>",
		crafting_info: "你制作了1份<<icon \"food/Cooked_Fish.png\">>熟鱼。<<if currentSkillValue('housekeeping') lt 1000>><<ghousekeeping 1000>><</if>><br>你有<<icon \"food/Cooked_Fish.png\">>熟鱼($Cooked_Fish)，你还有<<icon \"fishing/fish/Bass.png\">>鲈鱼($Bass)。",
	},
	"Cooked_Fish_Tuna": {
		name: "Cooked_Fish",
        cn_name: "熟鱼",
		des: "- - 饥饿值<br><i>“薯条在哪里！？”</i>",
        type: "food",
        amount: V.Cooked_Fish || 0,
        icon: "food/Cooked_Fish.png",
		required_material: ["Tuna"],
		required_material_info: "<<icon \"fishing/fish/Tuna.png\">>金枪鱼(1)",
		required_crafting_station: "Cooking_Pot",
		required_crafting_station_info: "<<icon \"furniture_item/Cooking_Pot.png\">>烹饪锅/<<birdicon 'pot_cook'>>鹰塔烹饪锅",
		craftable: "<<set _craftable to $Tuna gt 0 ? true : false>>",
		craft: "<<set $Tuna -= 1>><<set $Cooked_Fish += 1>>",
		crafting_info: "你制作了1份<<icon \"food/Cooked_Fish.png\">>熟鱼。<<if currentSkillValue('housekeeping') lt 1000>><<ghousekeeping 1000>><</if>><br>你有<<icon \"food/Cooked_Fish.png\">>熟鱼($Cooked_Fish)，你还有<<icon \"fishing/fish/Tuna.png\">>金枪鱼($Tuna)。",
	},
	"Cooked_Fish_Red_Snapper": {
		name: "Cooked_Fish",
        cn_name: "熟鱼",
		des: "- - 饥饿值<br><i>“薯条在哪里！？”</i>",
        type: "food",
        amount: V.Cooked_Fish || 0,
        icon: "food/Cooked_Fish.png",
		required_material: ["Red_Snapper"],
		required_material_info: "<<icon \"fishing/fish/Red_Snapper.png\">>红鲷鱼(1)",
		required_crafting_station: "Cooking_Pot",
		required_crafting_station_info: "<<icon \"furniture_item/Cooking_Pot.png\">>烹饪锅/<<birdicon 'pot_cook'>>鹰塔烹饪锅",
		craftable: "<<set _craftable to $Red_Snapper gt 0 ? true : false>>",
		craft: "<<set $Red_Snapper -= 1>><<set $Cooked_Fish += 1>>",
		crafting_info: "你制作了1份<<icon \"food/Cooked_Fish.png\">>熟鱼。<<if currentSkillValue('housekeeping') lt 1000>><<ghousekeeping 1000>><</if>><br>你有<<icon \"food/Cooked_Fish.png\">>熟鱼($Cooked_Fish)，你还有<<icon \"fishing/fish/Red_Snapper.png\">>红鲷鱼($Red_Snapper)。",
	},
	"Cooked_Fish_Trout": {
		name: "Cooked_Fish",
        cn_name: "熟鱼",
		des: "- - 饥饿值<br><i>“薯条在哪里！？”</i>",
        type: "food",
        amount: V.Cooked_Fish || 0,
        icon: "food/Cooked_Fish.png",
		required_material: ["Trout"],
		required_material_info: "<<icon \"fishing/fish/Trout.png\">>鳟鱼(1)",
		required_crafting_station: "Cooking_Pot",
		required_crafting_station_info: "<<icon \"furniture_item/Cooking_Pot.png\">>烹饪锅/<<birdicon 'pot_cook'>>鹰塔烹饪锅",
		craftable: "<<set _craftable to $Trout gt 0 ? true : false>>",
		craft: "<<set $Trout -= 1>><<set $Cooked_Fish += 1>>",
		crafting_info: "你制作了1份<<icon \"food/Cooked_Fish.png\">>熟鱼。<<if currentSkillValue('housekeeping') lt 1000>><<ghousekeeping 1000>><</if>><br>你有<<icon \"food/Cooked_Fish.png\">>熟鱼($Cooked_Fish)，你还有<<icon \"fishing/fish/Trout.png\">>鳟鱼($Trout)。",
	},
	"Cooked_Fish_Flounder": {
		name: "Cooked_Fish",
        cn_name: "熟鱼",
		des: "- - 饥饿值<br><i>“薯条在哪里！？”</i>",
        type: "food",
        amount: V.Cooked_Fish || 0,
        icon: "food/Cooked_Fish.png",
		required_material: ["Flounder"],
		required_material_info: "<<icon \"fishing/fish/Flounder.png\">>偏口鱼(1)",
		required_crafting_station: "Cooking_Pot",
		required_crafting_station_info: "<<icon \"furniture_item/Cooking_Pot.png\">>烹饪锅/<<birdicon 'pot_cook'>>鹰塔烹饪锅",
		craftable: "<<set _craftable to $Flounder gt 0 ? true : false>>",
		craft: "<<set $Flounder -= 1>><<set $Cooked_Fish += 1>>",
		crafting_info: "你制作了1份<<icon \"food/Cooked_Fish.png\">>熟鱼。<<if currentSkillValue('housekeeping') lt 1000>><<ghousekeeping 1000>><</if>><br>你有<<icon \"food/Cooked_Fish.png\">>熟鱼($Cooked_Fish)，你还有<<icon \"fishing/fish/Flounder.png\">>偏口鱼($Flounder)。",
	},
	"Cooked_Fish_Atlantic_Cod": {
		name: "Cooked_Fish",
        cn_name: "熟鱼",
		des: "- - 饥饿值<br><i>“薯条在哪里！？”</i>",
        type: "food",
        amount: V.Cooked_Fish || 0,
        icon: "food/Cooked_Fish.png",
		required_material: ["Atlantic_Cod"],
		required_material_info: "<<icon \"fishing/fish/Atlantic_Cod.png\">>大西洋鳕鱼(1)",
		required_crafting_station: "Cooking_Pot",
		required_crafting_station_info: "<<icon \"furniture_item/Cooking_Pot.png\">>烹饪锅/<<birdicon 'pot_cook'>>鹰塔烹饪锅",
		craftable: "<<set _craftable to $Atlantic_Cod gt 0 ? true : false>>",
		craft: "<<set $Atlantic_Cod -= 1>><<set $Cooked_Fish += 1>>",
		crafting_info: "你制作了1份<<icon \"food/Cooked_Fish.png\">>熟鱼。<<if currentSkillValue('housekeeping') lt 1000>><<ghousekeeping 1000>><</if>><br>你有<<icon \"food/Cooked_Fish.png\">>熟鱼($Cooked_Fish)，你还有<<icon \"fishing/fish/Atlantic_Cod.png\">>大西洋鳕鱼($Atlantic_Cod)。",
	},
	"Cooked_Fish_Prismatic_Guppy": {
		name: "Cooked_Fish",
        cn_name: "熟鱼",
		des: "- - 饥饿值<br><i>“薯条在哪里！？”</i>",
        type: "food",
        amount: V.Cooked_Fish || 0,
        icon: "food/Cooked_Fish.png",
		required_material: ["Prismatic_Guppy"],
		required_material_info: "<<icon \"fishing/fish/Prismatic_Guppy.png\">>棱晶孔雀鱼(1)",
		required_crafting_station: "Cooking_Pot",
		required_crafting_station_info: "<<icon \"furniture_item/Cooking_Pot.png\">>烹饪锅/<<birdicon 'pot_cook'>>鹰塔烹饪锅",
		craftable: "<<set _craftable to $Prismatic_Guppy gt 0 ? true : false>>",
		craft: "<<set $Prismatic_Guppy -= 1>><<set $Cooked_Fish += 1>>",
		crafting_info: "你制作了1份<<icon \"food/Cooked_Fish.png\">>熟鱼。<<if currentSkillValue('housekeeping') lt 1000>><<ghousekeeping 1000>><</if>><br>你有<<icon \"food/Cooked_Fish.png\">>熟鱼($Cooked_Fish)，你还有<<icon \"fishing/fish/Prismatic_Guppy.png\">>棱晶孔雀鱼($Prismatic_Guppy)。",
	},
	"Cooked_Fish_Crag_Bullhead": {
		name: "Cooked_Fish",
        cn_name: "熟鱼",
		des: "- - 饥饿值<br><i>“薯条在哪里！？”</i>",
        type: "food",
        amount: V.Cooked_Fish || 0,
        icon: "food/Cooked_Fish.png",
		required_material: ["Crag_Bullhead"],
		required_material_info: "<<icon \"fishing/fish/Crag_Bullhead.png\">>硫火崖回鱼(1)",
		required_crafting_station: "Cooking_Pot",
		required_crafting_station_info: "<<icon \"furniture_item/Cooking_Pot.png\">>烹饪锅/<<birdicon 'pot_cook'>>鹰塔烹饪锅",
		craftable: "<<set _craftable to $Crag_Bullhead gt 0 ? true : false>>",
		craft: "<<set $Crag_Bullhead -= 1>><<set $Cooked_Fish += 1>>",
		crafting_info: "你制作了1份<<icon \"food/Cooked_Fish.png\">>熟鱼。<<if currentSkillValue('housekeeping') lt 1000>><<ghousekeeping 1000>><</if>><br>你有<<icon \"food/Cooked_Fish.png\">>熟鱼($Cooked_Fish)，你还有<<icon \"fishing/fish/Crag_Bullhead.png\">>硫火崖回鱼($Crag_Bullhead)。",
	},
	//熟虾：可由 虾 在 烹饪锅 上制作得到
	"Cooked_Shrimp": {
		name: "Cooked_Shrimp",
        cn_name: "熟虾",
		des: "- 饥饿值<br><i>“烧、煮、烤、烘……”</i>",
        type: "food",
        amount: V.Cooked_Shrimp || 0,
        icon: "food/Cooked_Shrimp.png",
		required_material: ["Shrimp"],
		required_material_info: "<<icon \"fishing/fish/Shrimp.png\">>虾(1)",
		required_crafting_station: "Cooking_Pot",
		required_crafting_station_info: "<<icon \"furniture_item/Cooking_Pot.png\">>烹饪锅/<<birdicon 'pot_cook'>>鹰塔烹饪锅",
		craftable: "<<set _craftable to $Shrimp gt 0 ? true : false>>",
		craft: "<<set $Shrimp -= 1>><<set $Cooked_Shrimp += 1>>",
		crafting_info: "你制作了1份<<icon \"food/Cooked_Shrimp.png\">>熟虾。<<if currentSkillValue('housekeeping') lt 1000>><<ghousekeeping 1000>><</if>><br>你有<<icon \"food/Cooked_Shrimp.png\">>熟虾($Cooked_Shrimp)，你还有<<icon \"fishing/fish/Shrimp.png\">>虾($Shrimp)。",
	},
	//龙虾尾：可由 岩石龙虾 在 烹饪锅 上制作得到
	"Lobster_Tail": {
		name: "Lobster_Tail",
        cn_name: "龙虾尾",
		des: "- - 饥饿值<br><i>“加一点黄油就很美味了”</i>",
        type: "food",
        amount: V.Lobster_Tail || 0,
        icon: "food/Lobster_Tail.png",
		required_material: ["Rock_Lobster"],
		required_material_info: "<<icon \"fishing/fish/Rock_Lobster.png\">>岩石龙虾(1)",
		required_crafting_station: "Cooking_Pot",
		required_crafting_station_info: "<<icon \"furniture_item/Cooking_Pot.png\">>烹饪锅/<<birdicon 'pot_cook'>>鹰塔烹饪锅",
		craftable: "<<set _craftable to $Rock_Lobster gt 0 ? true : false>>",
		craft: "<<set $Rock_Lobster -= 1>><<set $Lobster_Tail += 1>>",
		crafting_info: "你制作了1份<<icon \"food/Lobster_Tail.png\">>龙虾尾。<<if currentSkillValue('housekeeping') lt 1000>><<ghousekeeping 1000>><</if>><br>你有<<icon \"food/Lobster_Tail.png\">>龙虾尾($Lobster_Tail)，你还有<<icon \"fishing/fish/Rock_Lobster.png\">>岩石龙虾($Rock_Lobster)。",
	},
	//海鲜大餐：可由 臭味鱼、装甲洞穴鱼、镜面鱼、双鳍鳕鱼、斑驳油鱼、霓虹脂鲤、混沌鱼、七彩矿鱼、公主鱼、寒霜绦鱼、闪鳍锦鲤、黑曜石鱼、沉沦帆鱼、海岸恶魔鱼 在 烹饪锅 上制作得到
	"Seafood_Dinner_Stinkfish": {
		name: "Seafood_Dinner",
        cn_name: "海鲜大餐",
		des: "- - - 饥饿值<br><i>“我，海鲜，吃掉。”</i>",
        type: "food",
        amount: V.Seafood_Dinner || 0,
        icon: "food/Seafood_Dinner.png",
		required_material: ["Stinkfish"],
		required_material_info: "<<icon \"fishing/fish/Stinkfish.png\">>臭味鱼(2)",
		required_crafting_station: "Cooking_Pot",
		required_crafting_station_info: "<<icon \"furniture_item/Cooking_Pot.png\">>烹饪锅/<<birdicon 'pot_cook'>>鹰塔烹饪锅",
		craftable: "<<set _craftable to $Stinkfish gte 2 ? true : false>>",
		craft: "<<set $Stinkfish -= 2>><<set $Seafood_Dinner += 1>>",
		crafting_info: "你制作了1份<<icon \"food/Seafood_Dinner.png\">>海鲜大餐。<<if currentSkillValue('housekeeping') lt 1000>><<ghousekeeping 1000>><</if>><br>你有<<icon \"food/Seafood_Dinner.png\">>海鲜大餐($Seafood_Dinner)，你还有<<icon \"fishing/fish/Stinkfish.png\">>臭味鱼($Stinkfish)。",
	},
	"Seafood_Dinner_Armored_Cavefish": {
		name: "Seafood_Dinner",
        cn_name: "海鲜大餐",
		des: "- - - 饥饿值<br><i>“我，海鲜，吃掉。”</i>",
        type: "food",
        amount: V.Seafood_Dinner || 0,
        icon: "food/Seafood_Dinner.png",
		required_material: ["Armored_Cavefish"],
		required_material_info: "<<icon \"fishing/fish/Armored_Cavefish.png\">>装甲洞穴鱼(2)",
		required_crafting_station: "Cooking_Pot",
		required_crafting_station_info: "<<icon \"furniture_item/Cooking_Pot.png\">>烹饪锅/<<birdicon 'pot_cook'>>鹰塔烹饪锅",
		craftable: "<<set _craftable to $Armored_Cavefish gte 2 ? true : false>>",
		craft: "<<set $Armored_Cavefish -= 2>><<set $Seafood_Dinner += 1>>",
		crafting_info: "你制作了1份<<icon \"food/Seafood_Dinner.png\">>海鲜大餐。<<if currentSkillValue('housekeeping') lt 1000>><<ghousekeeping 1000>><</if>><br>你有<<icon \"food/Seafood_Dinner.png\">>海鲜大餐($Seafood_Dinner)，你还有<<icon \"fishing/fish/Armored_Cavefish.png\">>装甲洞穴鱼($Armored_Cavefish)。",
	},
	"Seafood_Dinner_Specular_Fish": {
		name: "Seafood_Dinner",
        cn_name: "海鲜大餐",
		des: "- - - 饥饿值<br><i>“我，海鲜，吃掉。”</i>",
        type: "food",
        amount: V.Seafood_Dinner || 0,
        icon: "food/Seafood_Dinner.png",
		required_material: ["Specular_Fish"],
		required_material_info: "<<icon \"fishing/fish/Specular_Fish.png\">>镜面鱼(2)",
		required_crafting_station: "Cooking_Pot",
		required_crafting_station_info: "<<icon \"furniture_item/Cooking_Pot.png\">>烹饪锅/<<birdicon 'pot_cook'>>鹰塔烹饪锅",
		craftable: "<<set _craftable to $Specular_Fish gte 2 ? true : false>>",
		craft: "<<set $Specular_Fish -= 2>><<set $Seafood_Dinner += 1>>",
		crafting_info: "你制作了1份<<icon \"food/Seafood_Dinner.png\">>海鲜大餐。<<if currentSkillValue('housekeeping') lt 1000>><<ghousekeeping 1000>><</if>><br>你有<<icon \"food/Seafood_Dinner.png\">>海鲜大餐($Seafood_Dinner)，你还有<<icon \"fishing/fish/Specular_Fish.png\">>镜面鱼($Specular_Fish)。",
	},
	"Seafood_Dinner_Honeyfin": {
		name: "Seafood_Dinner",
        cn_name: "海鲜大餐",
		des: "- - - 饥饿值<br><i>“我，海鲜，吃掉。”</i>",
        type: "food",
        amount: V.Seafood_Dinner || 0,
        icon: "food/Seafood_Dinner.png",
		required_material: ["Honeyfin"],
		required_material_info: "<<icon \"fishing/fish/Honeyfin.png\">>蜂蜜鱼(2)",
		required_crafting_station: "Cooking_Pot",
		required_crafting_station_info: "<<icon \"furniture_item/Cooking_Pot.png\">>烹饪锅/<<birdicon 'pot_cook'>>鹰塔烹饪锅",
		craftable: "<<set _craftable to $Honeyfin gte 2 ? true : false>>",
		craft: "<<set $Honeyfin -= 2>><<set $Seafood_Dinner += 1>>",
		crafting_info: "你制作了1份<<icon \"food/Seafood_Dinner.png\">>海鲜大餐。<<if currentSkillValue('housekeeping') lt 1000>><<ghousekeeping 1000>><</if>><br>你有<<icon \"food/Seafood_Dinner.png\">>海鲜大餐($Seafood_Dinner)，你还有<<icon \"fishing/fish/Honeyfin.png\">>蜂蜜鱼($Honeyfin)。",
	},
	"Seafood_Dinner_Double_Cod": {
		name: "Seafood_Dinner",
        cn_name: "海鲜大餐",
		des: "- - - 饥饿值<br><i>“我，海鲜，吃掉。”</i>",
        type: "food",
        amount: V.Seafood_Dinner || 0,
        icon: "food/Seafood_Dinner.png",
		required_material: ["Double_Cod"],
		required_material_info: "<<icon \"fishing/fish/Double_Cod.png\">>双鳍鳕鱼(2)",
		required_crafting_station: "Cooking_Pot",
		required_crafting_station_info: "<<icon \"furniture_item/Cooking_Pot.png\">>烹饪锅/<<birdicon 'pot_cook'>>鹰塔烹饪锅",
		craftable: "<<set _craftable to $Double_Cod gte 2 ? true : false>>",
		craft: "<<set $Double_Cod -= 2>><<set $Seafood_Dinner += 1>>",
		crafting_info: "你制作了1份<<icon \"food/Seafood_Dinner.png\">>海鲜大餐。<<if currentSkillValue('housekeeping') lt 1000>><<ghousekeeping 1000>><</if>><br>你有<<icon \"food/Seafood_Dinner.png\">>海鲜大餐($Seafood_Dinner)，你还有<<icon \"fishing/fish/Double_Cod.png\">>双鳍鳕鱼($Double_Cod)。",
	},
	"Seafood_Dinner_Variegated_Lardfish": {
		name: "Seafood_Dinner",
        cn_name: "海鲜大餐",
		des: "- - - 饥饿值<br><i>“我，海鲜，吃掉。”</i>",
        type: "food",
        amount: V.Seafood_Dinner || 0,
        icon: "food/Seafood_Dinner.png",
		required_material: ["Variegated_Lardfish"],
		required_material_info: "<<icon \"fishing/fish/Variegated_Lardfish.png\">>斑驳油鱼(2)",
		required_crafting_station: "Cooking_Pot",
		required_crafting_station_info: "<<icon \"furniture_item/Cooking_Pot.png\">>烹饪锅/<<birdicon 'pot_cook'>>鹰塔烹饪锅",
		craftable: "<<set _craftable to $Variegated_Lardfish gte 2 ? true : false>>",
		craft: "<<set $Variegated_Lardfish -= 2>><<set $Seafood_Dinner += 1>>",
		crafting_info: "你制作了1份<<icon \"food/Seafood_Dinner.png\">>海鲜大餐。<<if currentSkillValue('housekeeping') lt 1000>><<ghousekeeping 1000>><</if>><br>你有<<icon \"food/Seafood_Dinner.png\">>海鲜大餐($Seafood_Dinner)，你还有<<icon \"fishing/fish/Variegated_Lardfish.png\">>斑驳油鱼($Variegated_Lardfish)。",
	},
	"Seafood_Dinner_Neon_Tetra": {
		name: "Seafood_Dinner",
        cn_name: "海鲜大餐",
		des: "- - - 饥饿值<br><i>“我，海鲜，吃掉。”</i>",
        type: "food",
        amount: V.Seafood_Dinner || 0,
        icon: "food/Seafood_Dinner.png",
		required_material: ["Neon_Tetra"],
		required_material_info: "<<icon \"fishing/fish/Neon_Tetra.png\">>霓虹脂鲤(2)",
		required_crafting_station: "Cooking_Pot",
		required_crafting_station_info: "<<icon \"furniture_item/Cooking_Pot.png\">>烹饪锅/<<birdicon 'pot_cook'>>鹰塔烹饪锅",
		craftable: "<<set _craftable to $Neon_Tetra gte 2 ? true : false>>",
		craft: "<<set $Neon_Tetra -= 2>><<set $Seafood_Dinner += 1>>",
		crafting_info: "你制作了1份<<icon \"food/Seafood_Dinner.png\">>海鲜大餐。<<if currentSkillValue('housekeeping') lt 1000>><<ghousekeeping 1000>><</if>><br>你有<<icon \"food/Seafood_Dinner.png\">>海鲜大餐($Seafood_Dinner)，你还有<<icon \"fishing/fish/Neon_Tetra.png\">>霓虹脂鲤($Neon_Tetra)。",
	},
	"Seafood_Dinner_Chaos_Fish": {
		name: "Seafood_Dinner",
        cn_name: "海鲜大餐",
		des: "- - - 饥饿值<br><i>“我，海鲜，吃掉。”</i>",
        type: "food",
        amount: V.Seafood_Dinner || 0,
        icon: "food/Seafood_Dinner.png",
		required_material: ["Chaos_Fish"],
		required_material_info: "<<icon \"fishing/fish/Chaos_Fish.png\">>混沌鱼(2)",
		required_crafting_station: "Cooking_Pot",
		required_crafting_station_info: "<<icon \"furniture_item/Cooking_Pot.png\">>烹饪锅/<<birdicon 'pot_cook'>>鹰塔烹饪锅",
		craftable: "<<set _craftable to $Chaos_Fish gte 2 ? true : false>>",
		craft: "<<set $Chaos_Fish -= 2>><<set $Seafood_Dinner += 1>>",
		crafting_info: "你制作了1份<<icon \"food/Seafood_Dinner.png\">>海鲜大餐。<<if currentSkillValue('housekeeping') lt 1000>><<ghousekeeping 1000>><</if>><br>你有<<icon \"food/Seafood_Dinner.png\">>海鲜大餐($Seafood_Dinner)，你还有<<icon \"fishing/fish/Chaos_Fish.png\">>混沌鱼($Chaos_Fish)。",
	},
	"Seafood_Dinner_Prismite": {
		name: "Seafood_Dinner",
        cn_name: "海鲜大餐",
		des: "- - - 饥饿值<br><i>“我，海鲜，吃掉。”</i>",
        type: "food",
        amount: V.Seafood_Dinner || 0,
        icon: "food/Seafood_Dinner.png",
		required_material: ["Prismite"],
		required_material_info: "<<icon \"fishing/fish/Prismite.png\">>七彩矿鱼(2)",
		required_crafting_station: "Cooking_Pot",
		required_crafting_station_info: "<<icon \"furniture_item/Cooking_Pot.png\">>烹饪锅/<<birdicon 'pot_cook'>>鹰塔烹饪锅",
		craftable: "<<set _craftable to $Prismite gte 2 ? true : false>>",
		craft: "<<set $Prismite -= 2>><<set $Seafood_Dinner += 1>>",
		crafting_info: "你制作了1份<<icon \"food/Seafood_Dinner.png\">>海鲜大餐。<<if currentSkillValue('housekeeping') lt 1000>><<ghousekeeping 1000>><</if>><br>你有<<icon \"food/Seafood_Dinner.png\">>海鲜大餐($Seafood_Dinner)，你还有<<icon \"fishing/fish/Prismite.png\">>七彩矿鱼($Prismite)。",
	},
	"Seafood_Dinner_Princess_Fish": {
		name: "Seafood_Dinner",
        cn_name: "海鲜大餐",
		des: "- - - 饥饿值<br><i>“我，海鲜，吃掉。”</i>",
        type: "food",
        amount: V.Seafood_Dinner || 0,
        icon: "food/Seafood_Dinner.png",
		required_material: ["Princess_Fish"],
		required_material_info: "<<icon \"fishing/fish/Princess_Fish.png\">>公主鱼(2)",
		required_crafting_station: "Cooking_Pot",
		required_crafting_station_info: "<<icon \"furniture_item/Cooking_Pot.png\">>烹饪锅/<<birdicon 'pot_cook'>>鹰塔烹饪锅",
		craftable: "<<set _craftable to $Princess_Fish gte 2 ? true : false>>",
		craft: "<<set $Princess_Fish -= 2>><<set $Seafood_Dinner += 1>>",
		crafting_info: "你制作了1份<<icon \"food/Seafood_Dinner.png\">>海鲜大餐。<<if currentSkillValue('housekeeping') lt 1000>><<ghousekeeping 1000>><</if>><br>你有<<icon \"food/Seafood_Dinner.png\">>海鲜大餐($Seafood_Dinner)，你还有<<icon \"fishing/fish/Princess_Fish.png\">>公主鱼($Princess_Fish)。",
	},
	"Seafood_Dinner_Frost_Minnow": {
		name: "Seafood_Dinner",
        cn_name: "海鲜大餐",
		des: "- - - 饥饿值<br><i>“我，海鲜，吃掉。”</i>",
        type: "food",
        amount: V.Seafood_Dinner || 0,
        icon: "food/Seafood_Dinner.png",
		required_material: ["Frost_Minnow"],
		required_material_info: "<<icon \"fishing/fish/Frost_Minnow.png\">>寒霜绦鱼(2)",
		required_crafting_station: "Cooking_Pot",
		required_crafting_station_info: "<<icon \"furniture_item/Cooking_Pot.png\">>烹饪锅/<<birdicon 'pot_cook'>>鹰塔烹饪锅",
		craftable: "<<set _craftable to $Frost_Minnow gte 2 ? true : false>>",
		craft: "<<set $Frost_Minnow -= 2>><<set $Seafood_Dinner += 1>>",
		crafting_info: "你制作了1份<<icon \"food/Seafood_Dinner.png\">>海鲜大餐。<<if currentSkillValue('housekeeping') lt 1000>><<ghousekeeping 1000>><</if>><br>你有<<icon \"food/Seafood_Dinner.png\">>海鲜大餐($Seafood_Dinner)，你还有<<icon \"fishing/fish/Frost_Minnow.png\">>寒霜绦鱼($Frost_Minnow)。",
	},
	"Seafood_Dinner_Flarefin_Koi": {
		name: "Seafood_Dinner",
        cn_name: "海鲜大餐",
		des: "- - - 饥饿值<br><i>“我，海鲜，吃掉。”</i>",
        type: "food",
        amount: V.Seafood_Dinner || 0,
        icon: "food/Seafood_Dinner.png",
		required_material: ["Flarefin_Koi"],
		required_material_info: "<<icon \"fishing/fish/Flarefin_Koi.png\">>闪鳍锦鲤(2)",
		required_crafting_station: "Cooking_Pot",
		required_crafting_station_info: "<<icon \"furniture_item/Cooking_Pot.png\">>烹饪锅/<<birdicon 'pot_cook'>>鹰塔烹饪锅",
		craftable: "<<set _craftable to $Flarefin_Koi gte 2 ? true : false>>",
		craft: "<<set $Flarefin_Koi -= 2>><<set $Seafood_Dinner += 1>>",
		crafting_info: "你制作了1份<<icon \"food/Seafood_Dinner.png\">>海鲜大餐。<<if currentSkillValue('housekeeping') lt 1000>><<ghousekeeping 1000>><</if>><br>你有<<icon \"food/Seafood_Dinner.png\">>海鲜大餐($Seafood_Dinner)，你还有<<icon \"fishing/fish/Flarefin_Koi.png\">>闪鳍锦鲤($Flarefin_Koi)。",
	},
	"Seafood_Dinner_Obsidifish": {
		name: "Seafood_Dinner",
        cn_name: "海鲜大餐",
		des: "- - - 饥饿值<br><i>“我，海鲜，吃掉。”</i>",
        type: "food",
        amount: V.Seafood_Dinner || 0,
        icon: "food/Seafood_Dinner.png",
		required_material: ["Obsidifish"],
		required_material_info: "<<icon \"fishing/fish/Obsidifish.png\">>黑曜石鱼(2)",
		required_crafting_station: "Cooking_Pot",
		required_crafting_station_info: "<<icon \"furniture_item/Cooking_Pot.png\">>烹饪锅/<<birdicon 'pot_cook'>>鹰塔烹饪锅",
		craftable: "<<set _craftable to $Obsidifish gte 2 ? true : false>>",
		craft: "<<set $Obsidifish -= 2>><<set $Seafood_Dinner += 1>>",
		crafting_info: "你制作了1份<<icon \"food/Seafood_Dinner.png\">>海鲜大餐。<<if currentSkillValue('housekeeping') lt 1000>><<ghousekeeping 1000>><</if>><br>你有<<icon \"food/Seafood_Dinner.png\">>海鲜大餐($Seafood_Dinner)，你还有<<icon \"fishing/fish/Obsidifish.png\">>黑曜石鱼($Obsidifish)。",
	},
	"Seafood_Dinner_Sunken_Sailfish": {
		name: "Seafood_Dinner",
        cn_name: "海鲜大餐",
		des: "- - - 饥饿值<br><i>“我，海鲜，吃掉。”</i>",
        type: "food",
        amount: V.Seafood_Dinner || 0,
        icon: "food/Seafood_Dinner.png",
		required_material: ["Sunken_Sailfish"],
		required_material_info: "<<icon \"fishing/fish/Sunken_Sailfish.png\">>沉沦帆鱼(2)",
		required_crafting_station: "Cooking_Pot",
		required_crafting_station_info: "<<icon \"furniture_item/Cooking_Pot.png\">>烹饪锅/<<birdicon 'pot_cook'>>鹰塔烹饪锅",
		craftable: "<<set _craftable to $Sunken_Sailfish gte 2 ? true : false>>",
		craft: "<<set $Sunken_Sailfish -= 2>><<set $Seafood_Dinner += 1>>",
		crafting_info: "你制作了1份<<icon \"food/Seafood_Dinner.png\">>海鲜大餐。<<if currentSkillValue('housekeeping') lt 1000>><<ghousekeeping 1000>><</if>><br>你有<<icon \"food/Seafood_Dinner.png\">>海鲜大餐($Seafood_Dinner)，你还有<<icon \"fishing/fish/Sunken_Sailfish.png\">>沉沦帆鱼($Sunken_Sailfish)。",
	},
	"Seafood_Dinner_Coastal_Demonfish": {
		name: "Seafood_Dinner",
        cn_name: "海鲜大餐",
		des: "- - - 饥饿值<br><i>“我，海鲜，吃掉。”</i>",
        type: "food",
        amount: V.Seafood_Dinner || 0,
        icon: "food/Seafood_Dinner.png",
		required_material: ["Coastal_Demonfish"],
		required_material_info: "<<icon \"fishing/fish/Coastal_Demonfish.png\">>海岸恶魔鱼(2)",
		required_crafting_station: "Cooking_Pot",
		required_crafting_station_info: "<<icon \"furniture_item/Cooking_Pot.png\">>烹饪锅/<<birdicon 'pot_cook'>>鹰塔烹饪锅",
		craftable: "<<set _craftable to $Coastal_Demonfish gte 2 ? true : false>>",
		craft: "<<set $Coastal_Demonfish -= 2>><<set $Seafood_Dinner += 1>>",
		crafting_info: "你制作了1份<<icon \"food/Seafood_Dinner.png\">>海鲜大餐。<<if currentSkillValue('housekeeping') lt 1000>><<ghousekeeping 1000>><</if>><br>你有<<icon \"food/Seafood_Dinner.png\">>海鲜大餐($Seafood_Dinner)，你还有<<icon \"fishing/fish/Coastal_Demonfish.png\">>海岸恶魔鱼($Coastal_Demonfish)。",
	},
	// 肥料：生鱼片(2)+学徒诱饵(10)/熟手诱饵(5)/大师诱饵(3) 在 工作台 上制作得到
	"fertiliser_Apprentice_Bait": {
		name: "fertiliser",
        cn_name: "肥料",
		des: "在镇里原本是价值连城的化工产品，从海外运输而来。使用后可以增长土地肥力。",
        type: "fertiliser",
        icon: "fertiliser.png",
		required_material: ["Sashimi","Apprentice_Bait"],
		required_material_info: "<<icon \"food/Sashimi.png\">>生鱼片(2)<br><<icon \"fishing/bait/Apprentice_Bait.png\">>学徒诱饵(10)",
		required_crafting_station: "Work_Bench",
		required_crafting_station_info: "<<icon \"furniture_item/Work_Bench.png\">>工作台",
		craftable: "<<set _craftable to ($Sashimi gte 2 and $Apprentice_Bait gte 10) ? true : false>>",
		craft: "<<set $Sashimi -= 2>><<set $Apprentice_Bait -= 10>><<set $fertiliser.current += 1>>",
		crafting_info: "你制作了1袋<<icon \"fertiliser.png\">>肥料。<br>你有<<icon \"fertiliser.png\">>肥料($fertiliser.current)，你还有<<icon \"food/Sashimi.png\">>生鱼片($Sashimi)和<<icon \"fishing/bait/Apprentice_Bait.png\">>学徒诱饵($Apprentice_Bait)。",
	},
	"fertiliser_Journeyman_Bait": {
		name: "fertiliser",
        cn_name: "肥料",
		des: "在镇里原本是价值连城的化工产品，从海外运输而来。使用后可以增长土地肥力。",
        type: "fertiliser",
        icon: "fertiliser.png",
		required_material: ["Sashimi","Journeyman_Bait"],
		required_material_info: "<<icon \"food/Sashimi.png\">>生鱼片(2)<br><<icon \"fishing/bait/Journeyman_Bait.png\">>熟手诱饵(5)",
		required_crafting_station: "Work_Bench",
		required_crafting_station_info: "<<icon \"furniture_item/Work_Bench.png\">>工作台",
		craftable: "<<set _craftable to ($Sashimi gte 2 and $Journeyman_Bait gte 5) ? true : false>>",
		craft: "<<set $Sashimi -= 2>><<set $Journeyman_Bait -= 5>><<set $fertiliser.current += 1>>",
		crafting_info: "你制作了1袋<<icon \"fertiliser.png\">>肥料。<br>你有<<icon \"fertiliser.png\">>肥料($fertiliser.current)，你还有<<icon \"food/Sashimi.png\">>生鱼片($Sashimi)和<<icon \"fishing/bait/Journeyman_Bait.png\">>熟手诱饵($Journeyman_Bait)。",
	},
	"fertiliser_Master_Bait": {
		name: "fertiliser",
        cn_name: "肥料",
		des: "在镇里原本是价值连城的化工产品，从海外运输而来。使用后可以增长土地肥力。",
        type: "fertiliser",
        icon: "fertiliser.png",
		required_material: ["Sashimi","Master_Bait"],
		required_material_info: "<<icon \"food/Sashimi.png\">>生鱼片(2)<br><<icon \"fishing/bait/Master_Bait.png\">>大师诱饵(3)",
		required_crafting_station: "Work_Bench",
		required_crafting_station_info: "<<icon \"furniture_item/Work_Bench.png\">>工作台",
		craftable: "<<set _craftable to ($Sashimi gte 2 and $Master_Bait gte 3) ? true : false>>",
		craft: "<<set $Sashimi -= 2>><<set $Master_Bait -= 3>><<set $fertiliser.current += 1>>",
		crafting_info: "你制作了1袋<<icon \"fertiliser.png\">>肥料。<br>你有<<icon \"fertiliser.png\">>肥料($fertiliser.current)，你还有<<icon \"food/Sashimi.png\">>生鱼片($Sashimi)和<<icon \"fishing/bait/Master_Bait.png\">>大师诱饵($Master_Bait)。",
	},
	//鱼饵
	"Enchanted_Nightcrawler": {
		name: "Enchanted_Nightcrawler",
        cn_name: "附魔夜行者",
		des: "35渔力",
        type: "bait",
        icon: "fishing/bait/Enchanted_Nightcrawler.png",
		required_material: ["Worm","Fallen_Star"],
		required_material_info: "<<icon \"fishing/bait/Worm.png\">>蠕虫(1)<br><<icon \"material/Fallen_Star.png\">>坠落之星(1)",
		required_crafting_station: "Work_Bench",
		required_crafting_station_info: "<<icon \"furniture_item/Work_Bench.png\">>工作台",
		craftable: "<<set _craftable to ($Worm gte 1 and $Fallen_Star gte 1) ? true : false>>",
		craft: "<<set $Worm -= 1>><<set $Fallen_Star -= 1>><<set $Enchanted_Nightcrawler += 1>><<bestiaryStatistics 'bait' 'Enchanted_Nightcrawler' 1>>",
		crafting_info: "你制作了1只<<icon \"fishing/bait/Enchanted_Nightcrawler.png\">>附魔夜行者。<br>你有<<icon \"fishing/bait/Enchanted_Nightcrawler.png\">>附魔夜行者($Enchanted_Nightcrawler)，你还有<<icon \"fishing/bait/Worm.png\">>蠕虫($Worm)和<<icon \"material/Fallen_Star.png\">>坠落之星($Fallen_Star)。",
	},
	// 原版的新食材
	"Cod": {
		name: "Cod",
		cn_name: "鳕鱼",
		des: "厨房食材",
		type: "kitchen",
		icon: "tending/cod.png",
		required_material: ["Atlantic_Cod"],
		required_material_info: "<<icon \"fishing/fish/Atlantic_Cod.png\">>大西洋鳕鱼(1)",
		required_crafting_station: "Work_Bench",
		required_crafting_station_info: "<<icon \"furniture_item/Work_Bench.png\">>工作台",
		craftable: "<<set _craftable to ($Atlantic_Cod gte 1) ? true : false>>",
		craft: "<<set $Atlantic_Cod -= 1>><<set $plants.cod.amount += 1>>",
		crafting_info: "你制作了1份<<icon \"tending/cod.png\">>鳕鱼。<br>你有<<icon \"tending/cod.png\">>鳕鱼($plants.cod.amount)，你还有<<icon \"fishing/fish/Atlantic_Cod.png\">>大西洋鳕鱼($Atlantic_Cod)。",
	},
	"Haddock": {
		name: "Haddock",
		cn_name: "黑线鳕鱼",
		des: "厨房食材",
		type: "kitchen",
		icon: "tending/haddock.png",
		required_material: ["Double_Cod"],
		required_material_info: "<<icon \"fishing/fish/Double_Cod.png\">>双鳍鳕鱼(1)",
		required_crafting_station: "Work_Bench",
		required_crafting_station_info: "<<icon \"furniture_item/Work_Bench.png\">>工作台",
		craftable: "<<set _craftable to ($Double_Cod gte 1) ? true : false>>",
		craft: "<<set $Double_Cod -= 1>><<set $plants.haddock.amount += 1>>",
		crafting_info: "你制作了1份<<icon \"tending/haddock.png\">>黑线鳕鱼。<br>你有<<icon \"tending/haddock.png\">>黑线鳕鱼($plants.haddock.amount)，你还有<<icon \"fishing/fish/Double_Cod.png\">>双鳍鳕鱼($Double_Cod)。",
	},
	"Prawn": {
		name: "Prawn",
		cn_name: "虾",
		des: "厨房食材",
		type: "kitchen",
		icon: "tending/prawn.png",
		required_material: ["Shrimp"],
		required_material_info: "<<icon \"fishing/fish/Shrimp.png\">>虾(1)",
		required_crafting_station: "Work_Bench",
		required_crafting_station_info: "<<icon \"furniture_item/Work_Bench.png\">>工作台",
		craftable: "<<set _craftable to ($Shrimp gte 1) ? true : false>>",
		craft: "<<set $Shrimp -= 1>><<set $plants.prawn.amount += 1>>",
		crafting_info: "你制作了1份<<icon \"tending/prawn.png\">>虾。<br>你有<<icon \"tending/prawn.png\">>虾($plants.prawn.amount)，你还有<<icon \"fishing/fish/Shrimp.png\">>虾($Shrimp)。",
	},
	"Salmon": {
		name: "Salmon",
		cn_name: "鲑鱼",
		des: "厨房食材",
		type: "kitchen",
		icon: "tending/salmon.png",
		required_material: ["Salmon"],
		required_material_info: "<<icon \"fishing/fish/Salmon.png\">>三文鱼(1)",
		required_crafting_station: "Work_Bench",
		required_crafting_station_info: "<<icon \"furniture_item/Work_Bench.png\">>工作台",
		craftable: "<<set _craftable to ($Salmon gte 1) ? true : false>>",
		craft: "<<set $Salmon -= 1>><<set $plants.salmon.amount += 1>>",
		crafting_info: "你制作了1份<<icon \"tending/salmon.png\">>鲑鱼。<br>你有<<icon \"tending/salmon.png\">>鲑鱼($plants.salmon.amount)，你还有<<icon \"fishing/fish/Salmon.png\">>三文鱼($Salmon)。",
	},
	"Trout": {
		name: "Trout",
		cn_name: "鳟鱼",
		des: "厨房食材",
		type: "kitchen",
		icon: "tending/trout.png",
		required_material: ["Trout"],
		required_material_info: "<<icon \"fishing/fish/Trout.png\">>鳟鱼(1)",
		required_crafting_station: "Work_Bench",
		required_crafting_station_info: "<<icon \"furniture_item/Work_Bench.png\">>工作台",
		craftable: "<<set _craftable to ($Trout gte 1) ? true : false>>",
		craft: "<<set $Trout -= 1>><<set $plants.trout.amount += 1>>",
		crafting_info: "你制作了1份<<icon \"tending/trout.png\">>鳟鱼。<br>你有<<icon \"tending/trout.png\">>鳟鱼($plants.trout.amount)，你还有<<icon \"fishing/fish/Trout.png\">>鳟鱼($Trout)。",
	},
	"Honey_Honeyfin": {
		name: "Honey",
		cn_name: "蜂蜜",
		des: "厨房食材，香甜可口",
		type: "kitchen",
		icon: "tending/honey.png",
		required_material: ["Honeyfin"],
		required_material_info: "<<icon \"fishing/fish/Honeyfin.png\">>蜂蜜鱼(1)",
		required_crafting_station: "Work_Bench",
		required_crafting_station_info: "<<icon \"furniture_item/Work_Bench.png\">>工作台",
		craftable: "<<set _craftable to ($Honeyfin gte 1) ? true : false>>",
		craft: "<<set $Honeyfin -= 1>><<set $plants.honey.amount += 400>>",
		crafting_info: "你制作了400份<<icon \"tending/honey.png\">>蜂蜜。<br>你有<<icon \"tending/honey.png\">>蜂蜜($plants.honey.amount)，你还有<<icon \"fishing/fish/Honeyfin.png\">>蜂蜜鱼($Honeyfin)。",
	},
	"Honey_Bottomless_Honey_Bucket": {
		name: "Honey",
		cn_name: "蜂蜜",
		des: "厨房食材，香甜可口",
		type: "kitchen",
		icon: "tending/honey.png",
		required_material: ["Bottomless_Honey_Bucket"],
		required_material_info: "<<icon \"tool/Bottomless_Honey_Bucket.png\">>无底蜂蜜桶(不消耗)",
		required_crafting_station: "Work_Bench",
		required_crafting_station_info: "<<icon \"furniture_item/Work_Bench.png\">>工作台",
		craftable: "<<set _craftable to $Bottomless_Honey_Bucket ? true : false>>",
		craft: "<<set $plants.honey.amount += 100>>",
		crafting_info: "你制作了100份<<icon \"tending/honey.png\">>蜂蜜。",
	},
}

function getAllRecipeList() {
    let all_recipe_list = Object.keys(setup.terraRecipe);
	return all_recipe_list;
}
window.getAllRecipeList = getAllRecipeList;