/*
	name: 产物代号/英文名
	cn_name: 产物中文名
	des: 产物的信息描述
	type: 产物的种类(饰品/工具/食物等等)
	icon: 产物图标
	crafting_station: 需求的制作站
	condition: 制作物品的前置要求
	ingredients: 合成所消耗的材料
	craft: 获得产物
	crafting_info: 合成物品后，显示合成的物品为何，持有的产物数量以及剩余的原料数量
*/
setup.terraRecipe = {
	//饰品和工具
	"Enchanted_Pearl": {
        name: "Enchanted_Pearl",
        cn_name: "附魔珍珠",
		des: "增加渔力，并增加钓到宝匣的几率",
        type: "accessories",
        icon: "fishing/fishing_accessories/Enchanted_Pearl.png",
		crafting_station: ["Iron_Anvil"],
		condition: () => !V.Enchanted_Pearl,
		ingredients: {
			White_Pearl: 1,
			Sea_Prism: 10,
			Sea_Remains: 3,
		},
		ingredients_info: "<<icon \"material/White_Pearl.png\">>白珍珠(1)<br><<icon \"material/Sea_Prism.png\">>海棱晶(10)<br><<icon \"material/Sea_Remains.png\">>海洋残渣(3)",
		craft: "<<set $Enchanted_Pearl to true>>",
		crafting_info: "你制作了1个<<icon \"fishing/fishing_accessories/Enchanted_Pearl.png\">>附魔珍珠。",
    },
	"Demon_Conch": {
        name: "Demon_Conch",
        cn_name: "恶魔海螺",
		des: "使用后将你传送至地下熔岩湖",
        type: "tool",
        icon: "tool/Demon_Conch.png",
		crafting_station: ["Hellforge"],
		condition: () => !V.Demon_Conch && !V.Shellphone,
		ingredients: {
			Magic_Conch: true,
			Demonic_Bone_Ash: 5,
		},
		ingredients_info: "<<icon \"tool/Magic_Conch.png\">>魔法海螺<br><<icon \"material/Demonic_Bone_Ash.png\">>恶魔骨灰(5)",
		craft: "<<set $Demon_Conch to true>>",
		crafting_info: "你制作了1个<<icon \"tool/Demon_Conch.png\">>恶魔海螺。",
    },
	"Cell_Phone": {
        name: "Cell_Phone",
        cn_name: "手机",
		des: "显示所有信息，并结合了魔镜、冰雪镜的传送功能",
        type: "tool",
        icon: "tool/Cell_Phone.png",
		crafting_station: ["Tinkerers_Workshop"],
		condition: () => !V.Cell_Phone,
		ingredients: {
			PDA: true,
			Magic_Mirror: true,
			Ice_Mirror: true,
		},
		ingredients_info: "<<icon \"accessories/PDA.png\">>个人数字助手<br><<icon \"tool/Magic_Mirror.png\">>魔镜<br><<icon \"tool/Ice_Mirror.png\">>冰雪镜",
		craft: "<<set $Cell_Phone to true>>",
		crafting_info: "你制作了1个<<icon \"tool/Cell_Phone.png\">>手机。",
    },
	"Shellphone": {
        name: "Shellphone",
        cn_name: "贝壳电话",
		des: "显示所有信息，并结合了四种传送工具的传送功能",
        type: "tool",
        icon: "tool/Shellphone.png",
		crafting_station: ["Tinkerers_Workshop"],
		condition: () => !V.Shellphone,
		ingredients: {
			Cell_Phone: true,
			Magic_Conch: true,
			Demon_Conch: true,
		},
		ingredients_info: "<<icon \"tool/Cell_Phone.png\">>手机<br><<icon \"tool/Magic_Conch.png\">>魔法海螺<br><<icon \"tool/Demon_Conch.png\">>恶魔海螺",
		craft: "<<set $Shellphone to true>>",
		crafting_info: "你制作了1个<<icon \"tool/Shellphone.png\">>贝壳电话。",
    },
	"Lavaproof_Bug_Net": {
        name: "Lavaproof_Bug_Net",
        cn_name: "防熔岩虫网",
		des: "可以用来和罗宾在森林捕捉小动物，还可以在森林湖边、雷米庄园门口抓蜻蜓。也可以捕捉熔岩小动物！",
        type: "tool",
        icon: "tool/Lavaproof_Bug_Net.png",
		crafting_station: ["Hellforge"],
		condition: () => !V.Lavaproof_Bug_Net,
		ingredients: {
			Bug_Net: true,
			Demonic_Bone_Ash: 5,
		},
		ingredients_info: "<<icon \"tool/Bug_Net.png\">>虫网<br><<icon \"material/Demonic_Bone_Ash.png\">>恶魔骨灰(5)",
		craft: "<<set $Lavaproof_Bug_Net to true>>",
		crafting_info: "你制作了1个<<icon \"tool/Lavaproof_Bug_Net.png\">>防熔岩虫网。",
    },
	"Mana_Crystal": {
		name: "Mana_Crystal",
        cn_name: "魔力水晶",
		des: "用坠落之星的魔力汇聚而成，使用后可以对已有的催眠特质起到抵消作用，使随机一项催眠特质降级",
        type: "tool",
        icon: "tool/Mana_Crystal.png",
		crafting_station: ["Work_Bench"],
		condition: () => true,
		ingredients: {
			Fallen_Star: 5,
		},
		ingredients_info: "<<icon \"material/Fallen_Star.png\">>坠落之星(5)",
		craft: "<<set $Mana_Crystal += 1>>",
		crafting_info: "你制作了1个<<icon \"tool/Mana_Crystal.png\">>魔力水晶。<br>你有<<icon \"tool/Mana_Crystal.png\">>魔力水晶($Mana_Crystal)，你还有<<icon \"material/Fallen_Star.png\">>坠落之星($Fallen_Star)。",
	},
	"Iron_Anvil": {
        name: "Iron_Anvil",
        cn_name: "铁砧",
		des: "用于制作以金属锭为原料的物品",
        type: "furniture",
        icon: "furniture_item/Iron_Anvil.png",
		crafting_station: ["Work_Bench"],
		condition: () => !V.orphanage_loft_crafting_station.includes('Iron_Anvil') && currentSkillValue('housekeeping') >= 400,
		ingredients: {
			Iron_Bar: 5,
		},
		ingredients_info: "需要有C级家务技能<br><<icon \"material/Iron_Bar.png\">>铁锭(5)",
		craft: "<<set $orphanage_loft_crafting_station.pushUnique(\"Iron_Anvil\")>>",
		crafting_info: "你制作了1个<<icon \"furniture_item/Iron_Anvil.png\">>铁砧，将它放在了阁楼。",
    },
	"Cooking_Pot": {
        name: "Cooking_Pot",
        cn_name: "烹饪锅",
		des: "用于食物制作",
        type: "furniture",
        icon: "furniture_item/Cooking_Pot.png",
		crafting_station: ["Iron_Anvil"],
		condition: () => !V.orphanage_loft_crafting_station.includes('Cooking_Pot') && currentSkillValue('housekeeping') >= 600,
		ingredients: {
			Iron_Bar: 10,
		},
		ingredients_info: "需要有B级家务技能<br><<icon \"material/Iron_Bar.png\">>铁锭(10)",
		craft: "<<set $orphanage_loft_crafting_station.pushUnique(\"Cooking_Pot\")>>",
		crafting_info: "你制作了1个<<icon \"furniture_item/Cooking_Pot.png\">>烹饪锅，将它放在了阁楼。",
    },
	"Angler_Tackle_Bag": {
        name: "Angler_Tackle_Bag",
        cn_name: "渔夫渔具袋<br><i>材料</i>",
		des: "结合了其合成材料的效果：钓鱼线永远不会断，降低鱼饵消耗几率，渔力增加10",
        type: "accessories",
        icon: "fishing/fishing_accessories/Angler_Tackle_Bag.png",
		crafting_station: ["Tinkerers_Workshop"],
		condition: () => !V.Angler_Tackle_Bag,
		ingredients: {
			Angler_Earring: true,
			High_Test_Fishing_Line: true,
			Tackle_Box: true,
		},
		ingredients_info: "<<icon \"fishing/fishing_accessories/Angler_Earring.png\">>渔夫耳环<br><<icon \"fishing/fishing_accessories/High_Test_Fishing_Line.png\">>优质钓鱼线<br><<icon \"fishing/fishing_accessories/Tackle_Box.png\">>钓具箱",
		craft: "<<set $Angler_Tackle_Bag to true>>",
		crafting_info: "你制作了1个<<icon \"fishing/fishing_accessories/Angler_Tackle_Bag.png\">>渔夫渔具袋。",
    },
	"Lavaproof_Tackle_Bag": {
        name: "Lavaproof_Tackle_Bag",
        cn_name: "防熔岩渔具袋",
		des: "结合了其合成材料的效果：钓鱼线永远不会断，降低鱼饵消耗几率，渔力增加10，可在沸水/熔岩中钓鱼",
        type: "accessories",
        icon: "fishing/fishing_accessories/Lavaproof_Tackle_Bag.png",
		crafting_station: ["Tinkerers_Workshop"],
		condition: () => !V.Lavaproof_Tackle_Bag,
		ingredients: {
			Angler_Tackle_Bag: true,
			Lavaproof_Fishing_Hook: true,
		},
		ingredients_info: "<<icon \"fishing/fishing_accessories/Angler_Tackle_Bag.png\">>渔夫渔具袋<br><<icon \"fishing/fishing_accessories/Lavaproof_Fishing_Hook.png\">>防熔岩钓钩",
		craft: "<<set $Lavaproof_Tackle_Bag to true>>",
		crafting_info: "你制作了1个<<icon \"fishing/fishing_accessories/Lavaproof_Tackle_Bag.png\">>防熔岩渔具袋。",
    },
	"Supreme_Bait_Tackle_Box_Fishing_Station": {
        name: "Supreme_Bait_Tackle_Box_Fishing_Station",
        cn_name: "万能渔具包",
		des: "拥有防熔岩渔具袋的全部效果，在此基础上增加50点渔力，并使钓鱼/声呐/宝匣药水持续时间翻倍<br><i>\"水中鱼的噩梦，钓鱼者的最爱，泰拉人的希望，至尊渔具背包钓鱼台！\"</i>",
        type: "accessories",
        icon: "fishing/fishing_accessories/Supreme_Bait_Tackle_Box_Fishing_Station.png",
		crafting_station: ["Iron_Anvil"],
		condition: () => !V.Supreme_Bait_Tackle_Box_Fishing_Station,
		ingredients: {
			Lavaproof_Tackle_Bag: true,
			Pink_Pearl: 1,
			Master_Bait: 5,
			Fishing_Potion: 5,
			Sonar_Potion: 5,
			Crate_Potion: 5,
		},
		ingredients_info: "<<icon \"fishing/fishing_accessories/Lavaproof_Tackle_Bag.png\">>防熔岩渔具袋<br><<icon 'material/Pink_Pearl.png'>>粉珍珠(1)<br><<icon 'fishing/bait/Master_Bait.png'>>大师诱饵(5)<br><<icon 'potions/Fishing_Potion.png'>>钓鱼药水(5)<br><<icon 'potions/Sonar_Potion.png'>>声呐药水(5)<br><<icon 'potions/Crate_Potion.png'>>宝匣药水(5)",
		craft: "<<set $Supreme_Bait_Tackle_Box_Fishing_Station to true>>",
		crafting_info: "你制作了1个<<icon \"fishing/fishing_accessories/Supreme_Bait_Tackle_Box_Fishing_Station.png\">>万能渔具包。",
    },
	"Fish_Finder": {
        name: "Fish_Finder",
        cn_name: "探鱼器",
		des: "结合了其合成材料的效果：显示天气、月相和钓鱼信息",
        type: "accessories",
        icon: "fishing/fishing_accessories/Fish_Finder.png",
		crafting_station: ["Tinkerers_Workshop"],
		condition: () => !V.Fish_Finder,
		ingredients: {
			Fishermans_Pocket_Guide: true,
			Sextant: true,
			Weather_Radio: true,
		},
		ingredients_info: "<<icon \"fishing/fishing_accessories/Fishermans_Pocket_Guide.png\">>渔民袖珍宝典<br><<icon \"fishing/fishing_accessories/Sextant.png\">>六分仪<br><<icon \"fishing/fishing_accessories/Weather_Radio.png\">>天气收音机",
		craft: "<<set $Fish_Finder to true>>",
		crafting_info: "你制作了1个<<icon \"fishing/fishing_accessories/Fish_Finder.png\">>探鱼器。",
    },
	"GPS": {
        name: "GPS",
        cn_name: "全球定位系统",
		des: "结合了其合成材料的效果：闹钟提醒、位于特定区域时显示所处的具体位置。并在旧下水道、触手平原、老教堂墓地、码头时显示该区域的地图。",
        type: "accessories",
        icon: "accessories/GPS.png",
		crafting_station: ["Tinkerers_Workshop"],
		condition: () => !V.GPS,
		ingredients: {
			Gold_Watch: true,
			Compass: true,
			Depth_Meter: true,
		},
		ingredients_info: "<<icon 'accessories/Gold_Watch.png'>>金表<br><<icon 'accessories/Compass.png'>>罗盘<br><<icon 'accessories/Depth_Meter.png'>>深度计",
		craft: "<<set $GPS to true>>",
		crafting_info: "你制作了1个<<icon 'accessories/GPS.png'>>全球定位系统。",
    },
	"Goblin_Tech": {
        name: "Goblin_Tech",
        cn_name: "哥布林数据仪",
		des: "结合了其合成材料的效果：可查看当前温度、允许在合适时机消磨时间、与全球定位系统配合使用（在码头显示有价值的物品）。",
        type: "accessories",
        icon: "accessories/Goblin_Tech.png",
		crafting_station: ["Tinkerers_Workshop"],
		condition: () => !V.Goblin_Tech,
		ingredients: {
			Thermometer: true,
			Stopwatch: true,
			Metal_Detector: true,
		},
		ingredients_info: "<<icon 'accessories/Thermometer.png'>>温度计<br><<icon 'accessories/Stopwatch.png'>>秒表<br><<icon 'accessories/Metal_Detector.png'>>金属探测器",
		craft: "<<set $Goblin_Tech to true>>",
		crafting_info: "你制作了1个<<icon 'accessories/Goblin_Tech.png'>>哥布林数据仪。",
    },
	"R_E_K_3000": {
        name: "R_E_K_3000",
        cn_name: "R.E.K.3000",
		des: "结合了雷达、生命体分析机、战斗计数器的功能",
        type: "accessories",
        icon: "accessories/R_E_K_3000.png",
		crafting_station: ["Tinkerers_Workshop"],
		condition: () => !V.R_E_K_3000,
		ingredients: {
			Radar: true,
			Lifeform_Analyzer: true,
			Tally_Counter: true,
		},
		ingredients_info: "<<icon 'accessories/Radar.png'>>雷达<br><<icon 'accessories/Lifeform_Analyzer.png'>>生命体分析机<br><<icon 'accessories/Tally_Counter.png'>>战斗计数器",
		craft: "<<set $R_E_K_3000 to true>>",
		crafting_info: "你制作了1个<<icon 'accessories/R_E_K_3000.png'>>R.E.K.3000。",
    },
	"PDA": {
        name: "PDA",
        cn_name: "个人数字助手",
		des: "结合了所有信息饰品的功能",
        type: "accessories",
        icon: "accessories/PDA.png",
		crafting_station: ["Tinkerers_Workshop"],
		condition: () => !V.PDA,
		ingredients: {
			Fish_Finder: true,
			GPS: true,
			Goblin_Tech: true,
			R_E_K_3000: true,
		},
		ingredients_info: "<<icon 'fishing/fishing_accessories/Fish_Finder.png'>>探鱼器<br><<icon 'accessories/GPS.png'>>全球定位系统<br><<icon 'accessories/Goblin_Tech.png'>>哥布林数据仪<br><<icon 'accessories/R_E_K_3000.png'>>R.E.K.3000",
		craft: "<<set $PDA to true>>",
		crafting_info: "你制作了1个<<icon 'accessories/PDA.png'>>个人数字助手。",
    },
	"Glowing_Fishing_Bobber": {
        name: "Glowing_Fishing_Bobber",
        cn_name: "发光钓鱼浮标<br><i>材料</i>",
		des: "增加10点渔力。<i>时装：</i>你的浮标现在会发光",
        type: "accessories",
        icon: "fishing/fishing_accessories/Glowing_Fishing_Bobber.png",
		crafting_station: ["Tinkerers_Workshop"],
		condition: () => !V.Glowing_Fishing_Bobber,
		ingredients: {
			Fishing_Bobber: true,
			Fallen_Star: 5,
		},
		ingredients_info: "<<icon \"fishing/fishing_accessories/Fishing_Bobber.png\">>钓鱼浮标<br><<icon \"material/Fallen_Star.png\">>坠落之星(5)",
		craft: "<<set $Glowing_Fishing_Bobber to true>>",
		crafting_info: "你制作了1个<<icon \"fishing/fishing_accessories/Glowing_Fishing_Bobber.png\">>发光钓鱼浮标。",
    },
	"Helium_Moss_Fishing_Bobber": {
        name: "Helium_Moss_Fishing_Bobber",
        cn_name: "氦苔藓钓鱼浮标",
		des: "增加10点渔力。<i>时装：</i>你的浮标现在会发光",
        type: "accessories",
        icon: "fishing/fishing_accessories/Helium_Moss_Fishing_Bobber.gif",
		crafting_station: ["Tinkerers_Workshop"],
		condition: () => !V.Helium_Moss_Fishing_Bobber,
		ingredients: {
			Glowing_Fishing_Bobber: true,
			Helium_Moss: 5,
		},
		ingredients_info: "<<icon \"fishing/fishing_accessories/Glowing_Fishing_Bobber.png\">>发光钓鱼浮标<br><<icon \"material/Helium_Moss.gif\">>氦苔藓(5)",
		craft: "<<set $Helium_Moss_Fishing_Bobber to true>>",
		crafting_info: "你制作了1个<<icon \"fishing/fishing_accessories/Helium_Moss_Fishing_Bobber.gif\">>氦苔藓钓鱼浮标。",
    },
	"Neon_Moss_Fishing_Bobber": {
        name: "Neon_Moss_Fishing_Bobber",
        cn_name: "氖苔藓钓鱼浮标",
		des: "增加10点渔力。<i>时装：</i>你的浮标现在会发光",
        type: "accessories",
        icon: "fishing/fishing_accessories/Neon_Moss_Fishing_Bobber.png",
		crafting_station: ["Tinkerers_Workshop"],
		condition: () => !V.Neon_Moss_Fishing_Bobber,
		ingredients: {
			Glowing_Fishing_Bobber: true,
			Neon_Moss: 5,
		},
		ingredients_info: "<<icon \"fishing/fishing_accessories/Glowing_Fishing_Bobber.png\">>发光钓鱼浮标<br><<icon \"material/Neon_Moss.png\">>氖苔藓(5)",
		craft: "<<set $Neon_Moss_Fishing_Bobber to true>>",
		crafting_info: "你制作了1个<<icon \"fishing/fishing_accessories/Neon_Moss_Fishing_Bobber.png\">>氖苔藓钓鱼浮标。",
    },
	"Argon_Moss_Fishing_Bobber": {
        name: "Argon_Moss_Fishing_Bobber",
        cn_name: "氩苔藓钓鱼浮标",
		des: "增加10点渔力。<i>时装：</i>你的浮标现在会发光",
        type: "accessories",
        icon: "fishing/fishing_accessories/Argon_Moss_Fishing_Bobber.png",
		crafting_station: ["Tinkerers_Workshop"],
		condition: () => !V.Argon_Moss_Fishing_Bobber,
		ingredients: {
			Glowing_Fishing_Bobber: true,
			Argon_Moss: 5,
		},
		ingredients_info: "<<icon \"fishing/fishing_accessories/Glowing_Fishing_Bobber.png\">>发光钓鱼浮标<br><<icon \"material/Argon_Moss.png\">>氩苔藓(5)",
		craft: "<<set $Argon_Moss_Fishing_Bobber to true>>",
		crafting_info: "你制作了1个<<icon \"fishing/fishing_accessories/Argon_Moss_Fishing_Bobber.png\">>氩苔藓钓鱼浮标。",
    },
	"Krypton_Moss_Fishing_Bobber": {
        name: "Krypton_Moss_Fishing_Bobber",
        cn_name: "氪苔藓钓鱼浮标",
		des: "增加10点渔力。<i>时装：</i>你的浮标现在会发光",
        type: "accessories",
        icon: "fishing/fishing_accessories/Krypton_Moss_Fishing_Bobber.png",
		crafting_station: ["Tinkerers_Workshop"],
		condition: () => !V.Krypton_Moss_Fishing_Bobber,
		ingredients: {
			Glowing_Fishing_Bobber: true,
			Krypton_Moss: 5,
		},
		ingredients_info: "<<icon \"fishing/fishing_accessories/Glowing_Fishing_Bobber.png\">>发光钓鱼浮标<br><<icon \"material/Krypton_Moss.png\">>氪苔藓(5)",
		craft: "<<set $Krypton_Moss_Fishing_Bobber to true>>",
		crafting_info: "你制作了1个<<icon \"fishing/fishing_accessories/Krypton_Moss_Fishing_Bobber.png\">>氪苔藓钓鱼浮标。",
    },
	"Xenon_Moss_Fishing_Bobber": {
        name: "Xenon_Moss_Fishing_Bobber",
        cn_name: "氙苔藓钓鱼浮标",
		des: "增加10点渔力。<i>时装：</i>你的浮标现在会发光",
        type: "accessories",
        icon: "fishing/fishing_accessories/Xenon_Moss_Fishing_Bobber.png",
		crafting_station: ["Tinkerers_Workshop"],
		condition: () => !V.Xenon_Moss_Fishing_Bobber,
		ingredients: {
			Glowing_Fishing_Bobber: true,
			Xenon_Moss: 5,
		},
		ingredients_info: "<<icon \"fishing/fishing_accessories/Glowing_Fishing_Bobber.png\">>发光钓鱼浮标<br><<icon \"material/Xenon_Moss.png\">>氙苔藓(5)",
		craft: "<<set $Xenon_Moss_Fishing_Bobber to true>>",
		crafting_info: "你制作了1个<<icon \"fishing/fishing_accessories/Xenon_Moss_Fishing_Bobber.png\">>氙苔藓钓鱼浮标。",
    },
	"Lava_Moss_Fishing_Bobber": {
        name: "Lava_Moss_Fishing_Bobber",
        cn_name: "熔岩苔藓钓鱼浮标",
		des: "增加10点渔力。<i>时装：</i>你的浮标现在会发光",
        type: "accessories",
        icon: "fishing/fishing_accessories/Lava_Moss_Fishing_Bobber.png",
		crafting_station: ["Tinkerers_Workshop"],
		condition: () => !V.Lava_Moss_Fishing_Bobber,
		ingredients: {
			Glowing_Fishing_Bobber: true,
			Lava_Moss: 5,
		},
		ingredients_info: "<<icon \"fishing/fishing_accessories/Glowing_Fishing_Bobber.png\">>发光钓鱼浮标<br><<icon \"material/Lava_Moss.png\">>熔岩苔藓(5)",
		craft: "<<set $Lava_Moss_Fishing_Bobber to true>>",
		crafting_info: "你制作了1个<<icon \"fishing/fishing_accessories/Lava_Moss_Fishing_Bobber.png\">>熔岩苔藓钓鱼浮标。",
    },
	//生鱼片：可由 三文鱼、鲈鱼、金枪鱼、红鲷鱼、鳟鱼、偏口鱼、大西洋鳕鱼、棱晶孔雀鱼、硫火崖回鱼 在 工作台 上制作得到
	"Sashimi_Salmon": {
		name: "Sashimi",
        cn_name: "生鱼片<br><i>材料</i>",
		des: "- 饥饿值<br><i>“是生的！异国风味！”</i>",
        type: "food",
        icon: "food/Sashimi.png",
		crafting_station: ["Work_Bench","birdToolBox"],
		condition: () => true,
		ingredients: {
			Salmon: 1,
		},
		ingredients_info: "<<icon \"fishing/fish/Salmon.png\">>三文鱼(1)",
		craft: "<<set $Sashimi += 1>>",
		crafting_info: "你制作了1份<<icon \"food/Sashimi.png\">>生鱼片。<<if currentSkillValue('housekeeping') lt 600>><<ghousekeeping 600>><</if>><br>你有<<icon \"food/Sashimi.png\">>生鱼片($Sashimi)，你还有<<icon \"fishing/fish/Salmon.png\">>三文鱼($Salmon)。",
	},
	"Sashimi_Bass": {
		name: "Sashimi",
        cn_name: "生鱼片<br><i>材料</i>",
		des: "- 饥饿值<br><i>“是生的！异国风味！”</i>",
        type: "food",
        icon: "food/Sashimi.png",
		crafting_station: ["Work_Bench","birdToolBox"],
		condition: () => true,
		ingredients: {
			Bass: 1,
		},
		ingredients_info: "<<icon \"fishing/fish/Bass.png\">>鲈鱼(1)",
		craft: "<<set $Sashimi += 1>>",
		crafting_info: "你制作了1份<<icon \"food/Sashimi.png\">>生鱼片。<<if currentSkillValue('housekeeping') lt 600>><<ghousekeeping 600>><</if>><br>你有<<icon \"food/Sashimi.png\">>生鱼片($Sashimi)，你还有<<icon \"fishing/fish/Bass.png\">>鲈鱼($Bass)。",
	},
	"Sashimi_Tuna": {
		name: "Sashimi",
        cn_name: "生鱼片<br><i>材料</i>",
		des: "- 饥饿值<br><i>“是生的！异国风味！”</i>",
        type: "food",
        icon: "food/Sashimi.png",
		crafting_station: ["Work_Bench","birdToolBox"],
		condition: () => true,
		ingredients: {
			Tuna: 1,
		},
		ingredients_info: "<<icon \"fishing/fish/Tuna.png\">>金枪鱼(1)",
		craft: "<<set $Sashimi += 1>>",
		crafting_info: "你制作了1份<<icon \"food/Sashimi.png\">>生鱼片。<<if currentSkillValue('housekeeping') lt 600>><<ghousekeeping 600>><</if>><br>你有<<icon \"food/Sashimi.png\">>生鱼片($Sashimi)，你还有<<icon \"fishing/fish/Tuna.png\">>金枪鱼($Tuna)。",
	},
	"Sashimi_Red_Snapper": {
		name: "Sashimi",
        cn_name: "生鱼片<br><i>材料</i>",
		des: "- 饥饿值<br><i>“是生的！异国风味！”</i>",
        type: "food",
        icon: "food/Sashimi.png",
		crafting_station: ["Work_Bench","birdToolBox"],
		condition: () => true,
		ingredients: {
			Red_Snapper: 1,
		},
		ingredients_info: "<<icon \"fishing/fish/Red_Snapper.png\">>红鲷鱼(1)",
		craft: "<<set $Sashimi += 1>>",
		crafting_info: "你制作了1份<<icon \"food/Sashimi.png\">>生鱼片。<<if currentSkillValue('housekeeping') lt 600>><<ghousekeeping 600>><</if>><br>你有<<icon \"food/Sashimi.png\">>生鱼片($Sashimi)，你还有<<icon \"fishing/fish/Red_Snapper.png\">>红鲷鱼($Red_Snapper)。",
	},
	"Sashimi_Trout": {
		name: "Sashimi",
        cn_name: "生鱼片<br><i>材料</i>",
		des: "- 饥饿值<br><i>“是生的！异国风味！”</i>",
        type: "food",
        icon: "food/Sashimi.png",
		crafting_station: ["Work_Bench","birdToolBox"],
		condition: () => true,
		ingredients: {
			Trout: 1,
		},
		ingredients_info: "<<icon \"fishing/fish/Trout.png\">>鳟鱼(1)",
		craft: "<<set $Sashimi += 1>>",
		crafting_info: "你制作了1份<<icon \"food/Sashimi.png\">>生鱼片。<<if currentSkillValue('housekeeping') lt 600>><<ghousekeeping 600>><</if>><br>你有<<icon \"food/Sashimi.png\">>生鱼片($Sashimi)，你还有<<icon \"fishing/fish/Trout.png\">>鳟鱼($Trout)。",
	},
	"Sashimi_Flounder": {
		name: "Sashimi",
        cn_name: "生鱼片<br><i>材料</i>",
		des: "- 饥饿值<br><i>“是生的！异国风味！”</i>",
        type: "food",
        icon: "food/Sashimi.png",
		crafting_station: ["Work_Bench","birdToolBox"],
		condition: () => true,
		ingredients: {
			Flounder: 1,
		},
		ingredients_info: "<<icon \"fishing/fish/Flounder.png\">>偏口鱼(1)",
		craft: "<<set $Sashimi += 1>>",
		crafting_info: "你制作了1份<<icon \"food/Sashimi.png\">>生鱼片。<<if currentSkillValue('housekeeping') lt 600>><<ghousekeeping 600>><</if>><br>你有<<icon \"food/Sashimi.png\">>生鱼片($Sashimi)，你还有<<icon \"fishing/fish/Flounder.png\">>偏口鱼($Flounder)。",
	},
	"Sashimi_Atlantic_Cod": {
		name: "Sashimi",
        cn_name: "生鱼片<br><i>材料</i>",
		des: "- 饥饿值<br><i>“是生的！异国风味！”</i>",
        type: "food",
        icon: "food/Sashimi.png",
		crafting_station: ["Work_Bench","birdToolBox"],
		condition: () => true,
		ingredients: {
			Atlantic_Cod: 1,
		},
		ingredients_info: "<<icon \"fishing/fish/Atlantic_Cod.png\">>大西洋鳕鱼(1)",
		craft: "<<set $Sashimi += 1>>",
		crafting_info: "你制作了1份<<icon \"food/Sashimi.png\">>生鱼片。<<if currentSkillValue('housekeeping') lt 600>><<ghousekeeping 600>><</if>><br>你有<<icon \"food/Sashimi.png\">>生鱼片($Sashimi)，你还有<<icon \"fishing/fish/Atlantic_Cod.png\">>大西洋鳕鱼($Atlantic_Cod)。",
	},
	"Sashimi_Prismatic_Guppy": {
		name: "Sashimi",
        cn_name: "生鱼片<br><i>材料</i>",
		des: "- 饥饿值<br><i>“是生的！异国风味！”</i>",
        type: "food",
        icon: "food/Sashimi.png",
		crafting_station: ["Work_Bench","birdToolBox"],
		condition: () => true,
		ingredients: {
			Prismatic_Guppy: 1,
		},
		ingredients_info: "<<icon \"fishing/fish/Prismatic_Guppy.png\">>棱晶孔雀鱼(1)",
		craft: "<<set $Sashimi += 1>>",
		crafting_info: "你制作了1份<<icon \"food/Sashimi.png\">>生鱼片。<<if currentSkillValue('housekeeping') lt 600>><<ghousekeeping 600>><</if>><br>你有<<icon \"food/Sashimi.png\">>生鱼片($Sashimi)，你还有<<icon \"fishing/fish/Prismatic_Guppy.png\">>棱晶孔雀鱼($Prismatic_Guppy)。",
	},
	"Sashimi_Crag_Bullhead": {
		name: "Sashimi",
        cn_name: "生鱼片<br><i>材料</i>",
		des: "- 饥饿值<br><i>“是生的！异国风味！”</i>",
        type: "food",
        icon: "food/Sashimi.png",
		crafting_station: ["Work_Bench","birdToolBox"],
		condition: () => true,
		ingredients: {
			Crag_Bullhead: 1,
		},
		ingredients_info: "<<icon \"fishing/fish/Crag_Bullhead.png\">>硫火崖回鱼(1)",
		craft: "<<set $Sashimi += 1>>",
		crafting_info: "你制作了1份<<icon \"food/Sashimi.png\">>生鱼片。<<if currentSkillValue('housekeeping') lt 600>><<ghousekeeping 600>><</if>><br>你有<<icon \"food/Sashimi.png\">>生鱼片($Sashimi)，你还有<<icon \"fishing/fish/Crag_Bullhead.png\">>硫火崖回鱼($Crag_Bullhead)。",
	},
	//熟鱼：可由 三文鱼、鲈鱼、金枪鱼、红鲷鱼、鳟鱼、偏口鱼、大西洋鳕鱼、棱晶孔雀鱼、硫火崖回鱼 在 烹饪锅 上制作得到
	"Cooked_Fish_Salmon": {
		name: "Cooked_Fish",
        cn_name: "熟鱼",
		des: "- - 饥饿值<br><i>“薯条在哪里！？”</i>",
        type: "food",
        icon: "food/Cooked_Fish.png",
		crafting_station: ["Cooking_Pot","birdPot"],
		condition: () => true,
		ingredients: {
			Salmon: 1,
		},
		ingredients_info: "<<icon \"fishing/fish/Salmon.png\">>三文鱼(1)",
		craft: "<<set $Cooked_Fish += 1>>",
		crafting_info: "你制作了1份<<icon \"food/Cooked_Fish.png\">>熟鱼。<<if currentSkillValue('housekeeping') lt 1000>><<ghousekeeping 1000>><</if>><br>你有<<icon \"food/Cooked_Fish.png\">>熟鱼($Cooked_Fish)，你还有<<icon \"fishing/fish/Salmon.png\">>三文鱼($Salmon)。",
	},
	"Cooked_Fish_Bass": {
		name: "Cooked_Fish",
        cn_name: "熟鱼",
		des: "- - 饥饿值<br><i>“薯条在哪里！？”</i>",
        type: "food",
        icon: "food/Cooked_Fish.png",
		crafting_station: ["Cooking_Pot","birdPot"],
		condition: () => true,
		ingredients: {
			Bass: 1,
		},
		ingredients_info: "<<icon \"fishing/fish/Bass.png\">>鲈鱼(1)",
		craft: "<<set $Cooked_Fish += 1>>",
		crafting_info: "你制作了1份<<icon \"food/Cooked_Fish.png\">>熟鱼。<<if currentSkillValue('housekeeping') lt 1000>><<ghousekeeping 1000>><</if>><br>你有<<icon \"food/Cooked_Fish.png\">>熟鱼($Cooked_Fish)，你还有<<icon \"fishing/fish/Bass.png\">>鲈鱼($Bass)。",
	},
	"Cooked_Fish_Tuna": {
		name: "Cooked_Fish",
        cn_name: "熟鱼",
		des: "- - 饥饿值<br><i>“薯条在哪里！？”</i>",
        type: "food",
        icon: "food/Cooked_Fish.png",
		crafting_station: ["Cooking_Pot","birdPot"],
		condition: () => true,
		ingredients: {
			Tuna: 1,
		},
		ingredients_info: "<<icon \"fishing/fish/Tuna.png\">>金枪鱼(1)",
		craft: "<<set $Cooked_Fish += 1>>",
		crafting_info: "你制作了1份<<icon \"food/Cooked_Fish.png\">>熟鱼。<<if currentSkillValue('housekeeping') lt 1000>><<ghousekeeping 1000>><</if>><br>你有<<icon \"food/Cooked_Fish.png\">>熟鱼($Cooked_Fish)，你还有<<icon \"fishing/fish/Tuna.png\">>金枪鱼($Tuna)。",
	},
	"Cooked_Fish_Red_Snapper": {
		name: "Cooked_Fish",
        cn_name: "熟鱼",
		des: "- - 饥饿值<br><i>“薯条在哪里！？”</i>",
        type: "food",
        icon: "food/Cooked_Fish.png",
		crafting_station: ["Cooking_Pot","birdPot"],
		condition: () => true,
		ingredients: {
			Red_Snapper: 1,
		},
		ingredients_info: "<<icon \"fishing/fish/Red_Snapper.png\">>红鲷鱼(1)",
		craft: "<<set $Cooked_Fish += 1>>",
		crafting_info: "你制作了1份<<icon \"food/Cooked_Fish.png\">>熟鱼。<<if currentSkillValue('housekeeping') lt 1000>><<ghousekeeping 1000>><</if>><br>你有<<icon \"food/Cooked_Fish.png\">>熟鱼($Cooked_Fish)，你还有<<icon \"fishing/fish/Red_Snapper.png\">>红鲷鱼($Red_Snapper)。",
	},
	"Cooked_Fish_Trout": {
		name: "Cooked_Fish",
        cn_name: "熟鱼",
		des: "- - 饥饿值<br><i>“薯条在哪里！？”</i>",
        type: "food",
        icon: "food/Cooked_Fish.png",
		crafting_station: ["Cooking_Pot","birdPot"],
		condition: () => true,
		ingredients: {
			Trout: 1,
		},
		ingredients_info: "<<icon \"fishing/fish/Trout.png\">>鳟鱼(1)",
		craft: "<<set $Cooked_Fish += 1>>",
		crafting_info: "你制作了1份<<icon \"food/Cooked_Fish.png\">>熟鱼。<<if currentSkillValue('housekeeping') lt 1000>><<ghousekeeping 1000>><</if>><br>你有<<icon \"food/Cooked_Fish.png\">>熟鱼($Cooked_Fish)，你还有<<icon \"fishing/fish/Trout.png\">>鳟鱼($Trout)。",
	},
	"Cooked_Fish_Flounder": {
		name: "Cooked_Fish",
        cn_name: "熟鱼",
		des: "- - 饥饿值<br><i>“薯条在哪里！？”</i>",
        type: "food",
        icon: "food/Cooked_Fish.png",
		crafting_station: ["Cooking_Pot","birdPot"],
		condition: () => true,
		ingredients: {
			Flounder: 1,
		},
		ingredients_info: "<<icon \"fishing/fish/Flounder.png\">>偏口鱼(1)",
		craft: "<<set $Cooked_Fish += 1>>",
		crafting_info: "你制作了1份<<icon \"food/Cooked_Fish.png\">>熟鱼。<<if currentSkillValue('housekeeping') lt 1000>><<ghousekeeping 1000>><</if>><br>你有<<icon \"food/Cooked_Fish.png\">>熟鱼($Cooked_Fish)，你还有<<icon \"fishing/fish/Flounder.png\">>偏口鱼($Flounder)。",
	},
	"Cooked_Fish_Atlantic_Cod": {
		name: "Cooked_Fish",
        cn_name: "熟鱼",
		des: "- - 饥饿值<br><i>“薯条在哪里！？”</i>",
        type: "food",
        icon: "food/Cooked_Fish.png",
		crafting_station: ["Cooking_Pot","birdPot"],
		condition: () => true,
		ingredients: {
			Atlantic_Cod: 1,
		},
		ingredients_info: "<<icon \"fishing/fish/Atlantic_Cod.png\">>大西洋鳕鱼(1)",
		craft: "<<set $Cooked_Fish += 1>>",
		crafting_info: "你制作了1份<<icon \"food/Cooked_Fish.png\">>熟鱼。<<if currentSkillValue('housekeeping') lt 1000>><<ghousekeeping 1000>><</if>><br>你有<<icon \"food/Cooked_Fish.png\">>熟鱼($Cooked_Fish)，你还有<<icon \"fishing/fish/Atlantic_Cod.png\">>大西洋鳕鱼($Atlantic_Cod)。",
	},
	"Cooked_Fish_Prismatic_Guppy": {
		name: "Cooked_Fish",
        cn_name: "熟鱼",
		des: "- - 饥饿值<br><i>“薯条在哪里！？”</i>",
        type: "food",
        icon: "food/Cooked_Fish.png",
		crafting_station: ["Cooking_Pot","birdPot"],
		condition: () => true,
		ingredients: {
			Prismatic_Guppy: 1,
		},
		ingredients_info: "<<icon \"fishing/fish/Prismatic_Guppy.png\">>棱晶孔雀鱼(1)",
		craft: "<<set $Cooked_Fish += 1>>",
		crafting_info: "你制作了1份<<icon \"food/Cooked_Fish.png\">>熟鱼。<<if currentSkillValue('housekeeping') lt 1000>><<ghousekeeping 1000>><</if>><br>你有<<icon \"food/Cooked_Fish.png\">>熟鱼($Cooked_Fish)，你还有<<icon \"fishing/fish/Prismatic_Guppy.png\">>棱晶孔雀鱼($Prismatic_Guppy)。",
	},
	"Cooked_Fish_Crag_Bullhead": {
		name: "Cooked_Fish",
        cn_name: "熟鱼",
		des: "- - 饥饿值<br><i>“薯条在哪里！？”</i>",
        type: "food",
        icon: "food/Cooked_Fish.png",
		crafting_station: ["Cooking_Pot","birdPot"],
		condition: () => true,
		ingredients: {
			Crag_Bullhead: 1,
		},
		ingredients_info: "<<icon \"fishing/fish/Crag_Bullhead.png\">>硫火崖回鱼(1)",
		craft: "<<set $Cooked_Fish += 1>>",
		crafting_info: "你制作了1份<<icon \"food/Cooked_Fish.png\">>熟鱼。<<if currentSkillValue('housekeeping') lt 1000>><<ghousekeeping 1000>><</if>><br>你有<<icon \"food/Cooked_Fish.png\">>熟鱼($Cooked_Fish)，你还有<<icon \"fishing/fish/Crag_Bullhead.png\">>硫火崖回鱼($Crag_Bullhead)。",
	},
	//熟虾：可由 虾 在 烹饪锅 上制作得到
	"Cooked_Shrimp": {
		name: "Cooked_Shrimp",
        cn_name: "熟虾",
		des: "- 饥饿值<br><i>“烧、煮、烤、烘……”</i>",
        type: "food",
        icon: "food/Cooked_Shrimp.png",
		crafting_station: ["Cooking_Pot","birdPot"],
		condition: () => true,
		ingredients: {
			Shrimp: 1,
		},
		ingredients_info: "<<icon \"fishing/fish/Shrimp.png\">>虾(1)",
		craft: "<<set $Cooked_Shrimp += 1>>",
		crafting_info: "你制作了1份<<icon \"food/Cooked_Shrimp.png\">>熟虾。<<if currentSkillValue('housekeeping') lt 1000>><<ghousekeeping 1000>><</if>><br>你有<<icon \"food/Cooked_Shrimp.png\">>熟虾($Cooked_Shrimp)，你还有<<icon \"fishing/fish/Shrimp.png\">>虾($Shrimp)。",
	},
	//龙虾尾：可由 岩石龙虾 在 烹饪锅 上制作得到
	"Lobster_Tail": {
		name: "Lobster_Tail",
        cn_name: "龙虾尾",
		des: "- - 饥饿值<br><i>“加一点黄油就很美味了”</i>",
        type: "food",
        icon: "food/Lobster_Tail.png",
		crafting_station: ["Cooking_Pot","birdPot"],
		condition: () => true,
		ingredients: {
			Rock_Lobster: 1,
		},
		ingredients_info: "<<icon \"fishing/fish/Rock_Lobster.png\">>岩石龙虾(1)",
		craft: "<<set $Lobster_Tail += 1>>",
		crafting_info: "你制作了1份<<icon \"food/Lobster_Tail.png\">>龙虾尾。<<if currentSkillValue('housekeeping') lt 1000>><<ghousekeeping 1000>><</if>><br>你有<<icon \"food/Lobster_Tail.png\">>龙虾尾($Lobster_Tail)，你还有<<icon \"fishing/fish/Rock_Lobster.png\">>岩石龙虾($Rock_Lobster)。",
	},
	//海鲜大餐：可由 臭味鱼、装甲洞穴鱼、镜面鱼、双鳍鳕鱼、斑驳油鱼、霓虹脂鲤、混沌鱼、七彩矿鱼、公主鱼、寒霜绦鱼、闪鳍锦鲤、黑曜石鱼、沉沦帆鱼、海岸恶魔鱼 在 烹饪锅 上制作得到
	"Seafood_Dinner_Stinkfish": {
		name: "Seafood_Dinner",
        cn_name: "海鲜大餐",
		des: "- - - 饥饿值<br><i>“我，海鲜，吃掉。”</i>",
        type: "food",
        icon: "food/Seafood_Dinner.png",
		crafting_station: ["Cooking_Pot","birdPot"],
		condition: () => true,
		ingredients: {
			Stinkfish: 2,
		},
		ingredients_info: "<<icon \"fishing/fish/Stinkfish.png\">>臭味鱼(2)",
		craft: "<<set $Seafood_Dinner += 1>>",
		crafting_info: "你制作了1份<<icon \"food/Seafood_Dinner.png\">>海鲜大餐。<<if currentSkillValue('housekeeping') lt 1000>><<ghousekeeping 1000>><</if>><br>你有<<icon \"food/Seafood_Dinner.png\">>海鲜大餐($Seafood_Dinner)，你还有<<icon \"fishing/fish/Stinkfish.png\">>臭味鱼($Stinkfish)。",
	},
	"Seafood_Dinner_Armored_Cavefish": {
		name: "Seafood_Dinner",
        cn_name: "海鲜大餐",
		des: "- - - 饥饿值<br><i>“我，海鲜，吃掉。”</i>",
        type: "food",
        icon: "food/Seafood_Dinner.png",
		crafting_station: ["Cooking_Pot","birdPot"],
		condition: () => true,
		ingredients: {
			Armored_Cavefish: 2,
		},
		ingredients_info: "<<icon \"fishing/fish/Armored_Cavefish.png\">>装甲洞穴鱼(2)",
		craft: "<<set $Seafood_Dinner += 1>>",
		crafting_info: "你制作了1份<<icon \"food/Seafood_Dinner.png\">>海鲜大餐。<<if currentSkillValue('housekeeping') lt 1000>><<ghousekeeping 1000>><</if>><br>你有<<icon \"food/Seafood_Dinner.png\">>海鲜大餐($Seafood_Dinner)，你还有<<icon \"fishing/fish/Armored_Cavefish.png\">>装甲洞穴鱼($Armored_Cavefish)。",
	},
	"Seafood_Dinner_Specular_Fish": {
		name: "Seafood_Dinner",
        cn_name: "海鲜大餐",
		des: "- - - 饥饿值<br><i>“我，海鲜，吃掉。”</i>",
        type: "food",
        icon: "food/Seafood_Dinner.png",
		crafting_station: ["Cooking_Pot","birdPot"],
		condition: () => true,
		ingredients: {
			Specular_Fish: 2,
		},
		ingredients_info: "<<icon \"fishing/fish/Specular_Fish.png\">>镜面鱼(2)",
		craft: "<<set $Seafood_Dinner += 1>>",
		crafting_info: "你制作了1份<<icon \"food/Seafood_Dinner.png\">>海鲜大餐。<<if currentSkillValue('housekeeping') lt 1000>><<ghousekeeping 1000>><</if>><br>你有<<icon \"food/Seafood_Dinner.png\">>海鲜大餐($Seafood_Dinner)，你还有<<icon \"fishing/fish/Specular_Fish.png\">>镜面鱼($Specular_Fish)。",
	},
	"Seafood_Dinner_Honeyfin": {
		name: "Seafood_Dinner",
        cn_name: "海鲜大餐",
		des: "- - - 饥饿值<br><i>“我，海鲜，吃掉。”</i>",
        type: "food",
        icon: "food/Seafood_Dinner.png",
		crafting_station: ["Cooking_Pot","birdPot"],
		condition: () => true,
		ingredients: {
			Honeyfin: 2,
		},
		ingredients_info: "<<icon \"fishing/fish/Honeyfin.png\">>蜂蜜鱼(2)",
		craft: "<<set $Seafood_Dinner += 1>>",
		crafting_info: "你制作了1份<<icon \"food/Seafood_Dinner.png\">>海鲜大餐。<<if currentSkillValue('housekeeping') lt 1000>><<ghousekeeping 1000>><</if>><br>你有<<icon \"food/Seafood_Dinner.png\">>海鲜大餐($Seafood_Dinner)，你还有<<icon \"fishing/fish/Honeyfin.png\">>蜂蜜鱼($Honeyfin)。",
	},
	"Seafood_Dinner_Double_Cod": {
		name: "Seafood_Dinner",
        cn_name: "海鲜大餐",
		des: "- - - 饥饿值<br><i>“我，海鲜，吃掉。”</i>",
        type: "food",
        icon: "food/Seafood_Dinner.png",
		crafting_station: ["Cooking_Pot","birdPot"],
		condition: () => true,
		ingredients: {
			Double_Cod: 2,
		},
		ingredients_info: "<<icon \"fishing/fish/Double_Cod.png\">>双鳍鳕鱼(2)",
		craft: "<<set $Seafood_Dinner += 1>>",
		crafting_info: "你制作了1份<<icon \"food/Seafood_Dinner.png\">>海鲜大餐。<<if currentSkillValue('housekeeping') lt 1000>><<ghousekeeping 1000>><</if>><br>你有<<icon \"food/Seafood_Dinner.png\">>海鲜大餐($Seafood_Dinner)，你还有<<icon \"fishing/fish/Double_Cod.png\">>双鳍鳕鱼($Double_Cod)。",
	},
	"Seafood_Dinner_Variegated_Lardfish": {
		name: "Seafood_Dinner",
        cn_name: "海鲜大餐",
		des: "- - - 饥饿值<br><i>“我，海鲜，吃掉。”</i>",
        type: "food",
        icon: "food/Seafood_Dinner.png",
		crafting_station: ["Cooking_Pot","birdPot"],
		condition: () => true,
		ingredients: {
			Variegated_Lardfish: 2,
		},
		ingredients_info: "<<icon \"fishing/fish/Variegated_Lardfish.png\">>斑驳油鱼(2)",
		craft: "<<set $Seafood_Dinner += 1>>",
		crafting_info: "你制作了1份<<icon \"food/Seafood_Dinner.png\">>海鲜大餐。<<if currentSkillValue('housekeeping') lt 1000>><<ghousekeeping 1000>><</if>><br>你有<<icon \"food/Seafood_Dinner.png\">>海鲜大餐($Seafood_Dinner)，你还有<<icon \"fishing/fish/Variegated_Lardfish.png\">>斑驳油鱼($Variegated_Lardfish)。",
	},
	"Seafood_Dinner_Neon_Tetra": {
		name: "Seafood_Dinner",
        cn_name: "海鲜大餐",
		des: "- - - 饥饿值<br><i>“我，海鲜，吃掉。”</i>",
        type: "food",
        icon: "food/Seafood_Dinner.png",
		crafting_station: ["Cooking_Pot","birdPot"],
		condition: () => true,
		ingredients: {
			Neon_Tetra: 2,
		},
		ingredients_info: "<<icon \"fishing/fish/Neon_Tetra.png\">>霓虹脂鲤(2)",
		craft: "<<set $Seafood_Dinner += 1>>",
		crafting_info: "你制作了1份<<icon \"food/Seafood_Dinner.png\">>海鲜大餐。<<if currentSkillValue('housekeeping') lt 1000>><<ghousekeeping 1000>><</if>><br>你有<<icon \"food/Seafood_Dinner.png\">>海鲜大餐($Seafood_Dinner)，你还有<<icon \"fishing/fish/Neon_Tetra.png\">>霓虹脂鲤($Neon_Tetra)。",
	},
	"Seafood_Dinner_Chaos_Fish": {
		name: "Seafood_Dinner",
        cn_name: "海鲜大餐",
		des: "- - - 饥饿值<br><i>“我，海鲜，吃掉。”</i>",
        type: "food",
        icon: "food/Seafood_Dinner.png",
		crafting_station: ["Cooking_Pot","birdPot"],
		condition: () => true,
		ingredients: {
			Chaos_Fish: 2,
		},
		ingredients_info: "<<icon \"fishing/fish/Chaos_Fish.png\">>混沌鱼(2)",
		craft: "<<set $Seafood_Dinner += 1>>",
		crafting_info: "你制作了1份<<icon \"food/Seafood_Dinner.png\">>海鲜大餐。<<if currentSkillValue('housekeeping') lt 1000>><<ghousekeeping 1000>><</if>><br>你有<<icon \"food/Seafood_Dinner.png\">>海鲜大餐($Seafood_Dinner)，你还有<<icon \"fishing/fish/Chaos_Fish.png\">>混沌鱼($Chaos_Fish)。",
	},
	"Seafood_Dinner_Prismite": {
		name: "Seafood_Dinner",
        cn_name: "海鲜大餐",
		des: "- - - 饥饿值<br><i>“我，海鲜，吃掉。”</i>",
        type: "food",
        icon: "food/Seafood_Dinner.png",
		crafting_station: ["Cooking_Pot","birdPot"],
		condition: () => true,
		ingredients: {
			Prismite: 2,
		},
		ingredients_info: "<<icon \"fishing/fish/Prismite.png\">>七彩矿鱼(2)",
		craft: "<<set $Seafood_Dinner += 1>>",
		crafting_info: "你制作了1份<<icon \"food/Seafood_Dinner.png\">>海鲜大餐。<<if currentSkillValue('housekeeping') lt 1000>><<ghousekeeping 1000>><</if>><br>你有<<icon \"food/Seafood_Dinner.png\">>海鲜大餐($Seafood_Dinner)，你还有<<icon \"fishing/fish/Prismite.png\">>七彩矿鱼($Prismite)。",
	},
	"Seafood_Dinner_Princess_Fish": {
		name: "Seafood_Dinner",
        cn_name: "海鲜大餐",
		des: "- - - 饥饿值<br><i>“我，海鲜，吃掉。”</i>",
        type: "food",
        icon: "food/Seafood_Dinner.png",
		crafting_station: ["Cooking_Pot","birdPot"],
		condition: () => true,
		ingredients: {
			Princess_Fish: 2,
		},
		ingredients_info: "<<icon \"fishing/fish/Princess_Fish.png\">>公主鱼(2)",
		craft: "<<set $Seafood_Dinner += 1>>",
		crafting_info: "你制作了1份<<icon \"food/Seafood_Dinner.png\">>海鲜大餐。<<if currentSkillValue('housekeeping') lt 1000>><<ghousekeeping 1000>><</if>><br>你有<<icon \"food/Seafood_Dinner.png\">>海鲜大餐($Seafood_Dinner)，你还有<<icon \"fishing/fish/Princess_Fish.png\">>公主鱼($Princess_Fish)。",
	},
	"Seafood_Dinner_Damselfish": {
		name: "Seafood_Dinner",
        cn_name: "海鲜大餐",
		des: "- - - 饥饿值<br><i>“我，海鲜，吃掉。”</i>",
        type: "food",
        icon: "food/Seafood_Dinner.png",
		crafting_station: ["Cooking_Pot","birdPot"],
		condition: () => true,
		ingredients: {
			Damselfish: 2,
		},
		ingredients_info: "<<icon \"fishing/fish/Damselfish.png\">>雀鲷(2)",
		craft: "<<set $Seafood_Dinner += 1>>",
		crafting_info: "你制作了1份<<icon \"food/Seafood_Dinner.png\">>海鲜大餐。<<if currentSkillValue('housekeeping') lt 1000>><<ghousekeeping 1000>><</if>><br>你有<<icon \"food/Seafood_Dinner.png\">>海鲜大餐($Seafood_Dinner)，你还有<<icon \"fishing/fish/Damselfish.png\">>雀鲷($Damselfish)。",
	},
	"Seafood_Dinner_Frost_Minnow": {
		name: "Seafood_Dinner",
        cn_name: "海鲜大餐",
		des: "- - - 饥饿值<br><i>“我，海鲜，吃掉。”</i>",
        type: "food",
        icon: "food/Seafood_Dinner.png",
		crafting_station: ["Cooking_Pot","birdPot"],
		condition: () => true,
		ingredients: {
			Frost_Minnow: 2,
		},
		ingredients_info: "<<icon \"fishing/fish/Frost_Minnow.png\">>寒霜绦鱼(2)",
		craft: "<<set $Seafood_Dinner += 1>>",
		crafting_info: "你制作了1份<<icon \"food/Seafood_Dinner.png\">>海鲜大餐。<<if currentSkillValue('housekeeping') lt 1000>><<ghousekeeping 1000>><</if>><br>你有<<icon \"food/Seafood_Dinner.png\">>海鲜大餐($Seafood_Dinner)，你还有<<icon \"fishing/fish/Frost_Minnow.png\">>寒霜绦鱼($Frost_Minnow)。",
	},
	"Seafood_Dinner_Flarefin_Koi": {
		name: "Seafood_Dinner",
        cn_name: "海鲜大餐",
		des: "- - - 饥饿值<br><i>“我，海鲜，吃掉。”</i>",
        type: "food",
        icon: "food/Seafood_Dinner.png",
		crafting_station: ["Cooking_Pot","birdPot"],
		condition: () => true,
		ingredients: {
			Flarefin_Koi: 2,
		},
		ingredients_info: "<<icon \"fishing/fish/Flarefin_Koi.png\">>闪鳍锦鲤(2)",
		craft: "<<set $Seafood_Dinner += 1>>",
		crafting_info: "你制作了1份<<icon \"food/Seafood_Dinner.png\">>海鲜大餐。<<if currentSkillValue('housekeeping') lt 1000>><<ghousekeeping 1000>><</if>><br>你有<<icon \"food/Seafood_Dinner.png\">>海鲜大餐($Seafood_Dinner)，你还有<<icon \"fishing/fish/Flarefin_Koi.png\">>闪鳍锦鲤($Flarefin_Koi)。",
	},
	"Seafood_Dinner_Obsidifish": {
		name: "Seafood_Dinner",
        cn_name: "海鲜大餐",
		des: "- - - 饥饿值<br><i>“我，海鲜，吃掉。”</i>",
        type: "food",
        icon: "food/Seafood_Dinner.png",
		crafting_station: ["Cooking_Pot","birdPot"],
		condition: () => true,
		ingredients: {
			Obsidifish: 2,
		},
		ingredients_info: "<<icon \"fishing/fish/Obsidifish.png\">>黑曜石鱼(2)",
		craft: "<<set $Seafood_Dinner += 1>>",
		crafting_info: "你制作了1份<<icon \"food/Seafood_Dinner.png\">>海鲜大餐。<<if currentSkillValue('housekeeping') lt 1000>><<ghousekeeping 1000>><</if>><br>你有<<icon \"food/Seafood_Dinner.png\">>海鲜大餐($Seafood_Dinner)，你还有<<icon \"fishing/fish/Obsidifish.png\">>黑曜石鱼($Obsidifish)。",
	},
	"Seafood_Dinner_Sunken_Sailfish": {
		name: "Seafood_Dinner",
        cn_name: "海鲜大餐",
		des: "- - - 饥饿值<br><i>“我，海鲜，吃掉。”</i>",
        type: "food",
        icon: "food/Seafood_Dinner.png",
		crafting_station: ["Cooking_Pot","birdPot"],
		condition: () => true,
		ingredients: {
			Sunken_Sailfish: 2,
		},
		ingredients_info: "<<icon \"fishing/fish/Sunken_Sailfish.png\">>沉沦帆鱼(2)",
		craft: "<<set $Seafood_Dinner += 1>>",
		crafting_info: "你制作了1份<<icon \"food/Seafood_Dinner.png\">>海鲜大餐。<<if currentSkillValue('housekeeping') lt 1000>><<ghousekeeping 1000>><</if>><br>你有<<icon \"food/Seafood_Dinner.png\">>海鲜大餐($Seafood_Dinner)，你还有<<icon \"fishing/fish/Sunken_Sailfish.png\">>沉沦帆鱼($Sunken_Sailfish)。",
	},
	"Seafood_Dinner_Coastal_Demonfish": {
		name: "Seafood_Dinner",
        cn_name: "海鲜大餐",
		des: "- - - 饥饿值<br><i>“我，海鲜，吃掉。”</i>",
        type: "food",
        amount: V.Seafood_Dinner || 0,
        icon: "food/Seafood_Dinner.png",
		crafting_station: ["Cooking_Pot","birdPot"],
		condition: () => true,
		ingredients: {
			Coastal_Demonfish: 2,
		},
		ingredients_info: "<<icon \"fishing/fish/Coastal_Demonfish.png\">>海岸恶魔鱼(2)",
		craft: "<<set $Seafood_Dinner += 1>>",
		crafting_info: "你制作了1份<<icon \"food/Seafood_Dinner.png\">>海鲜大餐。<<if currentSkillValue('housekeeping') lt 1000>><<ghousekeeping 1000>><</if>><br>你有<<icon \"food/Seafood_Dinner.png\">>海鲜大餐($Seafood_Dinner)，你还有<<icon \"fishing/fish/Coastal_Demonfish.png\">>海岸恶魔鱼($Coastal_Demonfish)。",
	},
	// 肥料：生鱼片(2)+学徒诱饵(10)/熟手诱饵(5)/大师诱饵(3) 在 工作台 上制作得到
	"fertiliser_Apprentice_Bait": {
		name: "fertiliser",
        cn_name: "肥料",
		des: "在镇里原本是价值连城的化工产品，从海外运输而来。使用后可以增长土地肥力。",
        type: "fertiliser",
        icon: "fertiliser.png",
		crafting_station: ["Work_Bench"],
		condition: () => true,
		ingredients: {
			Sashimi: 2,
			Apprentice_Bait: 10,
		},
		ingredients_info: "<<icon \"food/Sashimi.png\">>生鱼片(2)<br><<icon \"fishing/bait/Apprentice_Bait.png\">>学徒诱饵(10)",
		craft: "<<if $Apprentice_Bait lte 0 and $Bait is 'Apprentice_Bait'>><<set $Bait to 'None'>><</if>><<set $fertiliser.current += 1>>",
		crafting_info: "你制作了1袋<<icon \"fertiliser.png\">>肥料。<br>你有<<icon \"fertiliser.png\">>肥料($fertiliser.current)，你还有<<icon \"food/Sashimi.png\">>生鱼片($Sashimi)和<<icon \"fishing/bait/Apprentice_Bait.png\">>学徒诱饵($Apprentice_Bait)。",
	},
	"fertiliser_Journeyman_Bait": {
		name: "fertiliser",
        cn_name: "肥料",
		des: "在镇里原本是价值连城的化工产品，从海外运输而来。使用后可以增长土地肥力。",
        type: "fertiliser",
        icon: "fertiliser.png",
		crafting_station: ["Work_Bench"],
		condition: () => true,
		ingredients: {
			Sashimi: 2,
			Journeyman_Bait: 5,
		},
		ingredients_info: "<<icon \"food/Sashimi.png\">>生鱼片(2)<br><<icon \"fishing/bait/Journeyman_Bait.png\">>熟手诱饵(5)",
		craft: "<<if $Journeyman_Bait lte 0 and $Bait is 'Journeyman_Bait'>><<set $Bait to 'None'>><</if>><<set $fertiliser.current += 1>>",
		crafting_info: "你制作了1袋<<icon \"fertiliser.png\">>肥料。<br>你有<<icon \"fertiliser.png\">>肥料($fertiliser.current)，你还有<<icon \"food/Sashimi.png\">>生鱼片($Sashimi)和<<icon \"fishing/bait/Journeyman_Bait.png\">>熟手诱饵($Journeyman_Bait)。",
	},
	"fertiliser_Master_Bait": {
		name: "fertiliser",
        cn_name: "肥料",
		des: "在镇里原本是价值连城的化工产品，从海外运输而来。使用后可以增长土地肥力。",
        type: "fertiliser",
        icon: "fertiliser.png",
		crafting_station: ["Work_Bench"],
		condition: () => true,
		ingredients: {
			Sashimi: 2,
			Master_Bait: 3,
		},
		ingredients_info: "<<icon \"food/Sashimi.png\">>生鱼片(2)<br><<icon \"fishing/bait/Master_Bait.png\">>大师诱饵(3)",
		craft: "<<if $Master_Bait lte 0 and $Bait is 'Master_Bait'>><<set $Bait to 'None'>><</if>><<set $fertiliser.current += 1>>",
		crafting_info: "你制作了1袋<<icon \"fertiliser.png\">>肥料。<br>你有<<icon \"fertiliser.png\">>肥料($fertiliser.current)，你还有<<icon \"food/Sashimi.png\">>生鱼片($Sashimi)和<<icon \"fishing/bait/Master_Bait.png\">>大师诱饵($Master_Bait)。",
	},
	//鱼饵
	"Enchanted_Nightcrawler": {
		name: "Enchanted_Nightcrawler",
        cn_name: "附魔夜行者",
		des: "35渔力",
        type: "bait",
        icon: "fishing/bait/Enchanted_Nightcrawler.png",
		crafting_station: ["Work_Bench"],
		condition: () => true,
		ingredients: {
			Worm: 1,
			Fallen_Star: 1,
		},
		ingredients_info: "<<icon \"fishing/bait/Worm.png\">>蠕虫(1)<br><<icon \"material/Fallen_Star.png\">>坠落之星(1)",
		craft: "<<if $Worm lte 0 and $Bait is 'Worm'>><<set $Bait to 'None'>><</if>><<set $Enchanted_Nightcrawler += 1>><<bestiaryStatistics 'bait' 'Enchanted_Nightcrawler' 1>>",
		crafting_info: "你制作了1只<<icon \"fishing/bait/Enchanted_Nightcrawler.png\">>附魔夜行者。<br>你有<<icon \"fishing/bait/Enchanted_Nightcrawler.png\">>附魔夜行者($Enchanted_Nightcrawler)，你还有<<icon \"fishing/bait/Worm.png\">>蠕虫($Worm)和<<icon \"material/Fallen_Star.png\">>坠落之星($Fallen_Star)。",
	},
	// 原版的新食材
	"Cod": {
		name: "Cod",
		cn_name: "鳕鱼",
		des: "厨房食材",
		type: "kitchen",
		icon: "tending/cod.png",
		crafting_station: ["Work_Bench"],
		condition: () => true,
		ingredients: {
			Atlantic_Cod: 1,
		},
		ingredients_info: "<<icon \"fishing/fish/Atlantic_Cod.png\">>大西洋鳕鱼(1)",
		craft: "<<set $plants.cod.amount += 1>>",
		crafting_info: "你制作了1份<<icon \"tending/cod.png\">>鳕鱼。<br>你有<<icon \"tending/cod.png\">>鳕鱼($plants.cod.amount)，你还有<<icon \"fishing/fish/Atlantic_Cod.png\">>大西洋鳕鱼($Atlantic_Cod)。",
	},
	"Haddock": {
		name: "Haddock",
		cn_name: "黑线鳕鱼",
		des: "厨房食材",
		type: "kitchen",
		icon: "tending/haddock.png",
		crafting_station: ["Work_Bench"],
		condition: () => true,
		ingredients: {
			Double_Cod: 1,
		},
		ingredients_info: "<<icon \"fishing/fish/Double_Cod.png\">>双鳍鳕鱼(1)",
		craft: "<<set $plants.haddock.amount += 1>>",
		crafting_info: "你制作了1份<<icon \"tending/haddock.png\">>黑线鳕鱼。<br>你有<<icon \"tending/haddock.png\">>黑线鳕鱼($plants.haddock.amount)，你还有<<icon \"fishing/fish/Double_Cod.png\">>双鳍鳕鱼($Double_Cod)。",
	},
	"Prawn": {
		name: "Prawn",
		cn_name: "虾",
		des: "厨房食材",
		type: "kitchen",
		icon: "tending/prawn.png",
		crafting_station: ["Work_Bench"],
		condition: () => true,
		ingredients: {
			Shrimp: 1,
		},
		ingredients_info: "<<icon \"fishing/fish/Shrimp.png\">>虾(1)",
		craft: "<<set $plants.prawn.amount += 1>>",
		crafting_info: "你制作了1份<<icon \"tending/prawn.png\">>虾。<br>你有<<icon \"tending/prawn.png\">>虾($plants.prawn.amount)，你还有<<icon \"fishing/fish/Shrimp.png\">>虾($Shrimp)。",
	},
	"Salmon": {
		name: "Salmon",
		cn_name: "鲑鱼",
		des: "厨房食材",
		type: "kitchen",
		icon: "tending/salmon.png",
		crafting_station: ["Work_Bench"],
		condition: () => true,
		ingredients: {
			Salmon: 1,
		},
		ingredients_info: "<<icon \"fishing/fish/Salmon.png\">>三文鱼(1)",
		craft: "<<set $plants.salmon.amount += 1>>",
		crafting_info: "你制作了1份<<icon \"tending/salmon.png\">>鲑鱼。<br>你有<<icon \"tending/salmon.png\">>鲑鱼($plants.salmon.amount)，你还有<<icon \"fishing/fish/Salmon.png\">>三文鱼($Salmon)。",
	},
	"Trout": {
		name: "Trout",
		cn_name: "鳟鱼",
		des: "厨房食材",
		type: "kitchen",
		icon: "tending/trout.png",
		crafting_station: ["Work_Bench"],
		condition: () => true,
		ingredients: {
			Trout: 1,
		},
		ingredients_info: "<<icon \"fishing/fish/Trout.png\">>鳟鱼(1)",
		craft: "<<set $plants.trout.amount += 1>>",
		crafting_info: "你制作了1份<<icon \"tending/trout.png\">>鳟鱼。<br>你有<<icon \"tending/trout.png\">>鳟鱼($plants.trout.amount)，你还有<<icon \"fishing/fish/Trout.png\">>鳟鱼($Trout)。",
	},
	"Honey_Honeyfin": {
		name: "Honey",
		cn_name: "蜂蜜",
		des: "厨房食材，香甜可口",
		type: "kitchen",
		icon: "tending/honey.png",
		crafting_station: ["Work_Bench"],
		condition: () => true,
		ingredients: {
			Honeyfin: 1,
		},
		ingredients_info: "<<icon \"fishing/fish/Honeyfin.png\">>蜂蜜鱼(1)",
		craft: "<<set $plants.honey.amount += 400>>",
		crafting_info: "你制作了400份<<icon \"tending/honey.png\">>蜂蜜。<br>你有<<icon \"tending/honey.png\">>蜂蜜($plants.honey.amount)，你还有<<icon \"fishing/fish/Honeyfin.png\">>蜂蜜鱼($Honeyfin)。",
	},
	"Honey_Bottomless_Honey_Bucket": {
		name: "Honey",
		cn_name: "蜂蜜",
		des: "厨房食材，香甜可口",
		type: "kitchen",
		icon: "tending/honey.png",
		crafting_station: ["Work_Bench"],
		condition: () => true,
		ingredients: {
			Bottomless_Honey_Bucket: true,
		},
		ingredients_info: "<<icon \"tool/Bottomless_Honey_Bucket.png\">>无底蜂蜜桶(不消耗)",
		craft: "<<set $plants.honey.amount += 100>>",
		crafting_info: "你制作了100份<<icon \"tending/honey.png\">>蜂蜜。",
	},
}

function getAllRecipeList() {
    let all_recipe_list = Object.keys(setup.terraRecipe);
	return all_recipe_list;
}
window.getAllRecipeList = getAllRecipeList;