setup.terraTravelingMerchantGoods = {
	"Angel_Halo": {
		name: "Angel_Halo",
		cn_name: "天使光环",
		type: "vanity_accessory",
		stackable: false,
		rarity: 6,
		price: 400000,
		obtained: V.Angel_Halo,
		icon: "vanity_accessories/Angel_Halo.png",
		des: "一个天使的光环！防止天使转化点数衰退<br><br><i>时装</i>：获得仅自己可见的天使光环",
		purchase_info: "你购买了一个<<icon 'vanity_accessories/Angel_Halo.png'>>天使光环。<i>试着在装备栏里戴上它。</i>",
	},
	"Eye_Bone": {
		name: "Eye_Bone",
		cn_name: "眼骨",
		type: "pet",
		stackable: false,
		rarity: 5,
		price: 1000000,
		obtained: V.Eye_Bone,
		icon: "pet/pet_item/Eye_Bone.png",
		des: "召唤一只活宝箱<br>“它正在审视我的灵魂。”",
		purchase_info: "你购买了一个<<icon 'pet/pet_item/Eye_Bone.png'>>眼骨。<i>你可以在孤儿院的卧室里使用它。</i>",
	},
	"Glommers_Flower": {
		name: "Glommers_Flower",
		cn_name: "格罗姆的花",
		type: "pet",
		stackable: false,
		rarity: 5,
		price: 1000000,
		obtained: V.Glommers_Flower,
		icon: "pet/pet_item/Glommers_Flower.png",
		des: "召唤格罗姆<br>“花瓣在阳光下闪闪发光。”",
		purchase_info: "你购买了一个<<icon 'pet/pet_item/Glommers_Flower.png'>>格罗姆的花。<i>你可以在孤儿院的卧室里使用它。</i>",
	},
	"Sitting_Ducks_Fishing_Pole": {
		name: "Sitting_Ducks_Fishing_Pole",
		cn_name: "冤大头钓竿",
		type: "fishing_pole",
		stackable: false,
		rarity: 4,
		price: 350000,
		obtained: V.Sitting_Ducks_Fishing_Pole,
		icon: "fishing/fishing_pole/Sitting_Ducks_Fishing_Pole.png",
		purchase_info: "你购买了一把<<icon 'fishing/fishing_pole/Sitting_Ducks_Fishing_Pole.png'>>冤大头钓竿。<i>为什么这个鱼竿会叫这个名字？</i>",
		des: "40渔力",
	},
	"Companion_Cube": {
		name: "Companion_Cube",
		cn_name: "同伴方块",
		type: "pet",
		stackable: false,
		rarity: 4,
		price: 5000000,
		obtained: V.Companion_Cube,
		icon: "pet/pet_item/Companion_Cube.png",
		des: "召唤同伴方块<br>“易受熔岩伤害！”",
		purchase_info: "你购买了一个<<icon 'pet/pet_item/Companion_Cube.png'>>同伴方块。<i>你可以在孤儿院的卧室里使用它。</i>",
	},
	"Birdie_Rattle": {
		name: "Birdie_Rattle",
		cn_name: "小鸟拨浪鼓",
		type: "pet",
		stackable: false,
		rarity: 4,
		price: 1000000,
		obtained: V.Birdie_Rattle,
		icon: "pet/pet_item/Birdie_Rattle.png",
		des: "召唤鸟妖宝宝<br>“不适合你的日常小鹦鹉”",
		purchase_info: "你购买了一个<<icon 'pet/pet_item/Birdie_Rattle.png'>>小鸟拨浪鼓。<i>你可以在孤儿院的卧室里使用它。</i>",
	},
	"Exotic_Chew_Toy": {
		name: "Exotic_Chew_Toy",
		cn_name: "奇异咀嚼玩具",
		type: "pet",
		stackable: false,
		rarity: 4,
		price: 1000000,
		obtained: V.Exotic_Chew_Toy,
		icon: "pet/pet_item/Exotic_Chew_Toy.png",
		des: "召唤耳廓狐<br>“它的叫声是惊人的96千赫！”",
		purchase_info: "你购买了一个<<icon 'pet/pet_item/Exotic_Chew_Toy.png'>>奇异咀嚼玩具。<i>你可以在孤儿院的卧室里使用它。</i>",
	},
	"Blue_Chicken_Egg": {
		name: "Blue_Chicken_Egg",
		cn_name: "蓝鸡蛋",
		type: "pet",
		stackable: false,
		rarity: 4,
		price: 250000,
		obtained: V.Blue_Chicken_Egg,
		icon: "pet/pet_item/Blue_Chicken_Egg.png",
		des: "召唤蓝鸡<br>“普普通通的蓝色鸡蛋”",
		purchase_info: "你购买了一个<<icon 'pet/pet_item/Blue_Chicken_Egg.png'>>蓝鸡蛋。<i>你可以在孤儿院的卧室里使用它。</i>",
	},
	"Bedazzled_Nectar": {
		name: "Bedazzled_Nectar",
		cn_name: "眩晕花蜜",
		type: "pet",
		stackable: false,
		rarity: 4,
		price: 1000000,
		obtained: V.Bedazzled_Nectar,
		icon: "pet/pet_item/Bedazzled_Nectar.png",
		des: "召唤宠物蝴蝶<br>“只要最好、最精致的花蜜！”",
		purchase_info: "你购买了一个<<icon 'pet/pet_item/Bedazzled_Nectar.png'>>眩晕花蜜。<i>你可以在孤儿院的卧室里使用它。</i>",
	},
	"Bamboo_Leaf": {
		name: "Bamboo_Leaf",
		cn_name: "竹叶",
		type: "pet",
		stackable: false,
		rarity: 4,
		price: 1000000,
		obtained: V.Bamboo_Leaf,
		icon: "pet/pet_item/Bamboo_Leaf.png",
		des: "召唤小熊猫宝宝",
		purchase_info: "你购买了一个<<icon 'pet/pet_item/Bamboo_Leaf.png'>>竹叶。<i>你可以在孤儿院的卧室里使用它。</i>",
	},
	"Slurper_Pole": {
		name: "Slurper_Pole",
		cn_name: "饮食者钓竿",
		type: "fishing_pole",
		stackable: false,
		rarity: 3,
		price: 80000,
		obtained: V.Slurper_Pole,
		icon: "fishing/fishing_pole/Slurper_Pole.png",
		des: "25渔力，能够在沸水/岩浆中垂钓",
		purchase_info: "你购买了一把<<icon 'fishing/fishing_pole/Slurper_Pole.png'>>饮食者钓竿。<i>它隐隐散发着不祥的气息(其实并不会有任何副作用)。</i>",
	},
	"Can_Of_Worms": {
		name: "Can_Of_Worms",
		cn_name: "蠕虫罐头",
		type: "crate",
		stackable: 5,
		rarity: 3,
		price: 5000,
		obtained: V.Can_Of_Worms || 0,
		icon: "fishing/crates/Can_Of_Worms.png",
		des: "可以打开得到一些蠕虫",
		purchase_info: "你购买了一罐<<icon 'fishing/crates/Can_Of_Worms.png'>>蠕虫罐头。你现在有蠕虫罐头($Can_Of_Worms)。<i>打开获得丰富的蛋白质。</i>",
	},
	"Pho": {
		name: "Pho",
		cn_name: "越南河粉",
		type: "food",
		stackable: 10,
		rarity: 3,
		price: 7500,
		obtained: V.Pho || 0,
		icon: "food/Pho.png",
		des: "- - 饥饿值<br>“粉它！”",
		purchase_info: "你购买了一份<<icon 'food/Pho.png'>>越南河粉。你现在有越南河粉($Pho)。",
	},
	"Celestial_Wand": {
		name: "Celestial_Wand",
		cn_name: "天界魔棒",
		type: "pet",
		stackable: false,
		rarity: 3,
		price: 1000000,
		obtained: V.Celestial_Wand,
		icon: "pet/pet_item/Celestial_Wand.png",
		des: "召唤埃斯蒂",
		purchase_info: "你购买了一个<<icon 'pet/pet_item/Celestial_Wand.png'>>天界魔棒。<i>你可以在孤儿院的卧室里使用它。</i>",
	},
	"Demon_Horns": {
		name: "Demon_Horns",
		cn_name: "恶魔角",
		type: "vanity_accessory",
		stackable: false,
		rarity: 3,
		price: 25000,
		obtained: V.Demon_Horns,
		icon: "vanity_accessories/Demon_Horns.png",
		des: "一对恶魔的犄角！防止恶魔转化点数衰退(不会防止对应的惩罚)<br><br><i>时装</i>：获得仅自己可见的恶魔犄角",
		purchase_info: "你购买了一对<<icon 'vanity_accessories/Demon_Horns.png'>>恶魔角。<i>试着在装备栏里戴上它。</i>",
	},
	"Pad_Thai": {
		name: "Pad_Thai",
		cn_name: "泰式炒面",
		type: "food",
		stackable: 10,
		rarity: 2,
		price: 5500,
		obtained: V.Pad_Thai || 0,
		icon: "food/Pad_Thai.png",
		des: "- - 饥饿值<br>“五星级辣度！”",
		purchase_info: "你购买了一份<<icon 'food/Pad_Thai.png'>>泰式炒面。你现在有泰式炒面($Pad_Thai)。",
	},
	"Sake": {
		name: "Sake",
		cn_name: "清酒",
		type: "food",
		stackable: 10,
		rarity: 1,
		price: 500,
		obtained: V.Sake || 0,
		icon: "food/Sake.png",
		des: "给予2小时的醉酒效果<br>“喝多了你会变成空手道大师。”",
		purchase_info: "你购买了一瓶<<icon 'food/Sake.png'>>清酒。你现在有清酒($Sake)。",
	},
	"Stopwatch": {
		name: "Stopwatch",
		cn_name: "秒表",
		type: "accessory",
		stackable: false,
		rarity: 1,
		price: 50000,
		obtained: V.Stopwatch,
		icon: "accessories/Stopwatch.png",
		des: "允许在合适的地点和时机掐表消磨时间",
		purchase_info: "你购买了一个<<icon 'accessories/Stopwatch.png'>>秒表。",
	},
	"Lifeform_Analyzer": {
		name: "Lifeform_Analyzer",
		cn_name: "生命体分析机",
		type: "accessory",
		stackable: false,
		rarity: 1,
		price: 50000,
		obtained: V.Lifeform_Analyzer,
		icon: "accessories/Lifeform_Analyzer.png",
		des: "显示NPC的位置（仅限主要角色）",
		purchase_info: "你购买了一个<<icon 'accessories/Lifeform_Analyzer.png'>>生命体分析机。",
	},
	"Thermometer": {
		name: "Thermometer",
		cn_name: "温度计",
		type: "accessory",
		stackable: false,
		rarity: 1,
		price: 50000,
		obtained: V.Thermometer,
		icon: "accessories/Thermometer.png",
		des: "显示室外温度、室内温度与水体温度",
		purchase_info: "你购买了一个<<icon 'accessories/Thermometer.png'>>温度计。",
	},
}

function getAllTravelingMerchantGoodsList() {
	let all_goods_list = Object.keys(setup.terraTravelingMerchantGoods);
	return all_goods_list;
}
window.getAllTravelingMerchantGoodsList = getAllTravelingMerchantGoodsList;