setup.fishingRequestRewardMain = {
	"Reinforced_Fishing_Pole": {
		name: "Reinforced_Fishing_Pole",
		cn_name: "强化钓竿",
		icon: "fishing/fishing_pole/Reinforced_Fishing_Pole.png",
		rarity: () => 1,
		condition: () => !V.Reinforced_Fishing_Pole && V.fishing_requests_finished_count >= 1,
		reward: () => V.Reinforced_Fishing_Pole = true,
	},
	"Angler_Hat": {
		name: "Angler_Hat",
		cn_name: "渔夫帽",
		icon: "armor/Angler_Hat.png",
		rarity: () => 1,
		condition: () => !V.Angler_Hat && V.fishing_requests_finished_count >= 10,
		reward: () => V.Angler_Hat = true,
	},
	"Angler_Vest": {
		name: "Angler_Vest",
		cn_name: "渔夫背心",
		icon: "armor/Angler_Vest.png",
		rarity: () => 1,
		condition: () => !V.Angler_Vest && V.fishing_requests_finished_count >= 15,
		reward: () => V.Angler_Vest = true,
	},
	"Angler_Pants": {
		name: "Angler_Pants",
		cn_name: "渔夫裤",
		icon: "armor/Angler_Pants.png",
		rarity: () => 1,
		condition: () => !V.Angler_Pants && V.fishing_requests_finished_count >= 20,
		reward: () => V.Angler_Pants = true,
	},
	"Bottomless_Honey_Bucket": {
		name: "Bottomless_Honey_Bucket",
		cn_name: "无底蜂蜜桶",
		icon: "tool/Bottomless_Honey_Bucket.png",
		rarity: () => 1,
		condition: () => !V.Bottomless_Honey_Bucket && V.fishing_request_selection === "Bumblebee_Tuna" && random(1,4) == 1,
		reward: () => V.Bottomless_Honey_Bucket = true,
	},
	"Golden_Fishing_Rod": {
		name: "Golden_Fishing_Rod",
		cn_name: "金钓竿",
		icon: "fishing/fishing_pole/Golden_Fishing_Rod.png",
		rarity: () => V.fishing_requests_finished_count == 30 ? 1 : 250,
		condition: () => !V.Golden_Fishing_Rod,
		reward: () => V.Golden_Fishing_Rod = true,
	},
	"Hotline_Fishing_Hook": {
		name: "Hotline_Fishing_Hook",
		cn_name: "熔线钓钩",
		icon: "fishing/fishing_pole/Hotline_Fishing_Hook.png",
		rarity: () => 100,
		condition: () => !V.Hotline_Fishing_Hook && V.fishing_requests_finished_count >= 25,
		reward: () => V.Hotline_Fishing_Hook = true,
	},
	"Fin_Wings": {
		name: "Fin_Wings",
		cn_name: "鳍翼",
		icon: "accessories/Fin_Wings.png",
		rarity: () => 70,
		condition: () => !V.Fin_Wings && V.fishing_requests_finished_count >= 10,
		reward: () => V.Fin_Wings = true,
	},
	"Bottomless_Water_Bucket": {
		name: "Bottomless_Water_Bucket",
		cn_name: "无底水桶",
		icon: "tool/Bottomless_Water_Bucket.png",
		rarity: () => V.fishing_requests_finished_count == 25 ? 1 : 70,
		condition: () => !V.Bottomless_Water_Bucket && V.fishing_requests_finished_count >= 5,
		reward: () => V.Bottomless_Water_Bucket = true,
	},
	"Super_Absorbant_Sponge": {
		name: "Super_Absorbant_Sponge",
		cn_name: "超级吸水棉",
		icon: "tool/Super_Absorbant_Sponge.png",
		rarity: () => 70,
		condition: () => !V.Super_Absorbant_Sponge && V.fishing_requests_finished_count >= 10,
		reward: () => V.Super_Absorbant_Sponge = true,
	},
	"Golden_Bug_Net": {
		name: "Golden_Bug_Net",
		cn_name: "金虫网",
		icon: "tool/Golden_Bug_Net.png",
		rarity: () => 80,
		condition: () => !V.Golden_Bug_Net,
		reward: () => V.Golden_Bug_Net = true,
	},
	"High_Test_Fishing_Line": {
		name: "High_Test_Fishing_Line",
		cn_name: "优质钓鱼线",
		icon: "fishing/fishing_accessories/High_Test_Fishing_Line.png",
		rarity: () => 40,
		condition: () => !V.High_Test_Fishing_Line,
		reward: () => V.High_Test_Fishing_Line = true,
	},
	"Angler_Earring": {
		name: "Angler_Earring",
		cn_name: "渔夫耳环",
		icon: "fishing/fishing_accessories/Angler_Earring.png",
		rarity: () => 40,
		condition: () => !V.Angler_Earring,
		reward: () => V.Angler_Earring = true,
	},
	"Tackle_Box": {
		name: "Tackle_Box",
		cn_name: "钓具箱",
		icon: "fishing/fishing_accessories/Tackle_Box.png",
		rarity: () => 40,
		condition: () => !V.Tackle_Box,
		reward: () => V.Tackle_Box = true,
	},
	"Fishermans_Pocket_Guide": {
		name: "Fishermans_Pocket_Guide",
		cn_name: "渔民袖珍宝典",
		icon: "fishing/fishing_accessories/Fishermans_Pocket_Guide.png",
		rarity: () => 30,
		condition: () => !setup.terraAccessories.Fishermans_Pocket_Guide.upgrades.some(a => V[a]),
		reward: () => V.Fishermans_Pocket_Guide = true,
	},
	"Weather_Radio": {
		name: "Weather_Radio",
		cn_name: "天气收音机",
		icon: "fishing/fishing_accessories/Weather_Radio.png",
		rarity: () => 30,
		condition: () => !setup.terraAccessories.Weather_Radio.upgrades.some(a => V[a]),
		reward: () => V.Weather_Radio = true,
	},
	"Sextant": {
		name: "Sextant",
		cn_name: "六分仪",
		icon: "fishing/fishing_accessories/Sextant.png",
		rarity: () => 30,
		condition: () => !setup.terraAccessories.Sextant.upgrades.some(a => V[a]),
		reward: () => V.Sextant = true,
	},
	"Fishing_Bobber": {
		name: "Fishing_Bobber",
		cn_name: "钓鱼浮标",
		icon: "fishing/fishing_accessories/Fishing_Bobber.png",
		rarity: () => 25,
		condition: () => !V.Fishing_Bobber,
		reward: () => V.Fishing_Bobber = true,
	},
	"Fishing_Potion": {
		name: "Fishing_Potion",
		cn_name: "钓鱼药水(_fishing_reward_potion)",
		icon: "potions/Fishing_Potion.png",
		rarity: () => 1,
		condition: () => random(1,3) == 1,
		reward: () => {
			T.fishing_reward_potion = random(2,5);
			V.Fishing_Potion += T.fishing_reward_potion;
		},
	},
	"Sonar_Potion": {
		name: "Sonar_Potion",
		cn_name: "声呐药水(_fishing_reward_potion)",
		icon: "potions/Sonar_Potion.png",
		rarity: () => 1,
		condition: () => random(1,2) == 1,
		reward: () => {
			T.fishing_reward_potion = random(2,5);
			V.Sonar_Potion += T.fishing_reward_potion;
		},
	},
	"Crate_Potion": {
		name: "Crate_Potion",
		cn_name: "宝匣药水(_fishing_reward_potion)",
		icon: "potions/Crate_Potion.png",
		rarity: () => 1,
		condition: () => true,
		reward: () => {
			T.fishing_reward_potion = random(2,5);
			V.Crate_Potion += T.fishing_reward_potion;
		},
	},
}