setup.terraBait = {
	"Apprentice_Bait": {
        name: "Apprentice_Bait",
        cn_name: "学徒诱饵",
		material: true,
        type: "bait",
        amount: V.Apprentice_Bait || 0,
		fishing_power: 15,
        icon: "fishing/bait/Apprentice_Bait.png",
		icon_placed: null,
    },
	"Journeyman_Bait": {
        name: "Journeyman_Bait",
        cn_name: "熟手诱饵",
		material: true,
        type: "bait",
        amount: V.Journeyman_Bait || 0,
		fishing_power: 30,
        icon: "fishing/bait/Journeyman_Bait.png",
		icon_placed: null,
    },
	"Master_Bait": {
        name: "Master_Bait",
        cn_name: "大师诱饵",
		material: true,
        type: "bait",
        amount: V.Master_Bait || 0,
		fishing_power: 50,
        icon: "fishing/bait/Master_Bait.png",
		icon_placed: null,
    },
    "Pink_Jellyfish_bait": {
        name: "Pink_Jellyfish_bait",
        cn_name: "粉水母",
		material: false,
        type: "bait",
        amount: V.Pink_Jellyfish_bait || 0,
		fishing_power: 20,
        icon: "fishing/bait/Pink_Jellyfish_bait.png",
		icon_placed: null,
    },
	"Blue_Jellyfish_bait": {
        name: "Blue_Jellyfish_bait",
        cn_name: "蓝水母",
		material: false,
        type: "bait",
        amount: V.Blue_Jellyfish_bait || 0,
		fishing_power: 20,
        icon: "fishing/bait/Blue_Jellyfish_bait.png",
		icon_placed: null,
    },
	"Green_Jellyfish_bait": {
        name: "Green_Jellyfish_bait",
        cn_name: "绿水母",
		material: false,
        type: "bait",
        amount: V.Green_Jellyfish_bait || 0,
		fishing_power: 20,
        icon: "fishing/bait/Green_Jellyfish_bait.png",
		icon_placed: null,
    },
	"Worm": {
        name: "Worm",
        cn_name: "蠕虫",
		material: true,
        type: "bait",
        amount: V.Worm || 0,
		fishing_power: 25,
        icon: "fishing/bait/Worm.png",
		icon_placed: "placed_bait/Placed_Worm.gif",
    },
	"Enchanted_Nightcrawler": {
        name: "Enchanted_Nightcrawler",
        cn_name: "附魔夜行者",
		material: false,
        type: "bait",
        amount: V.Enchanted_Nightcrawler || 0,
		fishing_power: 35,
        icon: "fishing/bait/Enchanted_Nightcrawler.png",
		icon_placed: "placed_bait/Placed_Enchanted_Nightcrawler.gif",
    },
	"Firefly": {
        name: "Firefly",
        cn_name: "萤火虫",
		material: false,
        type: "firefly",
        amount: V.Firefly || 0,
		fishing_power: 20,
        icon: "fishing/bait/Firefly.png",
		icon_placed: "placed_bait/Placed_Firefly.png",
    },
	"Lightning_Bug": {
        name: "Lightning_Bug",
        cn_name: "荧光虫",
		material: false,
        type: "firefly",
        amount: V.Lightning_Bug || 0,
		fishing_power: 35,
        icon: "fishing/bait/Lightning_Bug.png",
		icon_placed: "placed_bait/Placed_Lightning_Bug.png",
    },
	"Lavafly": {
        name: "Lavafly",
        cn_name: "熔岩萤火虫",
		material: false,
        type: "lavaProof",
        amount: V.Lavafly || 0,
		fishing_power: 25,
        icon: "fishing/bait/Lavafly.png",
		icon_placed: null,
    },
	"Snail": {
        name: "Snail",
        cn_name: "蜗牛",
		material: false,
        type: "bait",
        amount: V.Snail || 0,
		fishing_power: 10,
        icon: "fishing/bait/Snail.png",
		icon_placed: "placed_bait/Placed_Snail.gif",
    },
	"Glowing_Snail": {
        name: "Glowing_Snail",
        cn_name: "发光蜗牛",
		material: false,
        type: "bait",
        amount: V.Glowing_Snail || 0,
		fishing_power: 15,
        icon: "fishing/bait/Glowing_Snail.png",
		icon_placed: "placed_bait/Placed_Glowing_Snail.gif",
    },
	"Magma_Snail": {
        name: "Magma_Snail",
        cn_name: "岩浆蜗牛",
		material: false,
        type: "lavaProof",
        amount: V.Magma_Snail || 0,
		fishing_power: 35,
        icon: "fishing/bait/Magma_Snail.png",
		icon_placed: null,
    },
	"Grasshopper": {
        name: "Grasshopper",
        cn_name: "蚱蜢",
		material: false,
        type: "bait",
        amount: V.Grasshopper || 0,
		fishing_power: 10,
        icon: "fishing/bait/Grasshopper.png",
		icon_placed: "placed_bait/Placed_Grasshopper.gif",
    },
	"Monarch_Butterfly": {
        name: "Monarch_Butterfly",
        cn_name: "帝王蝶",
        type: "butterfly",
        amount: V.Monarch_Butterfly || 0,
		fishing_power: 5,
        icon: "fishing/bait/Monarch_Butterfly.png",
		icon_placed: "placed_bait/Placed_Monarch_Butterfly.gif",
    },
	"Sulphur_Butterfly": {
        name: "Sulphur_Butterfly",
        cn_name: "黄粉蝶",
		material: false,
        type: "butterfly",
        amount: V.Sulphur_Butterfly || 0,
		fishing_power: 10,
        icon: "fishing/bait/Sulphur_Butterfly.png",
		icon_placed: "placed_bait/Placed_Sulphur_Butterfly.gif",
    },
	"Zebra_Swallowtail_Butterfly": {
        name: "Zebra_Swallowtail_Butterfly",
        cn_name: "带凤蝶",
		material: false,
        type: "butterfly",
        amount: V.Zebra_Swallowtail_Butterfly || 0,
		fishing_power: 15,
        icon: "fishing/bait/Zebra_Swallowtail_Butterfly.png",
		icon_placed: "placed_bait/Placed_Zebra_Swallowtail_Butterfly.gif",
    },
	"Ulysses_Butterfly": {
        name: "Ulysses_Butterfly",
        cn_name: "翠凤蝶",
		material: false,
        type: "butterfly",
        amount: V.Ulysses_Butterfly || 0,
		fishing_power: 20,
        icon: "fishing/bait/Ulysses_Butterfly.png",
		icon_placed: "placed_bait/Placed_Ulysses_Butterfly.gif",
    },
	"Julia_Butterfly": {
        name: "Julia_Butterfly",
        cn_name: "珠袖蝶",
		material: false,
        type: "butterfly",
        amount: V.Julia_Butterfly || 0,
		fishing_power: 25,
        icon: "fishing/bait/Julia_Butterfly.png",
		icon_placed: "placed_bait/Placed_Julia_Butterfly.gif",
    },
	"Red_Admiral_Butterfly": {
        name: "Red_Admiral_Butterfly",
        cn_name: "红蛱蝶",
		material: false,
        type: "butterfly",
        amount: V.Red_Admiral_Butterfly || 0,
		fishing_power: 30,
        icon: "fishing/bait/Red_Admiral_Butterfly.png",
		icon_placed: "placed_bait/Placed_Red_Admiral_Butterfly.gif",
    },
	"Purple_Emperor_Butterfly": {
        name: "Purple_Emperor_Butterfly",
        cn_name: "紫蛱蝶",
		material: false,
        type: "butterfly",
        amount: V.Purple_Emperor_Butterfly || 0,
		fishing_power: 35,
        icon: "fishing/bait/Purple_Emperor_Butterfly.png",
		icon_placed: "placed_bait/Placed_Purple_Emperor_Butterfly.gif",
    },
	"Tree_Nymph_Butterfly": {
        name: "Tree_Nymph_Butterfly",
        cn_name: "帛斑蝶",
		material: false,
        type: "butterfly",
        amount: V.Tree_Nymph_Butterfly || 0,
		fishing_power: 50,
        icon: "fishing/bait/Tree_Nymph_Butterfly.png",
		icon_placed: "placed_bait/Placed_Tree_Nymph_Butterfly.gif",
    },
	"Hell_Butterfly": {
        name: "Hell_Butterfly",
        cn_name: "地狱蝴蝶",
		material: false,
        type: "lavaproof",
        amount: V.Hell_Butterfly || 0,
		fishing_power: 15,
        icon: "fishing/bait/Hell_Butterfly.png",
		icon_placed: "placed_bait/Placed_Hell_Butterfly.gif",
    },
	"Red_Dragonfly": {
        name: "Red_Dragonfly",
        cn_name: "红蜻蜓",
		material: false,
        type: "dragonfly",
        amount: V.Red_Dragonfly || 0,
		fishing_power: 20,
        icon: "fishing/bait/Red_Dragonfly.png",
		icon_placed: "placed_bait/Placed_Red_Dragonfly.gif",
    },
	"Orange_Dragonfly": {
        name: "Orange_Dragonfly",
        cn_name: "橙蜻蜓",
		material: false,
        type: "dragonfly",
        amount: V.Orange_Dragonfly || 0,
		fishing_power: 20,
        icon: "fishing/bait/Orange_Dragonfly.png",
		icon_placed: "placed_bait/Placed_Orange_Dragonfly.gif",
    },
	"Yellow_Dragonfly": {
        name: "Yellow_Dragonfly",
        cn_name: "黄蜻蜓",
		material: false,
        type: "dragonfly",
        amount: V.Yellow_Dragonfly || 0,
		fishing_power: 20,
        icon: "fishing/bait/Yellow_Dragonfly.png",
		icon_placed: "placed_bait/Placed_Yellow_Dragonfly.gif",
    },
	"Green_Dragonfly": {
        name: "Green_Dragonfly",
        cn_name: "绿蜻蜓",
		material: false,
        type: "dragonfly",
        amount: V.Green_Dragonfly || 0,
		fishing_power: 20,
        icon: "fishing/bait/Green_Dragonfly.png",
		icon_placed: "placed_bait/Placed_Green_Dragonfly.gif",
    },
	"Blue_Dragonfly": {
        name: "Blue_Dragonfly",
        cn_name: "蓝蜻蜓",
		material: false,
        type: "dragonfly",
        amount: V.Blue_Dragonfly || 0,
		fishing_power: 20,
        icon: "fishing/bait/Blue_Dragonfly.png",
		icon_placed: "placed_bait/Placed_Blue_Dragonfly.gif",
    },
	"Black_Dragonfly": {
        name: "Black_Dragonfly",
        cn_name: "黑蜻蜓",
		material: false,
        type: "dragonfly",
        amount: V.Black_Dragonfly || 0,
		fishing_power: 20,
        icon: "fishing/bait/Black_Dragonfly.png",
		icon_placed: "placed_bait/Placed_Black_Dragonfly.gif",
    },
	"Maggot": {
        name: "Maggot",
        cn_name: "蝇蛆",
		material: false,
        type: "bait",
        amount: V.Maggot || 0,
		fishing_power: 22,
        icon: "fishing/bait/Maggot.png",
		icon_placed: "placed_bait/Placed_Maggot.gif",
    },
	"Stinkbug": {
        name: "Stinkbug",
        cn_name: "臭虫",
		material: false,
        type: "bait",
        amount: V.Stinkbug || 0,
		fishing_power: 10,
        icon: "fishing/bait/Stinkbug.png",
		icon_placed: "placed_bait/Placed_Stinkbug.gif",
    },
	"Ladybug": {
        name: "Ladybug",
        cn_name: "瓢虫",
		material: false,
        type: "bait",
        amount: V.Ladybug || 0,
		fishing_power: 17,
        icon: "fishing/bait/Ladybug.png",
		icon_placed: "placed_bait/Placed_Ladybug.gif",
    },
	"Gold_Butterfly": {
        name: "Gold_Butterfly",
        cn_name: "金蝴蝶",
		material: false,
        type: "butterfly",
        amount: V.Gold_Butterfly || 0,
		fishing_power: 50,
        icon: "fishing/bait/Gold_Butterfly.png",
		icon_placed: "placed_bait/Placed_Gold_Butterfly.gif",
    },
	"Gold_Grasshopper": {
        name: "Gold_Grasshopper",
        cn_name: "金蚱蜢",
		material: false,
        type: "bait",
        amount: V.Gold_Grasshopper || 0,
		fishing_power: 50,
        icon: "fishing/bait/Gold_Grasshopper.png",
		icon_placed: "placed_bait/Placed_Gold_Grasshopper.gif",
    },
	"Gold_Worm": {
        name: "Gold_Worm",
        cn_name: "金蠕虫",
		material: false,
        type: "bait",
        amount: V.Gold_Worm || 0,
		fishing_power: 50,
        icon: "fishing/bait/Gold_Worm.png",
		icon_placed: "placed_bait/Placed_Gold_Worm.gif",
    },
	"Gold_Ladybug": {
        name: "Gold_Ladybug",
        cn_name: "金瓢虫",
		material: false,
        type: "bait",
        amount: V.Gold_Ladybug || 0,
		fishing_power: 50,
        icon: "fishing/bait/Gold_Ladybug.png",
		icon_placed: "placed_bait/Placed_Gold_Ladybug.gif",
    },
	"Gold_Dragonfly": {
        name: "Gold_Dragonfly",
        cn_name: "金蜻蜓",
		material: false,
        type: "dragonfly",
        amount: V.Gold_Dragonfly || 0,
		fishing_power: 50,
        icon: "fishing/bait/Gold_Dragonfly.png",
		icon_placed: "placed_bait/Placed_Gold_Dragonfly.gif",
    },
	"Truffle_Worm": {
        name: "Truffle_Worm",
        cn_name: "松露虫",
		material: false,
        type: "boss_summoner",
        amount: V.Truffle_Worm || 0,
		fishing_power: 666,
        icon: "fishing/bait/Truffle_Worm.png",
		icon_placed: "placed_bait/Placed_Truffle_Worm.gif",
    },
}

function getAllBaitList() {
	let all_bait_list = Object.keys(setup.terraBait);
	return all_bait_list;
}
window.getAllBaitList = getAllBaitList

function getBaitObtainedList() {
	for (let bait in setup.terraBait) {
        setup.terraBait[bait].amount = V[bait] || 0;
    }
    let bait_obtained = Object.keys(setup.terraBait);
    return bait_obtained.filter(bait => {
        return setup.terraBait[bait].amount > 0;
    });
}
window.getBaitObtainedList = getBaitObtainedList;