setup.terraFish = {
	"Salmon": {
        name: "Salmon",
        cn_name: "三文鱼",
		material: true,
        type: "cookable",
		rarity: ["extremely_rare","very_rare","rare","uncommon"],
		rarity_cn: "不常见",
		catching_place: ["lake_fishing_rock","waterfall"],
        price: 7.5,
        amount: V.Salmon || 0,
        icon: "fishing/fish/Salmon.png",
		difficulty: 0.75,
    },
    "Bass": {
        name: "Bass",
        cn_name: "鲈鱼",
		material: true,
        type: "cookable",
		rarity: ["common","plentiful"],
		rarity_cn: "丰富",
		catching_place: ["lake_fishing_rock","waterfall","barb_street","gulch","farm_woodland","temple_garden","temple_garden_artificial","wolf_cave_clearing","wolf_cave_clearing_artificial","eden_clearing","eden_clearing_artificial","rocky_hillock","ice"],
		price: 5,
        amount: V.Bass || 0,
        icon: "fishing/fish/Bass.png",
		difficulty: 0.25,
    },
	"Shrimp": {
        name: "Shrimp",
        cn_name: "虾",
		material: true,
        type: "cookable",
		rarity: ["uncommon"],
		rarity_cn: "不常见",
		catching_place: ["beach","bog"],
        price: 15,
        amount: V.Shrimp || 0,
        icon: "fishing/fish/Shrimp.png",
		difficulty: 0.75,
    },
	"Tuna": {
        name: "Tuna",
        cn_name: "金枪鱼",
		material: true,
        type: "cookable",
		rarity: ["common"],
		rarity_cn: "常见",
		catching_place: ["beach","bog"],
        price: 7.5,
        amount: V.Tuna || 0,
        icon: "fishing/fish/Tuna.png",
		difficulty: 0.5,
    },
	"Red_Snapper": {
        name: "Red_Snapper",
        cn_name: "红鲷鱼",
		material: true,
        type: "cookable",
		rarity: ["common"],
		rarity_cn: "常见",
		catching_place: ["beach","bog"],
        price: 7.5,
        amount: V.Red_Snapper || 0,
        icon: "fishing/fish/Red_Snapper.png",
		difficulty: 0.5,
    },
	"Trout": {
        name: "Trout",
        cn_name: "鳟鱼",
		material: true,
        type: "cookable",
		rarity: ["plentiful"],
		rarity_cn: "丰富",
		catching_place: ["beach","bog"],
        price: 5,
        amount: V.Trout || 0,
        icon: "fishing/fish/Trout.png",
		difficulty: 0.25,
    },
	"Golden_Carp": {
        name: "Golden_Carp",
        cn_name: "金鲤鱼",
		material: false,
        type: "fish",
		rarity: ["extremely_rare"],
		rarity_cn: "极度罕见",
		catching_place: ["barb_street","gulch","wolf_cave_clearing","wolf_cave_clearing_artificial","ice"],
        price: 1000,
        amount: V.Golden_Carp || 0,
        icon: "fishing/fish/Golden_Carp.png",
		difficulty: 1.5,
    },
	"Stinkfish": {
        name: "Stinkfish",
        cn_name: "臭味鱼",
		material: true,
        type: "potion",
		rarity: ["very_rare","rare"],
		rarity_cn: "罕见",
		catching_place: ["barb_street","gulch","wolf_cave_clearing","wolf_cave_clearing_artificial","ice"],
        price: 25,
        amount: V.Stinkfish || 0,
        icon: "fishing/fish/Stinkfish.png",
		difficulty: 1,
    },
	"Armored_Cavefish": {
        name: "Armored_Cavefish",
        cn_name: "装甲洞穴鱼",
		material: true,
        type: "potion",
		rarity: ["uncommon"],
		rarity_cn: "不常见",
		catching_place: ["barb_street","gulch","wolf_cave_clearing","wolf_cave_clearing_artificial","ice"],
        price: 15,
        amount: V.Armored_Cavefish || 0,
        icon: "fishing/fish/Armored_Cavefish.png",
		difficulty: 0.75,
    },
	"Specular_Fish": {
        name: "Specular_Fish",
        cn_name: "镜面鱼",
		material: true,
        type: "potion",
		rarity: ["common"],
		rarity_cn: "常见",
		catching_place: ["barb_street","gulch","wolf_cave_clearing","wolf_cave_clearing_artificial","ice"],
        price: 7.5,
        amount: V.Specular_Fish || 0,
        icon: "fishing/fish/Specular_Fish.png",
		difficulty: 0.5,
    },
	"Flounder": {
        name: "Flounder",
        cn_name: "偏口鱼",
		material: true,
        type: "cookable",
		rarity: ["common","plentiful"],
		rarity_cn: "丰富",
		catching_place: ["moor"],
        price: 1.5,
        amount: V.Flounder || 0,
        icon: "fishing/fish/Flounder.png",
		difficulty: 0.25,
    },
	"Rock_Lobster": {
        name: "Rock_Lobster",
        cn_name: "岩石龙虾",
		material: true,
        type: "cookable",
		rarity: ["common","plentiful"],
		rarity_cn: "丰富",
		catching_place: ["moor"],
        price: 10,
        amount: V.Rock_Lobster || 0,
        icon: "fishing/fish/Rock_Lobster.png",
		difficulty: 0.5,
    },
	"Honeyfin": {
        name: "Honeyfin",
        cn_name: "蜂蜜鱼",
		material: true,
        type: "potion",
		rarity: ["extremely_rare","very_rare","rare","uncommon","common","plentiful"],
		rarity_cn: "丰富",
		catching_place: ["honey"],
        price: 15,
        amount: V.Honeyfin || 0,
        icon: "fishing/fish/Honeyfin.png",
		difficulty: 0.75,
    },
	"Double_Cod": {
        name: "Double_Cod",
        cn_name: "双鳍鳕鱼",
		material: true,
        type: "potion",
		rarity: ["extremely_rare","very_rare","rare","uncommon"],
		rarity_cn: "不常见",
		catching_place: ["farm_woodland"],
        price: 15,
        amount: V.Double_Cod || 0,
        icon: "fishing/fish/Double_Cod.png",
		difficulty: 0.75,
    },
	"Variegated_Lardfish": {
        name: "Variegated_Lardfish",
        cn_name: "斑驳油鱼",
		material: true,
        type: "potion",
		rarity: ["extremely_rare","very_rare","rare","uncommon"],
		rarity_cn: "不常见",
		catching_place: ["farm_woodland"],
        amount: V.Variegated_Lardfish || 0,
        icon: "fishing/fish/Variegated_Lardfish.png",
		difficulty: 0.75,
    },
	"Neon_Tetra": {
        name: "Neon_Tetra",
        cn_name: "霓虹脂鲤",
		material: true,
        type: "potion",
		rarity: ["common"],
		rarity_cn: "常见",
		catching_place: ["farm_woodland"],
        price: 15,
        amount: V.Neon_Tetra || 0,
        icon: "fishing/fish/Neon_Tetra.png",
		difficulty: 0.5,
    },
	"Chaos_Fish": {
        name: "Chaos_Fish",
        cn_name: "混沌鱼",
		material: true,
        type: "potion",
		rarity: ["extremely_rare","very_rare"],
		rarity_cn: "十分罕见",
		catching_place: ["temple_garden","temple_garden_artificial"],
        price: 300,
        amount: V.Chaos_Fish || 0,
        icon: "fishing/fish/Chaos_Fish.png",
		difficulty: 1.25,
    },
	"Prismite": {
        name: "Prismite",
        cn_name: "七彩矿鱼",
		material: true,
        type: "potion",
		rarity: ["rare"],
		rarity_cn: "罕见",
		catching_place: ["temple_garden","temple_garden_artificial"],
        price: 100,
        amount: V.Prismite || 0,
        icon: "fishing/fish/Prismite.png",
		difficulty: 1,
    },
	"Princess_Fish": {
        name: "Princess_Fish",
        cn_name: "公主鱼",
		material: true,
        type: "potion",
		rarity: ["uncommon"],
		rarity_cn: "不常见",
		catching_place: ["temple_garden","temple_garden_artificial"],
        price: 25,
        amount: V.Princess_Fish || 0,
        icon: "fishing/fish/Princess_Fish.png",
		difficulty: 0.75,
    },
	"Damselfish": {
        name: "Damselfish",
        cn_name: "雀鲷",
		material: true,
        type: "potion",
		rarity: ["extremely_rare","very_rare","rare","uncommon"],
		rarity_cn: "不常见",
		catching_place: ["eden_clearing","eden_clearing_artificial","rocky_hillock"],
        price: 30,
        amount: V.Damselfish || 0,
        icon: "fishing/fish/Damselfish.png",
		difficulty: 0.75,
    },
	"Frost_Minnow": {
        name: "Frost_Minnow",
        cn_name: "寒霜绦鱼",
		material: true,
        type: "potion",
		rarity: ["rare","uncommon"],
		rarity_cn: "不常见",
		catching_place: ["ice"],
        price: 15,
        amount: V.Frost_Minnow || 0,
        icon: "fishing/fish/Frost_Minnow.png",
		difficulty: 0.75,
    },
	"Atlantic_Cod": {
        name: "Atlantic_Cod",
        cn_name: "大西洋鳕鱼",
		material: true,
        type: "cookable",
		rarity: ["common"],
		rarity_cn: "常见",
		catching_place: ["ice"],
        price: 7.5,
        amount: V.Atlantic_Cod || 0,
        icon: "fishing/fish/Atlantic_Cod.png",
		difficulty: 0.25,
    },
	"Flarefin_Koi": {
        name: "Flarefin_Koi",
        cn_name: "闪鳍锦鲤",
		material: true,
        type: "potion",
		rarity: ["extremely_rare","very_rare"],
		rarity_cn: "非常罕见",
		catching_place: ["lava"],
        price: 50,
        amount: V.Flarefin_Koi || 0,
        icon: "fishing/fish/Flarefin_Koi.png",
		difficulty: 1.25,
    },
	"Obsidifish": {
        name: "Obsidifish",
        cn_name: "黑曜石鱼",
		material: true,
        type: "potion",
		rarity: ["rare"],
		rarity_cn: "罕见",
		catching_place: ["lava"],
        price: 15,
        amount: V.Obsidifish || 0,
        icon: "fishing/fish/Obsidifish.png",
		difficulty: 1,
    },
	"Greenwave_Loach": {
        name: "Greenwave_Loach",
        cn_name: "绿波泥鳅",
		material: false,
        type: "fish",
		rarity: ["extremely_rare","very_rare"],
		rarity_cn: "非常罕见",
		catching_place: ["bird_tower","bird_tower_artificial"],
        price: 1000,
        amount: V.Greenwave_Loach || 0,
        icon: "fishing/fish/Greenwave_Loach.png",
		difficulty: 1.25,
    },
	"Sunken_Sailfish": {
        name: "Sunken_Sailfish",
        cn_name: "沉沦帆鱼",
		material: true,
        type: "potion",
		rarity: ["rare","uncommon"],
		rarity_cn: "不常见",
		catching_place: ["bird_tower","bird_tower_artificial"],
        price: 70,
        amount: V.Sunken_Sailfish || 0,
        icon: "fishing/fish/Sunken_Sailfish.png",
		difficulty: 0.75,
    },
	"Prismatic_Guppy": {
        name: "Prismatic_Guppy",
        cn_name: "棱晶孔雀鱼",
		material: true,
        type: "cookable",
		rarity: ["common","plentiful"],
		rarity_cn: "丰富",
		catching_place: ["bird_tower","bird_tower_artificial"],
        price: 5,
        amount: V.Prismatic_Guppy || 0,
        icon: "fishing/fish/Prismatic_Guppy.png",
		difficulty: 0.25,
    },
	"Charred_Lasher": {
        name: "Charred_Lasher",
        cn_name: "焦黑鞭笞者",
		material: false,
        type: "fish",
		rarity: ["extremely_rare"],
		rarity_cn: "极度罕见",
		catching_place: ["trash"],
        price: 1000,
        amount: V.Charred_Lasher || 0,
        icon: "fishing/fish/Charred_Lasher.png",
		difficulty: 1.5,
    },
	"Coastal_Demonfish": {
        name: "Coastal_Demonfish",
        cn_name: "海岸恶魔鱼",
		material: true,
        type: "potion",
		rarity: ["very_rare","rare","uncommon"],
		rarity_cn: "不常见",
		catching_place: ["trash"],
        price: 8,
        amount: V.Coastal_Demonfish || 0,
        icon: "fishing/fish/Coastal_Demonfish.png",
		difficulty: 0.75,
    },
	"Crag_Bullhead": {
        name: "Crag_Bullhead",
        cn_name: "硫火崖回鱼", 
        type: "cookable",
		rarity: ["common","plentiful"],
		rarity_cn: "丰富",
		catching_place: ["trash"],
        price: 5,
        amount: V.Crag_Bullhead || 0,
        icon: "fishing/fish/Crag_Bullhead.png",
		difficulty: 0.25,
    },
}

function getAllFishList() {
    let all_fish_list = Object.keys(setup.terraFish);
	return all_fish_list;
}
window.getAllFishList = getAllFishList;

function getFishObtainedList() {
	for (let fish in setup.terraFish) {
        setup.terraFish[fish].amount = V[fish] || 0;
    }
    let fish_obtained = Object.keys(setup.terraFish);
    return fish_obtained.filter(fish => {
        return setup.terraFish[fish].amount > 0;
    });
}
window.getFishObtainedList = getFishObtainedList;