setup.terraPet = {
	"Royal_Delight": {
		name: "Royal_Delight",
		cn_name: "皇家美味",
		type: "pet",
		obtained: V.Royal_Delight,
		icon_item: "pet/pet_item/Royal_Delight.png",
		icon_projectile: "pet/pet_projectile/Slime_Prince.gif",
		sidebarCoordinate: {x: 10, y: 148},
		des_item: "召唤史莱姆王子<br><i>“适合国王的甜点！”</i>",
		des_projectile: "<span class='teal'>“他听命于上级！”</span><span class='gold'><i>感谢游玩泰拉瑞亚拓展模组！</i></span>",
	},
	"Zephyr_Fish": {
		name: "Zephyr_Fish",
		cn_name: "和风鱼",
		type: "pet",
		obtained: V.Zephyr_Fish,
		icon_item: "pet/pet_item/Zephyr_Fish.png",
		icon_projectile: "pet/pet_projectile/Zephyr_Fish.gif",
		sidebarCoordinate: {x: -10, y: 28},
		des_item: "召唤宠物和风鱼",
		des_projectile: "“它喜欢在你周围游泳。”",
	},
	"Strange_Orb": {
		name: "Strange_Orb",
		cn_name: "奇光球",
		type: "light_pet",
		obtained: V.Strange_Orb,
		icon_item: "pet/pet_item/Strange_Orb.png",
		icon_projectile: "pet/pet_projectile/Ocean_Spirit_(sleep).png",
		sidebarCoordinate: {x: -10, y: 18},
		des_item: "召唤一个迷你海洋之灵",
		des_projectile: "“音轻体柔，小巧玲珑。”",
	},
	"Rusted_Jingle_Bell": {
		name: "Rusted_Jingle_Bell",
		cn_name: "锈蚀铃铛",
		type: "light_pet",
		obtained: V.Rusted_Jingle_Bell,
		icon_item: "pet/pet_item/Rusted_Jingle_Bell.png",
		icon_projectile: "pet/pet_projectile/Baby_Ghost_Bell_(pet).gif",
		sidebarCoordinate: {x: -10, y: 18},
		des_item: "召唤一只小鬼铃水母",
		des_projectile: "“小心不要戳破那个泡泡。”",
	},
	"Shark_Bait": {
		name: "Shark_Bait",
		cn_name: "鲨鱼鱼饵",
		type: "pet",
		obtained: V.Shark_Bait,
		icon_item: "pet/pet_item/Shark_Bait.png",
		icon_projectile: "pet/pet_projectile/Shark_Pup_in_Bubble.gif",
		sidebarCoordinate: {x: -10, y: 28},
		des_item: "召唤小鲨鱼<br><i>“嘟嘟嘟嘟嘟嘟。”</i>",
		des_projectile: "“嘟嘟嘟嘟嘟嘟。”",
	},
	"Stardrop": {
		name: "Stardrop",
		cn_name: "星之果实",
		type: "pet",
		obtained: V.Stardrop,
		icon_item: "pet/pet_item/Stardrop.png",
		icon_projectile: "pet/pet_projectile/Junimo.gif",
		sidebarCoordinate: {x: 10, y: 148},
		des_item: "召唤祝尼魔<br><i>“来自异界的神秘果实。味道如梦如幻……”</i>",
		des_projectile: "“可爱的森林守护者。”",
	},
	"Celestial_Wand": {
		name: "Celestial_Wand",
		cn_name: "天界魔棒",
		type: "pet",
		obtained: V.Celestial_Wand,
		icon_item: "pet/pet_item/Celestial_Wand.png",
		icon_projectile: "pet/pet_projectile/Estee.gif",
		sidebarCoordinate: {x: -10, y: 28},
		des_item: "召唤埃斯蒂",
		des_projectile: "“埃斯蒂闪闪发光。”",
	},
	"Bamboo_Leaf": {
		name: "Bamboo_Leaf",
		cn_name: "竹叶",
		type: "pet",
		obtained: V.Bamboo_Leaf,
		icon_item: "pet/pet_item/Bamboo_Leaf.png",
		icon_projectile: "pet/pet_projectile/Baby_Red_Panda.gif",
		sidebarCoordinate: {x: 6, y: 148},
		des_item: "召唤小熊猫宝宝",
		des_projectile: "“小熊猫宝宝充满了活力。”",
	},
	"Bedazzled_Nectar": {
		name: "Bedazzled_Nectar",
		cn_name: "眩晕花蜜",
		type: "pet",
		obtained: V.Bedazzled_Nectar,
		icon_item: "pet/pet_item/Bedazzled_Nectar.png",
		icon_projectile: "pet/pet_projectile/Glittery_Butterfly.gif",
		sidebarCoordinate: {x: -10, y: 28},
		des_item: "召唤宠物蝴蝶<br><i>“只要最好、最精致的花蜜！”</i>",
		des_projectile: "“真的真的荒唐。”",
	},
	"Blue_Chicken_Egg": {
		name: "Blue_Chicken_Egg",
		cn_name: "蓝鸡蛋",
		type: "pet",
		obtained: V.Blue_Chicken_Egg,
		icon_item: "pet/pet_item/Blue_Chicken_Egg.png",
		icon_projectile: "pet/pet_projectile/Blue_Chicken.gif",
		sidebarCoordinate: {x: 10, y: 148},
		des_item: "召唤蓝鸡<br><i>“普普通通的蓝色鸡蛋”</i>",
		des_projectile: "“名牌上写着'Shane'”",
	},
	"Exotic_Chew_Toy": {
		name: "Exotic_Chew_Toy",
		cn_name: "奇异咀嚼玩具",
		type: "pet",
		obtained: V.Exotic_Chew_Toy,
		icon_item: "pet/pet_item/Exotic_Chew_Toy.png",
		icon_projectile: "pet/pet_projectile/Fennec_Fox.gif",
		sidebarCoordinate: {x: 6, y: 148},
		des_item: "召唤耳廓狐<br><i>“它的叫声是惊人的96千赫！”</i>",
		des_projectile: "“狐狸说了什么？更进一步，狐狸听到了什么？！”",
	},
	"Birdie_Rattle": {
		name: "Birdie_Rattle",
		cn_name: "小鸟拨浪鼓",
		type: "pet",
		obtained: V.Birdie_Rattle,
		icon_item: "pet/pet_item/Birdie_Rattle.png",
		icon_projectile: "pet/pet_projectile/Lil_Harpy.gif",
		sidebarCoordinate: {x: -10, y: 28},
		des_item: "召唤鸟妖宝宝<br><i>“不适合你的日常小鹦鹉”</i>",
		des_projectile: "“从天而降的可爱”",
	},
	"Companion_Cube": {
		name: "Companion_Cube",
		cn_name: "同伴方块",
		type: "pet",
		obtained: V.Companion_Cube,
		icon_item: "pet/pet_item/Companion_Cube.png",
		icon_projectile: "pet/pet_projectile/Companion_Cube_(pet).png",
		sidebarCoordinate: {x: 10, y: 148},
		des_item: "召唤同伴方块<br><i>“易受熔岩伤害！”</i>",
		des_projectile: "“永远不会威胁要刺伤你，而且，其实，不会说话”",
	},
	"Eye_Bone": {
		name: "Eye_Bone",
		cn_name: "眼骨",
		type: "pet",
		obtained: V.Eye_Bone,
		icon_item: "pet/pet_item/Eye_Bone.png",
		icon_projectile: "pet/pet_projectile/Chester.gif",
		sidebarCoordinate: {x: 10, y: 148},
		des_item: "召唤一只活宝箱<br><i>“它正在审视我的灵魂。”</i>",
		des_projectile: "“奥特·冯·切斯特菲尔德先生”",
	},
	"Glommers_Flower": {
		name: "Glommers_Flower",
		cn_name: "格罗姆的花",
		type: "pet",
		obtained: V.Glommers_Flower,
		icon_item: "pet/pet_item/Glommers_Flower.png",
		icon_projectile: "pet/pet_projectile/Glommer.gif",
		sidebarCoordinate: {x: -10, y: 28},
		des_item: "召唤格罗姆<br><i>“花瓣在阳光下闪闪发光。”</i>",
		des_projectile: "“毛茸茸！还黏糊糊……”",
	},
	"Parrot_Cracker": {
		name: "Parrot_Cracker",
		cn_name: "鹦鹉饼干",
		type: "pet",
		obtained: V.Parrot_Cracker,
		icon_item: "pet/pet_item/Parrot_Cracker.png",
		icon_projectile: "pet/pet_projectile/Pet_Parrot.gif",
		sidebarCoordinate: {x: -10, y: 28},
		des_item: "召唤宠物鹦鹉<br><i>“不适合人类食用。”</i>",
		des_projectile: "“波利想要饼干”",
	},
}

function getAllPetList() {
	let all_pet_list = Object.keys(setup.terraPet);
	return all_pet_list;
}
window.getAllPetList = getAllPetList;

function getPetObtained() {
	for (let pet in setup.terraPet) {
        setup.terraPet[pet].obtained = V[pet];
    }
    let pet_obtained = Object.keys(setup.terraPet);
    return pet_obtained.filter(pet => {
        return setup.terraPet[pet].obtained !== undefined;
    });
}
window.getPetObtained = getPetObtained;